### PR TITLE
Fixed Population Hud Wrapping

### LINKED ISSUE #2154: Population number starts wrapping when the population is big in Microbe HUD
Not sure on other screen resolutions, but for a 1920x1080, once the population reaches 10k, digits start going to a new line.

### PR DESCRIPTION
**Pull request by Pickles4Life**
When appropriate population is displayed in the thousands and millions. Fixes #2154.

### CODE REVIEW

File: src/microbe_stage/MicrobeHUD.cs [hunk 1]
```diff
@@ -807,7 +807,20 @@ private void UpdateHealth(float delta)
 
     private void UpdatePopulation()
     {
-        populationLabel.Text = stage.GameWorld.PlayerSpecies.Population.ToString(CultureInfo.InvariantCulture);
+        var playerPopulation = stage.GameWorld.PlayerSpecies.Population;
+
+        if (playerPopulation < 1000)
```
Comment (Kasterisk) [inline src/microbe_stage/MicrobeHUD.cs:812]: There's already a static helper method for the formatting: `StringUtils.FormatNumber`. I'd use it here since it also handles translations.

**Review by Kasterisk — CHANGES_REQUESTED** [review]

**Review by Kasterisk — APPROVED** [review]
Looks good, thanks for your contribution!

**Comment by hhyyrylainen** [comment]
@Pickles4Life we are in the process of getting a CLA in-place for Thrive in order to make it possible to have Thrive on Steam. Could you maybe sign the CLA? You can do that here: https://dev.revolutionarygamesstudio.com/cla
