### PR TITLE
Added listener for microbe sound effects and other fixes.

### LINKED ISSUE #837: Player taking damage sound doesn't play
The player taking damage sound does not play (or it plays so low volume that it's not audible).
Would be nice to alert the player with it.

### PR DESCRIPTION
**Pull request by Satharis**
Made the audio actually work by adding a listener to the player microbe, along with some other adjustments like supporting playing multiple sounds at once.
Closes #837

### CODE REVIEW

File: src/microbe_stage/Microbe.cs [hunk 1]
```diff
@@ -31,9 +31,10 @@ public class Microbe : RigidBody, ISpawned, IProcessable, IMicrobeAI
 
     private CompoundCloudSystem cloudSystem;
 
+    private List<AudioStreamPlayer3D> otherAudioPlayers = new List<AudioStreamPlayer3D>();
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:34]: I think this should be after the `// Child components` comment because this contains child components.

File: src/microbe_stage/Microbe.cs [hunk 2]
```diff
@@ -498,10 +513,10 @@ public void Damage(float amount, string source)
             return;
         }
 
-        if (source == "toxin")
+        if (source == "toxin" || source == "oxytoxy")
         {
             // Play the toxin sound
-            PlaySoundEffect("res://assets/sounds/soundeffects/microbe-toxin-damage.ogg");
+            PlaySoundEffect("res://assets/sounds/soundeffects/microbe-release-toxin.ogg");
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:519]: Why did you change the damage receive sound to be the toxin release sound?

File: src/microbe_stage/Microbe.cs [hunk 3]
```diff
@@ -518,9 +533,15 @@ public void Damage(float amount, string source)
         }
         else if (source == "chunk")
         {
+            PlaySoundEffect("res://assets/sounds/soundeffects/microbe-toxin-damage.ogg");
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:536]: There should be a todo comment here that, this should play an ice damage sound effect as that's where this damage comes from.

File: src/microbe_stage/Microbe.cs [hunk 4]
```diff
@@ -518,9 +533,15 @@ public void Damage(float amount, string source)
...
+
             // Divide damage by physical resistance
             amount /= Species.MembraneType.PhysicalResistance;
         }
+        else if (source == "atpDamage")
+        {
+            PlaySoundEffect("res://assets/sounds/soundeffects/microbe-release-toxin.ogg");
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:543]: This also shouldn't use the same sound as the toxin release.

File: src/microbe_stage/Microbe.cs [hunk 5]
```diff
@@ -753,8 +774,22 @@ public void PlaySoundEffect(string effect)
         // TODO: make these sound objects only be loaded once
         var sound = GD.Load<AudioStream>(effect);
 
-        otherAudio.Stream = sound;
-        otherAudio.Play();
+        // Find a player not in use or create a new one if none are available.
+        var player = otherAudioPlayers.Find(nextPlayer => !nextPlayer.Playing);
+
+        if (player == null)
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:780]: I really think there should be a hard limit like 10 to prevent bugs where a cell is playing 10000 sounds at once each frame.

File: src/microbe_stage/Microbe.cs [hunk 6]
```diff
@@ -998,6 +1044,10 @@ public override void _Process(float delta)
             totalMovement += queuedMovementForce;
 
             ApplyMovementImpulse(totalMovement, delta);
+
+            // Play movement sound if one isn't already playing.
+            if (!movementAudio.Playing)
+                movementAudio.Play();
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:1050]: It would be really nice to scale the movement sound level by the cell speed so that only the fastest cells play the sound at max volume. Though if it is too hard to do then this can be left as is and fixed in a future PR.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
In addition to the code comments I found a saving related bug:
- Go to the editor
- Make a quick safe
- Go to the stage, everything is still fine. Load the quick save
- Go to the stage, the listener on the player cell is now broken.

File: src/microbe_stage/Microbe.cs (hunk 1 above)
Comment (Satharis) [reply src/microbe_stage/Microbe.cs:34]: Funnily enough I actually moved it up there because I thought the opposite, that it's not actually attached as a child component so I thought it'd be better above.

Comment (hhyyrylainen) [reply src/microbe_stage/Microbe.cs:34]: Sound players don't work if they aren't a child component, and you call AddChild with them.

File: src/microbe_stage/Microbe.cs (hunk 5 above)
Comment (Satharis) [reply src/microbe_stage/Microbe.cs:780]: Problem with that is what do you do if you end up with that many? Just not play the sound if they're all busy? I could add a limit if you're that concerned about it.

Comment (hhyyrylainen) [reply src/microbe_stage/Microbe.cs:780]: I would just not play the sound. And I'd like to have a limit.
Many audio engines have an internal max limit for active sounds, and they just stop the quietest sound or not play new sounds if that limit is hit.
If you have 10 sound effects coming from a cell at once it will be chaotic enough already that the player won't notice if some sound isn't played.

File: src/microbe_stage/Microbe.cs (hunk 6 above)
Comment (Satharis) [reply src/microbe_stage/Microbe.cs:1050]: I was trying to set it up for that but the fact I couldn't get the local volume to change sorta made that a no go right now. I was gonna look into it again and try to fix that in a future PR, we might want new/different sounds for cell movement anyway, there's two other already but I didn't actually know what they were supposed to be used for. I looked into changing the playback rate instead of the volume too but godot doesn't really support that either.. you can only play with the pitch to sort of simulate it.

File: src/microbe_stage/Microbe.cs [hunk 7]
```diff
@@ -753,8 +773,26 @@ public void PlaySoundEffect(string effect)
...
 
-        otherAudio.Stream = sound;
-        otherAudio.Play();
+        // Find a player not in use or create a new one if none are available.
+        var player = otherAudioPlayers.Find(nextPlayer => !nextPlayer.Playing);
+
+        if (player == null)
+        {
+            // If we hit the player limit just return and ignore the sound.
+            if (otherAudioPlayers.Count >= 10)
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:782]: Could you put this constant in Constants, something like MAX_CONCURRENT_SOUNDS_PER_ENTITY

File: src/microbe_stage/Microbe.cs (hunk 3 above)
Comment (hhyyrylainen) [reply src/microbe_stage/Microbe.cs:535]: I don't see you adding a comment here?

File: src/microbe_stage/Microbe.cs [hunk 8]
```diff
@@ -518,9 +532,15 @@ public void Damage(float amount, string source)
...
         else if (source == "chunk")
         {
+            PlaySoundEffect("res://assets/sounds/soundeffects/microbe-toxin-damage.ogg");
+
             // Divide damage by physical resistance
             amount /= Species.MembraneType.PhysicalResistance;
         }
+        else if (source == "atpDamage")
+        {
+            PlaySoundEffect("res://assets/sounds/soundeffects/microbe-release-toxin.ogg");
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:542]: Also a TODO comment here for replacing this sound in the future should be added.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Just a couple tiny changes and this'll be done.

**Review by hhyyrylainen — APPROVED** [review]
I don't think I have any issues with this now.
I'll merge and open the follow-up issues.
