### PR TITLE
Fix engulfment of colony members

### LINKED ISSUE #3528: New engulfing mechanics need to handle detaching colony members properly
from @Kasterisk's explanation it seems that the engulfing won't properly let the colony know that a member was removed from it, which probably causes various bugs. We should fix this by just letting the colony know that a member got "killed" when something is engulfed from it.

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Colony members are now properly considered detached/removed if they're engulfed.

**Related Issues**

Fixes #3528

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/microbe_stage/Microbe.cs [hunk 1]
```diff
@@ -1023,6 +1023,9 @@ private Node GetStageAsParent()
         if (Colony == null)
             return GetParent();
 
+        if (Colony.Master.HostileEngulfer.Value != null)
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:1026]: When is this not null, doesn't the fact that when the engulfing starts the cell is removed from the colony mean that if the master is engulfed, it will just immediately break the colony? Or is this needed in this case. Could you clarify this with a comment in the source code?

**Comment by hhyyrylainen** [comment]
Code change looks good now. I haven't had time to playtest this, hoping someone else might have time...
