### PR TITLE
2912 fix iron food source

### LINKED ISSUE #2923: Auto-evo do not take into account marine snow density
As per the title, I can scavenge marine snow in the vents while its density is 0. 

This issue should be fixed by #2921 , but I open it here to keep track of it should it change.

### PR DESCRIPTION
**Pull request by Maxonovien**
**Brief Description of What This PR Does**

This PR adds iron chunks as a possible food source by generalizing marine snow food source. It also considers density in the computations, and so I changed a few constants for balance.

Note that I specifically target iron & glucose as compounds of interest in chunks, although this could be expanded to other energy source compounds. The reason to keep iron and glucose selection is that considering all compounds should not break chunk sources, as long as we generalize this to the whole system. Discussions on this part welcome.

**Related Issues**

Closes (at least partially) #2912 
Closes #2923 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
I'll try to finish my emergency changes tonight so that it could be merged first as I also touched the marine snow food source file.

**Comment by Maxonovien** [comment]
I tried to avoid making potential conflicts. We'll see if that works.

**Comment by hhyyrylainen** [comment]
I guess it might work. At least theoretically git can handle the rename and changes in other branch.

File: src/auto-evo/simulation/PopulationSimulation.cs [hunk 1]
```diff
@@ -157,7 +157,9 @@ private static List<Species> CopyInitialPopulationsToResults(SimulationConfigura
                 new CompoundFoodSource(patch, Glucose),
                 new CompoundFoodSource(patch, HydrogenSulfide),
                 new CompoundFoodSource(patch, Iron),
```
Comment (adQuid) [inline src/auto-evo/simulation/PopulationSimulation.cs:159]: This shouldn't do anything in the current state of the game, but I like that you kept it in. +1 for versitility!

File: src/auto-evo/simulation/food_source/ChunkFoodSource.cs [hunk 2]
```diff
@@ -38,11 +46,24 @@ public override float FitnessScore(Species species, SimulationCache simulationCa
 
         score /= energyBalance.FinalBalanceStationary;
 
+        var ponderedEnergyGenerationScore = energyCompounds.Sum(
+            c => EnergyGenerationScore(microbeSpecies, c.Key) * ProportionOfTotalEnergy(c.Key));
```
Comment (adQuid) [inline src/auto-evo/simulation/food_source/ChunkFoodSource.cs:50]: Is there a reason this needs to be proportional? I think you can save some division and seven code lines by just multiplying by amounts.

Remember that fitness scores are only used in ratio of other fitness scores of the same type, so scalar multipliers shouldn't matter.

File: src/auto-evo/simulation/food_source/ChunkFoodSource.cs [hunk 3]
```diff
@@ -38,11 +46,24 @@ public override float FitnessScore(Species species, SimulationCache simulationCa
...
     }
+
+    public float ProportionOfTotalEnergy(Compound compound)
+    {
+        if (energyCompounds.TryGetValue(compound, out var quantity))
+            return quantity / energyCompounds.Sum(c => c.Value);
+
+        return 0;
+    }
 }
```
Comment (adQuid) [inline src/auto-evo/simulation/food_source/ChunkFoodSource.cs:69]: nice

**Review by adQuid — COMMENTED** [review]
I think there's one unnecessary calculation in there, but the approach is right on point.

File: src/auto-evo/simulation/food_source/ChunkFoodSource.cs (hunk 2 above)
Comment (Maxonovien) [reply src/auto-evo/simulation/food_source/ChunkFoodSource.cs:50]: That was a point on which I wasn't sure, so I went the safe way. So we agree that I can add/multiply any constant to the score, that won't matter, right?

**Review by adQuid — APPROVED** [review]

**Comment by hhyyrylainen** [comment]
And there we go, this now has a conflict...

File: src/auto-evo/simulation/food_source/ChunkFoodSource.cs [hunk 4]
```diff
@@ -38,6 +46,13 @@ public override float FitnessScore(Species species, SimulationCache simulationCa
 
         score /= energyBalance.FinalBalanceStationary;
 
+        // We ponder the score for each compound by its amount, leading to pondering in proportion of total quantity,
+        // with a constant factor that will be eliminated when making ratios of scores for this niche.
+        var ponderedEnergyGenerationScore = energyCompounds.Sum(
```
Comment (hhyyrylainen) [inline src/auto-evo/simulation/food_source/ChunkFoodSource.cs:51]: I think this doesn't need a separate variable. Also this is part of the *base* score, so to me this multiplying is pretty weird here. Instead I'd move this to line 39 and make this an addition.

Comment (Maxonovien) [reply src/auto-evo/simulation/food_source/ChunkFoodSource.cs:51]: It is not part of the base score, it *is* the base score. All the rest are multiplicative factors to this base.

Comment (hhyyrylainen) [reply src/auto-evo/simulation/food_source/ChunkFoodSource.cs:51]: Yes, but you *multiply* it into the score *after* all the other stuff has been already calculated, at least github diff shows it to me like that.

Comment (hhyyrylainen) [reply src/auto-evo/simulation/food_source/ChunkFoodSource.cs:51]: Kuvakaappaus - 2021-12-09 14-08-29

Comment (Maxonovien) [reply src/auto-evo/simulation/food_source/ChunkFoodSource.cs:51]: I've just been reordering this, because I agree this may be misleading. But I *think* I saw it in another food source. Not sure though.

Comment (hhyyrylainen) [reply src/auto-evo/simulation/food_source/ChunkFoodSource.cs]: Still you are *multiplying* the *final* score after all the adjustments, with what should be the *base* number and the adjustments should apply on top of that number.

Comment (Maxonovien) [reply src/auto-evo/simulation/food_source/ChunkFoodSource.cs]: As I wrote just above, I already reordered that part of the logic.

**Comment by hhyyrylainen** [comment]
I'll try to finish this PR now.

**Comment by hhyyrylainen** [comment]
Marine snow and small iron chunks are now pretty ridiculously nerfed:

**Comment by hhyyrylainen** [comment]
Looks like there's translation conflicts, Maybe I'll merge this anyway, and someone can in the meantime try to come up with better numbers to use. Remember that there's a release planned for *tomorrow*.

**Review by hhyyrylainen — APPROVED** [review]
The code is now fine to me, but big iron being OP and marine snow being nerfed (the total energy should at least be closer to 5000 for the marine snow) are problems, but I think I'll merge this soon anyway and wait for a follow up PR after that.
