### PR TITLE
fixed moving to any patch in freebuild

### LINKED ISSUE #2115: Make patch move in freebuild allow moving to any reachable patch
So instead of requiring the player to select each subsequent patch in a path and click the move button, in freebuild any patch (from the current patch where there is a viable path) can be moved to.

### PR DESCRIPTION
**Pull request by Jonathon594**
**Brief Description of What This PR Does**

Added recursive method to find all connected patches, if the target patch is in the list, allows travel.

**Related Issues**

fixes #2115 

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by Jonathon594** [comment]
Is this a good way to do this? I've used this recursive approach before and it works fairly efficiently in Java. I've tested it, it works fine as far as I can tell. I don't think there's any possible way this could mess with saving/loading.

**Comment by hhyyrylainen** [comment]
This could be rewritten as an enumerator with "yield return" (that approach is used in the microbe spawner) so that a list object doesn't need to be built. Instead the LINQ contains can directly just iterate the sequence once without having to make a concrete list.

**Comment by Jonathon594** [comment]
Yeah I was loosing my mind look at IEnumerable going "but how do I keep track of what I've already put.." I converted it to HashSet, does that look better? Personally I don't know all the differences of the List/Set types yet. Probably should look into that.

File: src/microbe_stage/Patch.cs [hunk 1]
```diff
@@ -79,6 +79,35 @@ public bool AddNeighbour(Patch patch)
         return Adjacent.Add(patch);
     }
 
+    /// <summary>
+    /// Checks all neighbors recursively to find all connected patch nodes
+    /// </summary>
```
Comment (Maxonovien) [inline src/microbe_stage/Patch.cs:84]:
```suggestion
    /// <summary>
    ///   Checks all neighbors recursively to find all connected patch nodes
    /// </summary>
```

File: src/microbe_stage/Patch.cs [hunk 2]
```diff
@@ -79,6 +79,35 @@ public bool AddNeighbour(Patch patch)
...
+    {
+        HashSet<Patch> resultSet = new HashSet<Patch>();
+        CollectNeighbors(this, ref resultSet);
+
+        return resultSet;
+    }
+
+    /// <summary>
+    /// Adds all neighbors recursively to the referenced <see cref="HashSet{T}"/>
+    /// </summary>
```
Comment (Maxonovien) [inline src/microbe_stage/Patch.cs:96]:
```suggestion
    /// <summary>
    ///   Adds all neighbors recursively to the referenced <see cref="HashSet{T}"/>
    /// </summary>
```

**Review by Maxonovien — CHANGES_REQUESTED** [review]
This seems like a nice implementation of a DFS. Maybe it could be worth it to mention that we use this kind of recursive search somewhere in the functions documentation?

The request for changes is only about XML formatting, otherwise I'm very happy with the changes brought to the code.

**Comment by Jonathon594** [comment]
Done, and done.

**Review by Maxonovien — APPROVED** [review]

File: src/microbe_stage/Patch.cs [hunk 3]
```diff
@@ -79,6 +79,35 @@ public bool AddNeighbour(Patch patch)
...
+
+        return resultSet;
+    }
+
+    /// <summary>
+    ///   Adds all neighbors recursively to the referenced <see cref="HashSet{T}"/>
+    /// </summary>
+    /// <param name="patch">The <see cref="Patch"/> to start from</param>
+    /// <param name="set">The <see cref="HashSet{T}"/> to add to</param>
+    public void CollectNeighbors(Patch patch, ref HashSet<Patch> set)
```
Comment (hhyyrylainen) [inline src/microbe_stage/Patch.cs:99]:
```suggestion
    public void CollectNeighbours(Patch patch, HashSet<Patch> neighbours)
```

Besides that suggestion: I have a question, why does this take in a patch? This is a non-static method, why not use `this.Adjacent`. Why is it like this?

File: src/microbe_stage/Patch.cs [hunk 4]
```diff
@@ -79,6 +79,35 @@ public bool AddNeighbour(Patch patch)
...
+    {
+        foreach (var neighbour in patch.Adjacent)
+        {
+            if (!set.Contains(neighbour))
```
Comment (hhyyrylainen) [inline src/microbe_stage/Patch.cs:103]: HashSet.Add already returns a boolean indicating whether the element was added, we can save one method call like that (so instead of first contains and then add, just directly add and check the return value).
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1.add?view=net-5.0

File: src/microbe_stage/editor/MicrobeEditor.cs [hunk 5]
```diff
@@ -1021,6 +1021,10 @@ public bool IsPatchMoveValid(Patch patch)
         if (patch == playerPatchOnEntry)
             return true;
 
+        // We are freebuilding so check if the target patch is connected by any means
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditor.cs:1024]:
```suggestion
        // If are freebuilding, check if the target patch is connected by any means, then it is allowed
```

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

File: src/microbe_stage/Patch.cs (hunk 3 above)
Comment (Jonathon594) [reply src/microbe_stage/Patch.cs:99]: Because this method calls itself on line 106 with the neighbour passed in as what to collect from. I probably should have made it static?

Comment (hhyyrylainen) [reply src/microbe_stage/Patch.cs]: Yes, that would make sense.

Comment (Jonathon594) [reply src/microbe_stage/Patch.cs]: I've converted it to static and moved it above all non static members. Along with all the other requested changes. It should look good now.

**Review by hhyyrylainen — APPROVED** [review]
lgtm
