### PR TITLE
Fix current light level in editor not working correctly

### LINKED ISSUE #4286: Current light level button doesn't always work correctly after a patch change
I was in the editor having entered it in the ice shelf. I moved to an estuary patch and the light level was correct. Then I clicked the night button and back to the current light level button, which for some reason made the light level stay as the night and all the light values were shown incorrectly on the patch map. When I exited to the stage the light jumped to 84% (as that's what it was supposed to be). Going back to the editor everything was fine then.

### PR DESCRIPTION
**Pull request by Kasterisk**
Fixing slightly flawed approach in #4276.

Moved `DayNightCycle` instance out of `CreatureStageBase` higher to `GameWorld` so that it's accessible to more logic that needs it. Also refactored some TODO comments regarding updating average sunlight in patches.

Editor light level is now changed to be a daylight fraction instead. This is to make it easier to apply the correct editor-specific time of day to all patches in the patch map.

DRAFT because old save needs to be loaded correctly.

**Brief Description of What This PR Does**

Fixes #4286.

**Related Issues**

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
As day/night cycle is an experimental feature, I'm fine with the save loading just working in a somewhat sensible way. It's not a big deal if it loses the current info.

File: src/general/GameWorld.cs [hunk 1]
```diff
@@ -92,6 +93,13 @@ public GameWorld(WorldGenerationSettings settings, Species? startingSpecies = nu
         GenerationHistory.Add(0, new GenerationRecord(
             0,
             new Dictionary<uint, SpeciesRecordLite> { { PlayerSpecies.ID, initialSpeciesRecord } }));
+
+        if (WorldSettings.DayNightCycleEnabled)
+        {
+            // Make sure average light levels are computed already
+            foreach (var patch in Map.Patches)
+                patch.Value.UpdateAverageSunlight(LightCycle);
```
Comment (hhyyrylainen) [inline src/general/GameWorld.cs:101]: I think this should be made into a general method in the patch map just for that extra bit of clarity and guarantee against accidentally modifying just one copy of this code (I saw this same kind of looking pattern in the editor).

File: src/general/base_stage/StageBase.cs [hunk 2]
```diff
@@ -107,6 +113,15 @@ public override void _Process(float delta)
 
             wantsToSave = false;
         }
+
+        GameWorld.LightCycle.Process(delta);
```
Comment (hhyyrylainen) [inline src/general/base_stage/StageBase.cs:117]: I think it would make sense to add a `GameWorld.Process` method that takes care of processing everything in the world.

File: src/general/base_stage/StageBase.cs [hunk 3]
```diff
@@ -38,6 +38,12 @@ public abstract class StageBase : NodeWithInput, IStageBase, IGodotEarlyNodeReso
 
     private bool transitionFinished;
 
+    /// <summary>
+    ///   Used to control how often light level is updated by the day/night cycle.
```
Comment (hhyyrylainen) [inline src/general/base_stage/StageBase.cs:42]:
```suggestion
    ///   Used to control how often updated light level data is read from the day/night cycle.
```
I think wording it like this will be more accurate to what is actually going on.

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 4]
```diff
@@ -2204,28 +2189,28 @@ private void ApplyLightLevelOption()
...
-                Editor.LightLevel = Editor.CurrentPatch.Biome.MinimumCompounds[sunlight].Ambient;
+                Editor.DayLightFraction = 0;
                 break;
             }
 
             case LightLevelOption.Average:
             {
                 averageLightButton.Pressed = true;
-                Editor.LightLevel = Editor.CurrentPatch.Biome.AverageCompounds[sunlight].Ambient;
+                Editor.DayLightFraction = Editor.CurrentGame.GameWorld.LightCycle.AverageSunlight;
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:2206]: Is this always correct? Can the average sunlight fraction not vary by patch?

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 5]
```diff
@@ -1077,6 +1071,8 @@ public override void OnLightLevelChanged(float lightLevel)
         // is non-zero too.
         if (maxLightLevel > 0.0f && templateMaxLightLevel > 0.0f)
         {
+            var lightLevel = maxLightLevel * dayLightFraction;
+
             // Normalise by maximum light level in the patch
             camera!.LightLevel = lightLevel / maxLightLevel;
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:1077]: Doesn't the math cancel out here.

You have first `ligthLevel = maxLightLevel * dayLightFraction` and then substituting that here gives:

```
lightLevel / maxLightLevel
maxLightLevel * dayLightFraction / maxLightLevel
dayLightFraction
```

So shouldn't this line just be `camera!.LightLevel = dayLightFraction;`?

File: src/microbe_stage/MicrobeStage.cs [hunk 6]
```diff
@@ -712,31 +690,21 @@ protected override void UpdatePatchSettings(bool promptPatchNameChange = true)
...
+        if (GameWorld.Map.CurrentPatch == null)
+            return;
 
-    private void UpdateBackground()
-    {
-        Camera.SetBackground(SimulationParameters.Instance.GetBackground(
-            GameWorld.Map.CurrentPatch!.BiomeTemplate.Background));
-    }
+        patchManager.UpdatePatchBiome(GameWorld.Map.CurrentPatch);
+        patchManager.UpdateAllPatchLightLevels();
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeStage.cs:699]: Doesn't have to happen now, but could you add a TODO here that it would make more sense for the GameWorld to update its patch map data based on the light cycle in it. That'd be much clearer OOP design where not everything is messing with the internals of that object.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
I just tested and it seems like loading an earlier save works sensibly enough for me to not need to consider a save upgrade. I do have some code structure and clean up related comments, though.

File: src/microbe_stage/editor/CellEditorComponent.cs (hunk 4 above)
Comment (Kasterisk) [reply src/microbe_stage/editor/CellEditorComponent.cs:2206]: This one is universal, patches just multiply `AverageSunlight` by their maximum sunlight to get their patch-specific average sunlight.

File: src/microbe_stage/editor/CellEditorComponent.cs (hunk 5 above)
Comment (Kasterisk) [reply src/microbe_stage/editor/CellEditorComponent.cs:1077]: That's indeed right...

File: src/general/GameWorld.cs (hunk 1 above)
Comment (Kasterisk) [reply src/general/GameWorld.cs]: I put this in `GameWorld` to reduce unnecessary passing of `DayNightCycle` in methods.

File: src/microbe_stage/MicrobeStage.cs (hunk 6 above)
Comment (Kasterisk) [reply src/microbe_stage/MicrobeStage.cs]: Added.

File: src/general/base_stage/StageBase.cs [hunk 7]
```diff
@@ -38,6 +38,11 @@ public abstract class StageBase : NodeWithInput, IStageBase, IGodotEarlyNodeReso
 
     private bool transitionFinished;
 
+    /// <summary>
+    ///   Used to control how often updated light level data is read from the day/night cycle.
+    /// </summary>
+    private float elapsedSinceLightLevelUpdate;
```
Comment (Kasterisk) [inline src/general/base_stage/StageBase.cs:44]: I didn't make this savable as I think the value is just too insignificant to be saved, plus I think we've been making similar fields as not for saving lately.

File: src/microbe_stage/editor/CellEditorComponent.cs (hunk 4 above)
Comment (hhyyrylainen) [reply src/microbe_stage/editor/CellEditorComponent.cs:2203]: It's universal *now* I was just wondering if it might not be the case in the future, though I guess it is kind of pointless to think about now if there's no ideas how this might potentially change in the future...

File: src/general/base_stage/StageBase.cs (hunk 7 above)
Comment (hhyyrylainen) [reply src/general/base_stage/StageBase.cs:44]: Yeah, this is so inconsequential that I wouldn't save this. Though maybe this should default to 1 to ensure that an immediate update happens?

Comment (hhyyrylainen) [reply src/general/base_stage/StageBase.cs:44]: If you don't mind, I'll commit this change and approve this PR now. I just playtested and I think this solved all the issues I had.

Comment (Kasterisk) [reply src/general/base_stage/StageBase.cs:44]: Sure.

**Review by hhyyrylainen — APPROVED** [review]
Seems to work now with a quick test (I didn't remember the exact steps I did before to get the issue to appear). And I added that one last bit of code change to ensure when loading a game the light data is immediately applied.
