### PR TITLE
Balance chunks food source

### LINKED ISSUE #2912: Investigate and fix iron compound food source
**Describe the bug**
I'm pretty sure the compound food source for iron is broken.

It is defined here
(https://github.com/Revolutionary-Games/Thrive/blob/master/src/auto-evo/simulation/PopulationSimulation.cs#L159)

Like all compound food sources, it takes dissolved compounds.
https://github.com/Revolutionary-Games/Thrive/blob/master/src/auto-evo/simulation/food_source/CompoundFoodSource.cs#L15

But iron is never found dissolved, it's only found in chunks.
https://github.com/Revolutionary-Games/Thrive/blob/master/simulation_parameters/microbe_stage/biomes.json#L101

Either the compound food source needs to be modified to handle this, a new food source class should be made, or I'm totally wrong and there's some other reason the auto-evo hates iron eaters. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a patch with iron but no glucose (modifying the biomes file will speed this up)
2. Be a pure iron-eater
3. Observe your auto-evo prediction

**Expected behaviour**
A non-zero population prediction

**Screenshots**

**System info (please complete the following information):**
- OS: [e.g. Windows 10]
- Graphics card (you can find this in the game logs) [e.g. OpenGL ES 3.0 Renderer:
    GeForce GTX 1080 Ti/PCIe/SSE2]
- Thrive version [e.g. 0.4.0.2]

**Logs**

Please use a text hosting service (for example https://pastebin.com/) to submit your logs.
You can copy the launcher output or the contents of the following files: `log.txt` and mono
log file. You can find these log files by reading the game log to see their location.
For example:
```
Mono: Logfile is: /home/hhyyrylainen/.local/share/godot/mono/mono_logs/2020_07_21 23.10.26 (265121).txt
Game logs are written to: /home/hhyyrylainen/.local/share/Thrive/logs latest log is 'log.txt'
```

**Additional context**

### PR DESCRIPTION
**Pull request by Maxonovien**
**Brief Description of What This PR Does**

This PR adds an exponent to limit the importance of big chunks compared to small, and favor high-density chunks to large ones.

**Related Issues**

Closes #2912 .

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: simulation_parameters/Constants.cs [hunk 1]
```diff
@@ -445,7 +445,8 @@ public static class Constants
     public const float AUTO_EVO_PREDATION_ENERGY_MULTIPLIER = 0.4f;
     public const float AUTO_EVO_SUNLIGHT_ENERGY_AMOUNT = 100000;
     public const float AUTO_EVO_COMPOUND_ENERGY_AMOUNT = 1200;
-    public const float AUTO_EVO_CHUNK_ENERGY_AMOUNT = 5000;
+    public const float AUTO_EVO_CHUNK_ENERGY_AMOUNT = 90000000;
+    public const double AUTO_EVO_CHUNK_AMOUNT_NERF = 0.01;
```
Comment (hhyyrylainen) [inline simulation_parameters/Constants.cs:449]: why is this a double? Mathf.Pow probably exists for floating point power math.

**Review by hhyyrylainen — APPROVED** [review]
Code seems reasonable.
