### PR TITLE
Fix double refunding of organelle upgrade MP

### LINKED ISSUE #5524: Reverting an organelle upgrade and then selecting it again incorrectly gives back the used MP (infinite MP glitch)
Steps to reproduce:
- Start a normal game
- Cheat to the editor
- Use the cheat to unlock all organelles
- Place a slime jet
- Modify it into a mucocyst
- Hit ok
- Modify it again back to a normal state
- Hit ok
- And now when it is modified again it costs 0 MP to select the mucocyst upgrade again.
- Hit ok
- Now finally modify one last time to switch back to the default state of the organelle which now gives more MP than before and these steps can be repeated for an infinite MP exploit

This bug is probably caused by the GUI somehow mistaking the organelle upgrade state, allowing freely to select an upgrade when it should still cost the normal amount as it was reversed by a later action. Could be a bug in the actions cancelling out system incorrectly calculating things as cancelling out.

If this is fixed, this might also fix: https://github.com/Revolutionary-Games/Thrive/issues/5518

### PR DESCRIPTION
**Pull request by 0HyperCube**
**Brief Description of What This PR Does**

When changing the organelle upgrade repeatedly in the same editor cycle, MP would be refunded twice (as detailed in #5524). This is because the cost of an upgrade also includes the negated cost of the current upgrade, meanwhile the editor refunds MP where `ActionInterferenceMode.Combinable` is returned as the interference mode.

I initially fixed this by not combining the actions. However I have now changed the implementation to avoid the negated cost.

**Related Issues**
Closes #5524

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by dligr — APPROVED** [review]
This PR fixes the issue based on my testing; the solution makes sense to me too.

File: src/microbe_stage/editor/action_data/OrganelleUpgradeActionData.cs [hunk 1]
```diff
@@ -41,13 +41,8 @@ protected override int CalculateCostInternal()
...
     {
-        if (other is OrganelleUpgradeActionData upgradeActionData)
-        {
-            if (ReferenceEquals(UpgradedOrganelle, upgradeActionData.UpgradedOrganelle))
-                return ActionInterferenceMode.Combinable;
-        }
-
-        // The replacing action is in the remove organelle action
+        // Organelle upgrades can never combine since the old choice will have already been refunded.
+        // https://github.com/Revolutionary-Games/Thrive/issues/5524
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/action_data/OrganelleUpgradeActionData.cs:45]: I'm a bit hesitant on this as if you have an upgrade like the chemoreceptor and it is made to cost MP, then wouldn't the combine be required for MP to work correctly?

For example:
- Player edits detection distance from 200 to 500 and it costs 3 MP
- The player then edits the distance from 500 to 200 again costing 3 MP
- The combined action should then be the change being from 200 to 200 and not costing any MP, but if the combining system is told that upgrade changes cannot combine, then this would cost 6 MP.

Comment (hhyyrylainen) [reply src/microbe_stage/editor/action_data/OrganelleUpgradeActionData.cs:45]: Just to clarify that is not the case yet, but is a desired feature: https://github.com/Revolutionary-Games/Thrive/issues/4093 also relevant for the flagellum: https://github.com/Revolutionary-Games/Thrive/issues/5536

Comment (dligr) [reply src/microbe_stage/editor/action_data/OrganelleUpgradeActionData.cs:45]: I think that the original problem comes down to the fact that removing upgrades refunds MP, which causes weirdness with combined upgrades.
```C#
cost += newUpgrades.Sum(u => u.MPCost);
cost -= removedUpgrades.Sum(u => u.MPCost);
```
Since #4095 is an issue, I believe that this refunding wasn't a desired behavior in the first place, as refunding MP by reverting upgrades in the same editor cycle should be done by action combining.

Comment (hhyyrylainen) [reply src/microbe_stage/editor/action_data/OrganelleUpgradeActionData.cs:45]: > reverting upgrades in the same editor cycle should be done by action combining.

That's probably true and a mistake I didn't realize at the time when I was writing the general upgrades system for the editor.

Comment (0HyperCube) [reply src/microbe_stage/editor/action_data/OrganelleUpgradeActionData.cs]: I have changed it so that it won't refund MP from previous editor sessions (since I assume that is what you wanted?).

When I previously asked about the desired behaviour, nobody gave any particular opinion either way.

Comment (dligr) [reply src/microbe_stage/editor/action_data/OrganelleUpgradeActionData.cs]: I meant more an approach like this:
```C#
cost += newUpgrades.Sum(u => u.MPCost);
cost += removedUpgrades.Sum(u => u.MPCost);
```
So that any changes to upgrades cost MP. It shouldn't be possible to refund actions from previous editor sessions too.
I don't think there will be any problems with reverting (=refunding) upgrades within the same session because of action combining.

**Review by hhyyrylainen — APPROVED** [review]
This fixes the infinite MP exploit (as long as I didn't accidentally mess up the steps). So I think this is good to merge now. I added a further TODO about a related issue that this doesn't fix (and I kept the deleted code as commented out for future reference).

File: src/microbe_stage/editor/action_data/OrganelleUpgradeActionData.cs (hunk 1 above)
Comment (hhyyrylainen) [reply src/microbe_stage/editor/action_data/OrganelleUpgradeActionData.cs]: I merged this for now, but I edited the issue https://github.com/Revolutionary-Games/Thrive/issues/4095 to be about making the upgrades cost MP to also remove.
