### PR TITLE
Fix evolutionary tree in fossilisation freebuild (One-line change)

### LINKED ISSUE #4027: Evolutionary tree fails to build in freebuild when playing with fossilisation

### PR DESCRIPTION
**Pull request by 84634E1A607A**
**Brief Description of What This PR Does**

Fixes #4027 

This PR does some stuff...

**Related Issues**

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/general/GameWorld.cs [hunk 1]
```diff
@@ -63,6 +63,7 @@ public GameWorld(WorldGenerationSettings settings, Species? startingSpecies = nu
         else
         {
             startingSpecies.BecomePlayerSpecies();
+            startingSpecies.Generation = 1;
```
Comment (hhyyrylainen) [inline src/general/GameWorld.cs:66]: Could you add a comment here that the generation needs to be forced to be 1 in case it is different in the fossil file?

**Review by hhyyrylainen — APPROVED** [review]
This code change makes sense to me now and looks good. I guess I'll merge this today even if no one has time to test this.

**Comment by hhyyrylainen** [comment]
I ended up testing this myself and it seems to work correctly, at least starting a 4th generation species in freebuild through the Thriveopedia has the evolutionary tree working.
