### PR TITLE
Fix patch map lag

### LINKED ISSUE #5975: Improve patch map rendering performance with large maps
With the new option to have larger worlds, the map performance on my computer falls to 30 FPS when zooming out. So that isn't exactly great so I think the performance needs some improving.

Interestingly I found out that if I click on something on the map (so that connections are redrawn) that increases the performance a ton, so that's pretty weird.

Image

After clicking:
Image

### PR DESCRIPTION
**Pull request by Patryk26g**
**Brief Description of What This PR Does**

Closes #5975

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by HyperbolicHadron** [comment]
This appears to have completely fixed the issue when tested on my main computer

File: src/microbe_stage/editor/PatchMapDrawer.cs [hunk 1]
```diff
@@ -188,14 +188,14 @@ public override void _Draw()
         if (connections.Count == 0)
         {
             // Clear existing connection lines
-            lineContainer.FreeChildren();
+            lineContainer.QueueFreeChildren();
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/PatchMapDrawer.cs:191]: Does this need to detach the nodes here? That I think costs more performance than passing in false here.

**Review by hhyyrylainen — APPROVED** [review]
This improves the performance quite a bit. I tested the normal map view and also the patch extinction view and couldn't see any bugs that these changes would have introduced.

File: src/microbe_stage/editor/PatchMapDrawer.cs (hunk 1 above)
Comment (Patryk26g) [reply src/microbe_stage/editor/PatchMapDrawer.cs:191]: I forgot to add `false` :sob:

Comment (hhyyrylainen) [reply src/microbe_stage/editor/PatchMapDrawer.cs]: Seems like a simple enough change so I'll merge this without playtesting again as if anything the performance should be even better with this.
