### PR TITLE
Fix mucocyst for colonies

### LINKED ISSUE #5525: Fix mucocyst activation for colony members
The state setting is done, but the MucocystSystem is marked as not running on attached entities. So that attribute needs to be removed and then made sure that that doesn't break anything. Probably should add a check that the mucocyst-using cell is not engulfed currently as that might be what the attached entity check is for originally.

Also the sound could be made to play only for the colony lead cell if it is too loud.

### PR DESCRIPTION
**Pull request by dligr**
**Brief Description of What This PR Does**

Fixes mucocyst only activating on the lead cell of the colony

**Related Issues**

Closes #5525

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/microbe_stage/systems/MucocystSystem.cs [hunk 1]
```diff
@@ -37,6 +34,13 @@ protected override void Update(float delta, in Entity entity)
         if (control.MucocystEffectsApplied == wantsMucocyst && !control.MucocystEffectsApplied)
             return;
 
+        // Disable mucocyst if engulfed
+        if (entity.Get<Engulfable>().PhagocytosisStep != PhagocytosisPhase.None)
```
Comment (hhyyrylainen) [inline src/microbe_stage/systems/MucocystSystem.cs:38]: I think it would be better to put this code where other special state resetting when engulfed handling is done, because as written this system has to be modified to say that this only processes entities with Engulfable component (and just reads it).

Comment (dligr) [reply src/microbe_stage/systems/MucocystSystem.cs]: I have fixed it now. I'm not sure if this is the proper solution, as the special state resetting is technically already done in 'EngulfedHandlingSystem'. However, it runs after the mucocyst system, so mucocyst is deactivated with a slight delay, causing a flicker.
That could probably be fixed with a `[RunsAfter()]` attribute, but it didn't seem to help.

**Review by hhyyrylainen — APPROVED** [review]
I think this change is now good. I checked in the engulfed system and the way it disables engulf mode on the engulfed thing should work here as well. I trust that you playtested this enough so that I don't have to context switch from my current branch I'm working on to test this.

File: src/microbe_stage/systems/MucocystSystem.cs (hunk 1 above)
Comment (hhyyrylainen) [reply src/microbe_stage/systems/MucocystSystem.cs]: I assume the check to not allow entering mucocyst state when engulfed in the input handling should take care of this.
