### PR TITLE
Rotation after unbind

### LINKED ISSUE #2503: Stop unbound colony members from snapping back to it's original rotation
**Describe the bug**

After unbinding a colony member the unbound cell instantly turns to the rotation it had before entering the colony. After a small amount of time the AI kicks in and the microbe turns into another direction.

**To Reproduce**
1. Bind with another microbe. Keep note of the rotation of it.
2. Rotate a bit
3. Unbind

**Expected behavior**
The microbe should not turn towards it's original rotation. It should not rotate at all until the AI kicks in.

### PR DESCRIPTION
**Pull request by Kemikal1**
**Brief Description of What This PR Does**

Hopefully will fix the annoying colony rotations after unbind.

**Related Issues**

hopefully Fixes #2503
 
**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by RacerBG** [comment]
I'm interested in this fix. Tell me when it's ready for review.

**Comment by Kemikal1** [comment]
Maybe even tomorrow, ill see, took me long enough to figure that the microbe doesnt really care about the transform but about the look up point...ugh

**Comment by hhyyrylainen** [comment]
Well Microbe._Process does always reset the rotation (or was it physics process for rotation?) to point towards the look at point.

**Comment by Kemikal1** [comment]
Its the physiscs process. But i forgot about that, so i spent the day figuring it out, xD

**Comment by Kemikal1** [comment]
What happened to this pull request, why did it change fiels from other pull requests? Im confused.

**Comment by hhyyrylainen** [comment]
You used the wrong base branch?
You should be able to rebase your changes on master / use interactive rebase to skip the commits that shouldn't be in this branch.

**Comment by Kemikal1** [comment]
its upstream master, i dont get it why it doesnt work,

**Comment by Kemikal1** [comment]
@RacerBG 
Ready for you when you are

**Comment by Kemikal1** [comment]
By the way, you can disable AI with cheats to make it easier to test this, that took me a while to figure.

**Review by RacerBG — APPROVED** [review]
Nothing to comment here, everything which this PR is intending to do works as expected. Very good work. I would suggest someone to check to code just in case but testing wise everything is fine.

File: src/microbe_stage/MicrobeColony.cs [hunk 1]
```diff
@@ -71,6 +71,24 @@ public void RemoveFromColony(Microbe microbe)
         if (State == Microbe.MicrobeState.Unbinding)
             State = Microbe.MicrobeState.Normal;
 
+        var rotation = microbe.RotationInsideColony();
+        var offset = microbe.GetOffsetRelativeToMaster();
+
+        // Apply the rotation
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeColony.cs:77]: Isn't this where the "magic" of this PR happens. I think this comment needs to be explained more in detail *or* this whole if contents should be extracted as a named function to give this code the proper "label" to explain why it exists.

File: src/microbe_stage/MicrobeColony.cs [hunk 2]
```diff
@@ -71,6 +71,24 @@ public void RemoveFromColony(Microbe microbe)
...
+        if (microbe != Master)
+        {
+            // For some reason the first cell needs to be rotated by the colony master rotation
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeColony.cs:80]: Pretty strange, but okay

File: src/microbe_stage/MicrobeColony.cs [hunk 3]
```diff
@@ -71,6 +71,24 @@ public void RemoveFromColony(Microbe microbe)
...
+            if (microbe.ColonyParent == Master)
+                rotation *= new Quat(Master.Transform.basis);
+
+            // Normalize and apply the rotation
+            rotation = rotation.Normalized();
+            microbe.LookAtPoint = rotation.Xform(offset);
+
+            // Convert the vector to the lookupPoint true position
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeColony.cs:88]: Typo in LookAtPoint?

File: src/microbe_stage/MicrobeColony.cs [hunk 4]
```diff
@@ -71,6 +71,24 @@ public void RemoveFromColony(Microbe microbe)
...
+        // Apply the rotation
+        if (microbe != Master)
+        {
+            // For some reason the first cell needs to be rotated by the colony master rotation
+            if (microbe.ColonyParent == Master)
+                rotation *= new Quat(Master.Transform.basis);
+
+            // Normalize and apply the rotation
+            rotation = rotation.Normalized();
+            microbe.LookAtPoint = rotation.Xform(offset);
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeColony.cs:86]: Why is offset used here? Wouldn't a vector of just 1, 0, 0 or something similar work?

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Looks mostly fine to me, perhaps @FuJa0815 could do a further analysis being a colony expert.

File: src/microbe_stage/MicrobeColony.cs (hunk 4 above)
Comment (Kemikal1) [reply src/microbe_stage/MicrobeColony.cs:86]: The cell might be bigger then that vector and so it could point in the wrong way, if we use the distance between it and the master we know for sure that the position will be outside the cell.

Comment (hhyyrylainen) [reply src/microbe_stage/MicrobeColony.cs:86]: The look at point *doesn't* need to be outside the cell, the rotation direction is calculated from the vector (look at position - cell center position). So it doesn't matter as long as the point is not *exactly* at the cell center. In fact adding the position on the colony *could* accidentally make the point match exactly the world position the microbe is detached at.

**Comment by Kemikal1** [comment]
Anyone who wants a go at it be my guest, i used a better fix this time. |
After further testing my previous fix didnt work for  chains longer then 2.

**Review by RacerBG — APPROVED** [review]

File: src/microbe_stage/Microbe.Contact.cs [hunk 5]
```diff
@@ -568,6 +568,22 @@ public void UnbindAll()
         Colony?.RemoveFromColony(this);
     }
 
+    /// <summary>
+    ///   Updates the microbes LookAtPoint
+    /// </summary>
+    internal void UpdateLookAtPoint()
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.Contact.cs:574]: This needs a better name, one that explicitly says this creates a new look at point based on the rotation this cell has in a colony.

File: src/microbe_stage/Microbe.Contact.cs [hunk 6]
```diff
@@ -662,7 +678,6 @@ private void OnIGotAddedToColony()
 
         Rotation = newTransform.Rotation;
         Translation = newTransform.Translation;
-
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.Contact.cs:665]: Unnecessarily removed blank line

**Review by hhyyrylainen — APPROVED** [review]
Code looks fine. I assume this works as per the already done gameplay testing.
