### PR TITLE
Tweaked UI elements to make it work better with translations.

### LINKED ISSUE #1953: Fix Environment Panel Sizing for Localization
image

### LINKED ISSUE #1981: Make the top right panel in cell editor scroll better
figure out a better way to have a scroll bar on the top right panel in the microbe editor, after adding the compound balance there. For now I just basically added a min size to the scroll container that has the compounds list with the balance numbers.

Also sometimes the top right panel size doesn't shrink correctly until placing one more organelle.

### LINKED ISSUE #1997: Enable word wrap for patch depth info label
should solve:
img

### LINKED ISSUE #1998: Make editor confirm button expand if text is wide
Some translations are too wide to fit the confirm button:
img

the button should have the anchor points changed so it expands to the left instead of offscreen.

### LINKED ISSUE #1999: Ensure that compound icons can't have wrong aspect ratio
CreateCompoundIcon should be changed so that the created texture rect can't have its aspect ratio changed.

wrong aspect

### LINKED ISSUE #2002: Add word wrapping to organelle selection buttons
currently the translations need explicit line breaks to ensure they fit next to each other nicely.
After this is done, explicit line breaks should be removed from the translations (as long as the words themselves aren't too long, if they are then explicit word breaks with hyphens should be left in).

### PR DESCRIPTION
**Pull request by Kasterisk**
Closes #2002 
Closes #1999 
Closes #1998 
Closes #1997 
Closes #1981 
Closes #1953

### CODE REVIEW

File: src/gui_common/GUICommon.cs [hunk 1]
```diff
@@ -103,11 +103,13 @@ public void ModulateFadeOut(Control control, float duration)
...
-        var element = new TextureRect();
-        element.Expand = true;
-        element.RectMinSize = new Vector2(sizeX, sizeY);
-
-        element.Texture = GetCompoundIcon(compoundName);
+        var element = new TextureRect
+        {
+            Expand = true,
+            RectMinSize = new Vector2(sizeX, sizeY),
+            SizeFlagsVertical = (int)Control.SizeFlags.ShrinkCenter,
```
Comment (hhyyrylainen) [inline src/gui_common/GUICommon.cs:110]: I think this doesn't work exactly right as I always see glucose icon having the bottom cutoff, and in weird aspect ratios other icons also get cutoff.
I think I saw a rect size flag for "shrink to fit center with aspect ratio kept" I think that should work the best (unless this is already that).

**Review by hhyyrylainen — COMMENTED** [review]
Everything except the icon sizing looks good, which actually seems to have already been an issue even before these changes.
If you don't want to fix it, I can accept this and open a separate issue, but tweaking the icon display all at once might be good to do now.

File: src/gui_common/GUICommon.cs (hunk 1 above)
Comment (Kasterisk) [reply src/gui_common/GUICommon.cs:110]: The icon getting cutoff seems like a separate issue that I'm unsure how to fix, it's probably a problem with the texture resolution or something, might worth checking out if that's the case. And yeah, setting the stretch mode to keep aspect should work perfectly, forgot it exists, I'll add that.

**Review by hhyyrylainen — APPROVED** [review]
