### PR TITLE
Fix variable compound cloud resolutions

### LINKED ISSUE #1161: Fix different compound cloud resolutions
and enable the option in the options menu to change it.

### PR DESCRIPTION
**Pull request by RyuDanuer**
**Brief Description of What This PR Does**

This fixes the compound cloud code paths that still assumed the default cloud resolution. The local bounds check now uses the actual simulation plane size, and the advection world-position cache now builds its offsets from the current plane chunk size instead of the default-size constant.

It also enables the existing cloud resolution option in the performance options menu, since the setting was already wired up but the button was disabled.

**Related Issues**

Closes #1161

**Testing**

Checked on my pc:

- `dotnet run --project Scripts -- check files --include src/microbe_stage/CompoundCloudPlane.cs src/gui_common/menus/OptionsMenu.tscn`
- `dotnet build Thrive.csproj --no-restore`
- `dotnet test test/code_tests/ThriveTest.csproj --no-restore --no-build`

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/microbe_stage/CompoundCloudPlane.cs [hunk 1]
```diff
@@ -894,10 +894,9 @@ protected override void Dispose(bool disposing)
     }
 
     [MethodImpl(MethodImplOptions.AggressiveInlining)]
-    private static int GetWorldShiftKey(int x0, int y0, int playerX, int playerY)
+    private static int GetWorldShiftKey(int xSquare, int ySquare, int playerX, int playerY)
     {
-        // This is safe as long as the values are max 8 bit long, otherwise they will collide
-        return x0 | y0 << 8 | playerX << 16 | playerY << 24;
+        return xSquare | ySquare << 2 | playerX << 4 | playerY << 6;
```
Comment (Patryk26g) [inline src/microbe_stage/CompoundCloudPlane.cs:900]: I think that this would need a comment explaining why this is safe (or when it isn't)

Comment (RyuDanuer) [reply src/microbe_stage/CompoundCloudPlane.cs:900]: Added that now. It's safe because all four packed values are only 0-2, so the two bits reserved for each value don't overlap unless those ranges change later.

Comment (hhyyrylainen) [reply src/microbe_stage/CompoundCloudPlane.cs:900]: Does that assumption still hold even with the higher resolution clouds?

File: src/gui_common/menus/OptionsMenu.tscn [hunk 2]
```diff
@@ -1691,7 +1691,6 @@ custom_minimum_size = Vector2(200, 25)
 layout_mode = 2
 size_flags_horizontal = 3
 size_flags_stretch_ratio = 2.0
-disabled = true
```
Comment (hhyyrylainen) [inline src/gui_common/menus/OptionsMenu.tscn:1694]: I think this option won't immediately apply in a continued save, right? So maybe we should have a tooltip or something warning that this only applies to newly started games. (or make this possible to change during the game).

Comment (RyuDanuer) [reply src/gui_common/menus/OptionsMenu.tscn:1694]: Added the existing `SETTING_ONLY_APPLIES_TO_NEW_GAMES` tooltip to both the cloud resolution label and dropdown in ab80645, so the option now warns that it only applies to newly started games.
