### PR TITLE
Fix glucose decay

### LINKED ISSUE #2035: Investigate whether glucose reduction actually works
it's starting to look like that the glucose reduction code doesn't actually work.
Here's a starting point for anyone looking into this:
https://github.com/Revolutionary-Games/Thrive/blob/33d5740bd33d9151c38553b629352e6b42eaa064/src/general/IWorldEffect.cs#L34

### PR DESCRIPTION
**Pull request by adQuid**
Fixes #2035 

  Glucose decay was, in fact, broken due to the quirky way C# handles dictionary modification. After a little playtesting I took the liberty to modify the algorithm to only lower glucose where there was life to be eating it up. Otherwise at the current 0.8 decay rate there's no chance to get to the mesopelagic with enough nutrients to survive and reach the sunlight zone, unless you're REALLY good. I also added a constant for a minimum glucose level, but set it to zero for now. I like the ticking timer this provides, but in a future change I could see folks wanting to take things in an easier direction.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Ah, so the dictionary access returns a copy of the float, and multiplying that just affects that temporary variable, but won't actually update the value in the dictionary?

File: simulation_parameters/Constants.cs [hunk 1]
```diff
@@ -396,6 +396,7 @@ public static class Constants
     public const float AUTO_EVO_COMPOUND_ENERGY_AMOUNT = 600;
 
     public const float GLUCOSE_REDUCTION_RATE = 0.8f;
+    public const float GLUCOSE_MIN = 0.00000f;
```
Comment (hhyyrylainen) [inline simulation_parameters/Constants.cs:399]:
```suggestion
    public const float GLUCOSE_MIN = 0.0f;
```

File: src/general/IWorldEffect.cs [hunk 2]
```diff
@@ -37,13 +38,24 @@ public void OnTimePassed(double elapsed, double totalTimePassed)
         {
             var patch = targetWorld.Map.Patches[key];
 
-            foreach (var compound in patch.Biome.Compounds.Keys)
+            // If there are microbes to be eating up the primordial soup, reduce the milk
+            if (patch.SpeciesInPatch.Keys.Count > 0)
```
Comment (hhyyrylainen) [inline src/general/IWorldEffect.cs:42]: According to some documentation dictionary.Count should already return the number of keys in it.

File: src/general/IWorldEffect.cs [hunk 3]
```diff
@@ -37,13 +38,24 @@ public void OnTimePassed(double elapsed, double totalTimePassed)
...
                 {
-                    var data = patch.Biome.Compounds[compound];
+                    if (compound.InternalName == "glucose")
+                    {
+                        glucose = compound;
+                    }
+                }
 
-                    data.Density *= Constants.GLUCOSE_REDUCTION_RATE;
+                if (glucose != null)
```
Comment (hhyyrylainen) [inline src/general/IWorldEffect.cs:54]: This whole part could be replaced with code like: `if(pathc.Biome.Compounds.TryToGetValue(glucose, out ...))`
if you add a around line 36 (so it isn't done again every loop iteration): `var glucose = SimulationParameters.Instance.GetCompound("glucose");`

File: src/general/IWorldEffect.cs [hunk 4]
```diff
@@ -37,13 +38,24 @@ public void OnTimePassed(double elapsed, double totalTimePassed)
...
+                {
+                    var toMod = patch.Biome.Compounds[glucose];
```
Comment (hhyyrylainen) [inline src/general/IWorldEffect.cs:56]: I think this intermediate variable is unnecessary, if this were to be kept the naming would need to be changed as it doesn't follow the style guide.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
The approach looks good. Some minor code cleanup comments.

File: src/general/IWorldEffect.cs [hunk 5]
```diff
@@ -33,18 +34,17 @@ public void OnRegisterToWorld()
 
     public void OnTimePassed(double elapsed, double totalTimePassed)
     {
+        var glucose = SimulationParameters.Instance.GetCompound("glucose");
```
Comment (hhyyrylainen) [inline src/general/IWorldEffect.cs:37]: I'd add a blank line after this to improve readability.

File: src/general/IWorldEffect.cs [hunk 6]
```diff
@@ -33,18 +34,17 @@ public void OnRegisterToWorld()
...
+            // If there are microbes to be eating up the primordial soup, reduce the milk
+            if (patch.SpeciesInPatch.Count > 0)
             {
-                if (compound.InternalName == "glucose")
-                {
-                    var data = patch.Biome.Compounds[compound];
-
-                    data.Density *= Constants.GLUCOSE_REDUCTION_RATE;
-                }
+                var glucoseValue = patch.Biome.Compounds[glucose];
```
Comment (hhyyrylainen) [inline src/general/IWorldEffect.cs:45]: I would use TryGetValue here just in case there might in the future be patches that don't contain the glucose compounds at all.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

File: src/general/IWorldEffect.cs [hunk 7]
```diff
@@ -33,17 +34,21 @@ public void OnRegisterToWorld()
...
         {
             var patch = targetWorld.Map.Patches[key];
 
-            foreach (var compound in patch.Biome.Compounds.Keys)
+            // If there are microbes to be eating up the primordial soup, reduce the milk
+            if (patch.SpeciesInPatch.Count > 0)
             {
-                if (compound.InternalName == "glucose")
+                EnvironmentalCompoundProperties glucoseValue;
+                if (patch.Biome.Compounds.TryGetValue(glucose, out glucoseValue))
```
Comment (hhyyrylainen) [inline src/general/IWorldEffect.cs:47]: the variable declaration can be inlined in the out statement

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Just one more tiny thing. I'll also ask people to gameplay test this now.

File: src/general/IWorldEffect.cs (hunk 7 above)
Comment (adQuid) [reply src/general/IWorldEffect.cs]: C# is weird.

**Review by hhyyrylainen — APPROVED** [review]
