### PR TITLE
Using correct marshalling hint in NativePhysicsBody.cs

### LINKED ISSUE #5676: Fix the root cause why `byte` has to be used instead of `bool` for one C# interop call to C++
for some reason a single method call for checking if body is detached gets the wrong result to C# when the extern definition has `bool` instead of `byte` in it. This is super bizarre. And very worrying if other function calls also have the same problem or not...

### PR DESCRIPTION
**Pull request by xfractalino**
**Brief Description of What This PR Does**

Issue #5676 was caused by incorrect marshalling of the bool type as a 4-byte integer. This PR forces the usage of a single byte for the bool return type.

As a general future reference, the `MarshalAs` attribute *should* be used anywhere the return value is bool in native calls.

**Related Issues**

Closes #5676 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR). This includes **gameplay** testing by the PR author.
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/engine/physics/NativePhysicsBody.cs [hunk 1]
```diff
@@ -212,7 +212,8 @@ internal static partial class NativeMethods
     // TODO: find out why this had to be converted to have return type "byte" instead of bool
     // BUG: https://github.com/Revolutionary-Games/Thrive/issues/5676
```
Comment (hhyyrylainen) [inline src/engine/physics/NativePhysicsBody.cs]: I think these comments should be removed as solved now.


Did you also check all other DllImport places to make sure any bool return values have the right attributes?

Comment (xfractalino) [reply src/engine/physics/NativePhysicsBody.cs]: I searched for the `static extern byte` signature all over the codebase, and this seemed to be the only field using this workaround, so I guess there are no other `DllImport`s suffering from this bug.

Comment (xfractalino) [reply src/engine/physics/NativePhysicsBody.cs]: I've found several fields with bool return type though, so maybe I should modify those as well.

Comment (hhyyrylainen) [reply src/engine/physics/NativePhysicsBody.cs]: You should also look for `DllImport` and check if any method returns a bool as well to make sure they have the right attributes, because there might be unnoticed places in the game with the bug where bool values have been silently wrong all this time (and those wouldn't be found by searching for `extern byte` text).

**Review by hhyyrylainen — APPROVED** [review]
I fixed a few more cases where there were bool return values from our native lib. And then briefly tested the main features in the game and everything seems to have been converted correctly and still works.
