### PR TITLE
Fixed spawner cleaning not working and causing duplicate spawner registrations

### LINKED ISSUE #3544: Cells can spawn in the wrong patch
I moved to a patch that had no other species in, and saw a species from the previous patch spawning quite often in this new location. I suspect the spawn system isn't clearing spawners properly.

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**

So turns out for a while now the patch manager had registered a bunch of duplicate species spawners on each editor cycle. This should fix that. One thing to note was that saving and loading also properly cleaned the spawners so in all my testing until now I had not noticed this problem.

**Related Issues**

closes #3544

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by Oliveriver — APPROVED** [review]
This definitely fixes the scenario which reliably reproduced the issue before, and after testing a few other scenarios, I haven't yet found any nonsensical spawns.

File: simulation_parameters/Constants.cs [hunk 1]
```diff
@@ -40,6 +40,24 @@ public static class Constants
     /// </summary>
     public const float CLOUD_SPAWN_AMOUNT_SCALE_FACTOR = 0.75f;
 
+    /// <summary>
+    ///   Scale factor for how dense microbes spawn (also affected by their populations).
+    /// </summary>
+    /// <remarks>
+    ///   <para>
+    ///     Due to an earlier problem old, species spawners were never cleared so they accumulated a lot.
```
Comment (Oliveriver) [inline simulation_parameters/Constants.cs:48]: Comma placement typo here.

Comment (hhyyrylainen) [reply simulation_parameters/Constants.cs]: Fixed.

File: src/microbe_stage/PatchManager.cs [hunk 2]
```diff
@@ -195,20 +185,16 @@ private void HandleCellSpawns(Patch patch)
                 continue;
             }
 
-            var density = Mathf.Max(Mathf.Log(population / 25.0f) * 0.01f, 0.0f);
+            var density = Mathf.Max(
+                Mathf.Log(population / Constants.MICROBE_SPAWN_DENSITY_POPULATION_MULTIPLIER) *
+                Constants.MICROBE_SPAWN_DENSITY_SCALE_FACTOR, 0.0f);
```
Comment (adQuid) [inline src/microbe_stage/PatchManager.cs:190]: can this be negative?

Comment (hhyyrylainen) [reply src/microbe_stage/PatchManager.cs:190]: I don't know, I just left the Mathf.Max call here anyway. I just converted the magic numbers into proper named constants here.
