### PR TITLE
Art gallery slideshow works properly for models

### LINKED ISSUE #4388: Art gallery slideshow feature doesn't work for models
I just noticed that the slideshow feature does nothing when viewing a model. When viewing the images the slideshow button works correctly and switches to new images.

### PR DESCRIPTION
**Pull request by Brabygg**
**Brief Description of What This PR Does**

The art gallery's slideshow button, which previously did nothing at all when used in the model viewer, now correctly cycles between the viewer's models in order, complete with the correct fade transition.

**Related Issues**

Closes #4388

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [X] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/gui_common/art_gallery/CrossFadableGalleryViewport.cs [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+    private Tween tween = null!;
+#pragma warning restore CA2213
+
+    [Signal]
+    public delegate void Faded();
+
+    /// <summary>
+    ///   Triggers the gallery model viewer's crossfade effect.
+    /// </summary>
+    public bool FadeRequested
```
Comment (Kashnox) [inline src/gui_common/art_gallery/CrossFadableGalleryViewport.cs:21]: Is there any reason to use the FadeRequested property instead of letting SlideScreen call BeginFade() directly?

File: src/gui_common/art_gallery/SlideScreen.cs [hunk 2]
```diff
@@ -332,6 +332,14 @@ private void ChangeSlide(bool fade)
 
         var item = items[currentSlideIndex];
         slideTextureRect.Image = GD.Load(item.Asset.ResourcePath) as Texture;
+
+        if (slideTextureRect.Image != null)
+            return;
+
+        // If texture loading fails, the selected item is a model
+        // These are handled here
+
```
Comment (Kashnox) [inline src/gui_common/art_gallery/SlideScreen.cs:341]: There's no need for an extra line here.

**Review by Kashnox — CHANGES_REQUESTED** [review]
The CrossFadableGalleryViewport seems like a good fix for this problem. There was just one thing that looked a little overly complicated, which I left a review comment about.

File: src/gui_common/art_gallery/CrossFadableGalleryViewport.cs (hunk 1 above)
Comment (hhyyrylainen) [reply src/gui_common/art_gallery/CrossFadableGalleryViewport.cs:21]: I had a look through the changes here and this is the only thing I also noticed that could be improved.

Comment (Brabygg) [reply src/gui_common/art_gallery/CrossFadableGalleryViewport.cs:21]: I tried this, but I don't really see a way to just call the method without running into errors about conflicting static and non-static contexts. ChangeSlide() is static, while BeginFade() needs to be nonstatic. Most direct I can do is probably a signal.

**Comment by Brabygg** [comment]
This commit, I believe, is the closest possible route to calling the method directly. It's certainly shorter and more concise.

File: src/gui_common/art_gallery/CrossFadableGalleryViewport.cs (hunk 1 above)
Comment (Kashnox) [reply src/gui_common/art_gallery/CrossFadableGalleryViewport.cs]: I might have worded my initial review badly. You don't have to call BeginFade() in a static way. You can just call modelViewContainer!.BeginFade()

**Comment by hhyyrylainen** [comment]
I'm confused. Let me try just directly calling the method, I hope you don't mind me committing to your branch...

**Review by hhyyrylainen — APPROVED** [review]
I redid the signal sending with just a direct method call. It seems to work entirely fine. I noticed a very slight bug which I'm not sure is worth fixing: if the user hits the X to cancel the slideshow while it is fading between models, then the next time the slideshow is started it shows with partially faded screen until the model changes once again.
