### PR TITLE
Updated to .NET 7, fixed new code check warnings, rewrote translation extraction in C#

### LINKED ISSUE #3984: Localization script should not ignore `hint_tooltip` translation key when editor description says `PLACEHOLDER`
so that controls with placeholder text can have translatable builtin tooltip.

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**

Updated to .NET 7, updated the analyzers that go with it, and did some warnings fixing (https://forum.revolutionarygamesstudio.com/t/updating-to-disposing-all-godot-objects/975/3), and finally rewrote the translations extractor in C# so that python is no longer required for developing Thrive.

I didn't test the translations extractor on Windows so someone testing that would be good.

**Related Issues**

closes #3984

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: Scripts/GodotSceneTranslationExtractor.cs [hunk 1]
```diff
@@ -0,0 +1,210 @@
...
+            // that combination of state variables here
+
+            // We are allowed to pass all translations through
+            yield return translation;
+        }
+    }
+
+    private void HandleEditorDescription(string description)
+    {
+        if (description.Contains(PlaceHolderMarker))
```
Comment (84634E1A607A) [inline Scripts/GodotSceneTranslationExtractor.cs:200]: `TOOLTIP_PLACEHOLDER` contains `PLACEHOLDER`, so ignoring tooltip translation will ignore the name as well?

By the way, *Placeholder* is used to make the UI in Godot editor look good. Tooltip isn't visible in Godot editor, so I guess there isn't a need to add placeholder tooltips?

File: doc/style_guide.md [hunk 2]
```diff
@@ -421,11 +421,58 @@ Godot usage
...
+  non-Godot objects should still be disposed according to good style
+  so the warning helps in catching these cases. For example many
+  standard C# classes need to be disposed and for those objects, even
+  when they are held by Godot objects, custom dispose methods should
+  be implemented.
+
+- For most Godot-derived types a Dispose method just needs to be added
+  to dispose any `NodePath` variables. Note that Godot autoloads,
+  loading saves, and using things in the editor, dispose not fully
+  initialized Nodes. To workaround this the dispose method should
```
Comment (84634E1A607A) [inline doc/style_guide.md:456]: I don't understand what this sentence wants to tell...

File: src/engine/MissingExportVariableValueException.cs [hunk 3]
```diff
@@ -0,0 +1,18 @@
+﻿using System;
+using System.Runtime.Serialization;
+
+/// <summary>
+///   Thrown when a Godot Node derived type is missing a variable that should be set through the Godot editor.
+///   If you see this check that you didn't forget to add a value or if Godot has decided to automatically set some
```
Comment (84634E1A607A) [inline src/engine/MissingExportVariableValueException.cs:6]:
```suggestion
///   If you see this, check if you had forgotten to add a value, or if Godot had decided to automatically set some
```

File: Scripts/GodotSceneTranslationExtractor.cs (hunk 1 above)
Comment (hhyyrylainen) [reply Scripts/GodotSceneTranslationExtractor.cs:200]: I just added the tooltip placeholder, just for feature completeness (i.e. if there ever is a case where a tooltip should already be ignored, it can be). Also in the logic I assumed that if tooltip is ignored the other parts are also ignored, so `TOOLTIP_PLACEHOLDER` containing `PLACEHOLDER` is intended.

File: doc/style_guide.md (hunk 2 above)
Comment (hhyyrylainen) [reply doc/style_guide.md:456]: Godot sometimes makes partly initialized objects. I can try to slightly clarify this by saying that first and the nputting the cases I know in parentheses.

**Comment by hhyyrylainen** [comment]
I updated some of the less clear comments.

Also I tested doing a fresh clone and that doesn't exhibit the Godot editor crashing. So it is purely if outdated Thrive code is loaded the editor can crash. The solution is to then either clean the build files or compile Thrive outside the Godot editor.

**Review by 84634E1A607A — APPROVED** [review]
Played for a while and it seems okay.

**Comment by hhyyrylainen** [comment]
Did you test the translations update on Windows? I'm fairly confident it should work fine, but it might need a few file writing tweaks to fully work.

**Comment by 84634E1A607A** [comment]
No.

**Comment by hhyyrylainen** [comment]
Could you test it? It's fine if you can't but I'll merge this then anyway, but if there is a problem a follow up PR will be needed ASAP.

**Comment by 84634E1A607A** [comment]
I don't have any Windows devices with Dotnet installed now so I can't test it.
