### PR TITLE
Enabled sprinting by default (fixed keybinding, running with no ATP, GUI tweaks)

### LINKED ISSUE #3887: Allow binding game input actions to modifier keys (Shift, alt etc.)
though maybe some kind of warning should be shown that if you have another keybinding using that modifier, the results may be unpredictable (and at least some minimal testing should be done that using for example shift for something works as intended)

### LINKED ISSUE #5283: Sprinting allows speeding up when dying from lack of ATP
related to: https://github.com/Revolutionary-Games/Thrive/issues/5281

kind of related it seems that sprinting never deals damage even after like a minute of max speed sprinting

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**

Enables sprinting by default. Even though not everything in https://github.com/Revolutionary-Games/Thrive/issues/5284 is done I think we'll have enough time to fix the most important things.

**Related Issues**

closes #5283
closes #3887

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/engine/input/key_mapping/InputEventItem.cs [hunk 1]
```diff
@@ -132,6 +147,83 @@ public override void _ExitTree()
         KeyPromptHelper.ControllerTypeChanged -= OnControllerChanged;
     }
 
+    public override void _Process(double delta)
+    {
+        // Delayed key binding (to allow shift to be used in modifier combinations, for example)
+        if (modifierKeyStatus == ModifierKeyMode.None)
+            return;
+
+        timeSinceModifier += delta;
```
Comment (CI09) [inline src/engine/input/key_mapping/InputEventItem.cs:156]: I noticed that with standalone Shift keybind there is delay between when button is pressed and when it is accepted, it is minor thing though and I guess sooner or later player would figure it out

**Review by CI09 — APPROVED** [review]
I think everything is good, maybe except a bug where (at least) sprinting doesn't work when rebound, at least for me.

File: src/engine/input/key_mapping/InputEventItem.cs (hunk 1 above)
Comment (hhyyrylainen) [reply src/engine/input/key_mapping/InputEventItem.cs:156]: It's kind of necessary because otherwise you cannot bind stuff to like "Shift+W" as it would immediately just bind to shift and the W input would be just ignored. So there has to be some delay, though if lower value still works that could be fine (like maybe 300 ms or so).

**Comment by hhyyrylainen** [comment]
Yeah, the conflict stuff is kind of bugged right now. I opened one more issue about it today as it was *really* not working for me: https://github.com/Revolutionary-Games/Thrive/issues/5352

**Comment by hhyyrylainen** [comment]
I forgot to push my last commit for the day, so there's now another commit.
