### PR TITLE
Fix membrane color not applying in multicell editor

### LINKED ISSUE #3367: Multicellular membrane colour edit doesn't apply if only it was changed
seems to be a regression from the dynamic MP.

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Put membrane color changing through the editor action system so this change registers to the editor and work with undo/redo.

**Related Issues**

Fixes #3367 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/gui_common/TweakedColourPicker.cs [hunk 1]
```diff
@@ -194,7 +194,6 @@ public new Color Color
                 return;
 
             base.Color = value;
-            EmitSignal("color_changed", value);
```
Comment (Kasterisk) [inline src/gui_common/TweakedColourPicker.cs:197]: This had to be removed as this causes repeated signal emissions, causing problems. Also redundant because it should already be emitted under the hood.

Comment (hhyyrylainen) [reply src/gui_common/TweakedColourPicker.cs:197]: @84634E1A607A I think you made the tweaked colour picker, so do you have anything to say about this change?

Comment (84634E1A607A) [reply src/gui_common/TweakedColourPicker.cs:197]: I recall I added this because sometimes the native color_changed signal is not emitted. (Perhaps when you change the Color property directly)

File: src/microbe_stage/editor/action_data/ColourActionData.cs [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+    }
+
+    public override bool WantsMergeWith(CombinableActionData other)
+    {
+        return other is ColourActionData;
+    }
+
+    protected override int CalculateCostInternal()
+    {
+        // Changing membrane color has no cost
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/action_data/ColourActionData.cs:22]:
```suggestion
        // Changing membrane colour has no cost
```

File: src/microbe_stage/editor/action_data/ColourActionData.cs [hunk 3]
```diff
@@ -0,0 +1,77 @@
...
+            }
+
+            PreviousColour = colourChangeActionData.PreviousColour;
+            return;
+        }
+
+        NewColour = colourChangeActionData.NewColour;
+    }
+
+    protected override ActionInterferenceMode GetInterferenceModeWithGuaranteed(CombinableActionData other)
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/action_data/ColourActionData.cs:56]: These methods look like they are in different order than other actions, please reorder them to be in a consistent order.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Besides the need for playtesting to ensure the "color_changed" signal removal doesn't cause issues, I have just one tiny nitpick about the code style (and one typo in a comment).

File: src/microbe_stage/editor/action_data/ColourActionData.cs (hunk 3 above)
Comment (Kasterisk) [reply src/microbe_stage/editor/action_data/ColourActionData.cs:56]: Right, was put this way by my IDE.

File: src/gui_common/TweakedColourPicker.cs (hunk 1 above)
Comment (Kasterisk) [reply src/gui_common/TweakedColourPicker.cs:197]: Hm yeah, just isolated and tested this and it indeed doesn't automatically actually get emitted....

Comment (Kasterisk) [reply src/gui_common/TweakedColourPicker.cs:197]: Actually maybe it's better to not override this property, instead separate it to a new method as we sometimes want Color to not emit a signal?

Comment (hhyyrylainen) [reply src/gui_common/TweakedColourPicker.cs:197]: Probably yeah, but then it should be called here as well... or?

Comment (Kasterisk) [reply src/gui_common/TweakedColourPicker.cs:197]: Yes, so we will use the base `Color` and a `SetColor` method that sets `Color` and emits signal, this property should always be used in TweakedColorPicker, `Color` can be for other places.

@84634E1A607A What was actually the reason for emitting the signal by the way?

Comment (84634E1A607A) [reply src/gui_common/TweakedColourPicker.cs:197]: > I think it should since that also calls this overriden property.

Yes. (I said once, when this property is not overriden.) And this is why I chose to emit a signal here.

File: src/microbe_stage/editor/action_data/ColourActionData.cs (hunk 3 above)
Comment (Kasterisk) [reply src/microbe_stage/editor/action_data/ColourActionData.cs]: Fixed.

File: src/gui_common/TweakedColourPicker.cs (hunk 1 above)
Comment (84634E1A607A) [reply src/gui_common/TweakedColourPicker.cs:197]: Yes, but I didn't playtest so I'm not sure all functions are still correct.

Comment (84634E1A607A) [reply src/gui_common/TweakedColourPicker.cs:197]: I'd prefer a `if (Color == colour) return;` added

**Comment by Oliveriver** [comment]
Tested and it seems to work fine in both unicellular and multicellular settings for me.

**Review by hhyyrylainen — APPROVED** [review]
This is probably fine now, but I'll give a bit more time for testing.
