### PR TITLE
More various UI fixes and tweaks

### LINKED ISSUE #1859: Modify Godot tooltip theme to be more visible
make the tooltip on (in options performance tab) on "Cloud resolution divisor" to be more readable, the black text on transparent is really hard to read

### LINKED ISSUE #1973: Add styling for colour picker + button tooltip
I think it uses the default Godot tooltip that we don't have styling for:

should be styled to at least have the text white, and if possible made to look as close to the custom tooltips as possible.

This should be easy to do by editing the thrive theme.

### LINKED ISSUE #2011: Provide feedback on enter press after writing cell name
**Describe the bug**
1. After renaming the cell to something other than the default name when pressing Enter the **| beam** does not disappear even though the name itself is saved. This could be confusing because it leads to the impression that the new name is not saved.

**To Reproduce**
1. For bug # 1 -> Try to rename the cell in the Microbe Editor.

**Expected behavior**
1. For bug # 1 -> After pressing Enter or the box loses focus the | beam should disappear.

**System info (please complete the following information):**
- Thrive version [0.5.3.0 RC1]

### LINKED ISSUE #2012: Show player cell in hover over panel
The player cell is explicitly skipped when hovering over it in the top right panel. This skip should be removed and instead it should say "Player Cell" or "You"  or "Your Cell" (depending on whatever people perefer).

### LINKED ISSUE #2017: ATP in ATP balance bar tooltip is not translated
https://github.com/Revolutionary-Games/Thrive/blob/a8f92adb4fdae431bd4bc18107bf676128b5c07f/src/microbe_stage/editor/MicrobeEditorGUI.cs#L696

doesn't use translations, also in the same method some lines down is another string that doesn't use translations.

### LINKED ISSUE #2021: The Help Menu Needs An Upper Border
**Describe the bug**
The help menu currently have a border only at the bottom just above the "Close" button. While scrolling down the help messages their upper part looks cut off without a border.

**To Reproduce**
1. Open the help menu and scroll down the messages.

**Expected behavior**
The help menu should have a upper border, similar to the bottom one (above the "Close" button) to reduce the effect of cut off text during scrolling down.

**Screenshots**
Untitled

**System info:**
- Thrive version [0.5.3.0]

### LINKED ISSUE #2027: Options save confirmation popup doesn't adapt to translation size
needfix
I found two, see screenshot(s).

### PR DESCRIPTION
**Pull request by Kasterisk**
Some more fixes and tweaks/additions to the UI:

- Major tweaks to the popup dialogs. Added Label child node as the popup's dialog text to make use of Lato font for readability. Showing popups should now preferably use the `PopupCentered` method instead of `PopupCenteredMinsize`, for size shrinking purposes.
- Changed the options menu back confirm dialog type to AcceptDialog to make it resize according to its children automatically.
- Disabled scrolling for the membrane rigidity to fix unwanted changes to the rigidity value while scrolling membrane tab.
- Added background panel to the help screen.
- Added more null checks while getting legend container node child.
- Tweaked tweenings and screen fades
- Pressing enter on the save name box on NewSaveMenu now perform save (equivalent of pressing the Save button next to it).
- Changed MP bar value and editor arrow movement interpolation to use Tween.

Fixes #2027
Closes #2021 
Fixes #2017 
Closes #2012 
Fixes #2011 
Fixes #1973 
Fixes #1859

### CODE REVIEW

File: src/saving/SaveManagerGUI.cs [hunk 1]
```diff
@@ -203,23 +203,23 @@ private void DeleteSelectedButtonPressed()
     {
         GUICommon.Instance.PlayButtonPressSound();
 
-        deleteSelectedConfirmDialog.DialogText =
+        deleteSelectedConfirmDialog.GetNode<Label>("Label2").Text =
             string.Format(CultureInfo.CurrentCulture,
                 TranslationServer.Translate("DELETE_SELECTED_SAVE_WARNING"),
                 Selected.Count);
-        deleteSelectedConfirmDialog.PopupCenteredMinsize();
+        deleteSelectedConfirmDialog.PopupCentered(deleteSelectedConfirmDialog.GetMinimumSize());
```
Comment (hhyyrylainen) [inline src/saving/SaveManagerGUI.cs:210]: I have one idea regarding this. Couldn't we make an extension method for this? Perhaps like PopupCenteredProperly? That could then just do this GetMinimumSize call automatically making all of the places using it look neater and more future proof against needing more changes.

Comment (Kasterisk) [reply src/saving/SaveManagerGUI.cs:210]: Yeah, that's what I was originally going for (with messy implementation) but finally found that this also work with lesser code to write. But I agree that an extension should just be used, I think `PopupCenteredShrink` name is more fitting.

File: src/engine/input/key_mapping/InputGroupList.cs [hunk 2]
```diff
@@ -131,17 +131,17 @@ public InputEventItem Conflicts(InputEventItem item)
         latestDialogConflict = conflict;
         latestDialogNewEvent = newEvent;
 
-        conflictDialog.DialogText = string.Format(CultureInfo.CurrentCulture,
+        conflictDialog.GetNode<Label>("Label2").Text = string.Format(CultureInfo.CurrentCulture,
```
Comment (FuJa0815) [inline src/engine/input/key_mapping/InputGroupList.cs:134]: couldn't you give Label2 a better name 😄

**Review by FuJa0815 — CHANGES_REQUESTED** [review]

File: src/engine/input/key_mapping/InputGroupList.cs (hunk 2 above)
Comment (Kasterisk) [reply src/engine/input/key_mapping/InputGroupList.cs]: Changed to `DialogText` :)

File: doc/style_guide.md [hunk 3]
```diff
@@ -163,8 +163,9 @@ Godot usage
   (`?`). The content of the popup should give more details and also
   end with a question.
 
-- Popups should be shown with `PopupCenteredMinsize()` unless there's
-  a good reason why something else is required.
+- Popups should be shown with `PopupCentered()` unless there's
+  a good reason why something else is required. To shrink the popup
+  to a minimum size, use the `PopupCenteredShrink()` extension method.
```
Comment (hhyyrylainen) [inline doc/style_guide.md:168]: I think this should be worded so that PopupCenteredShrink is the optimal, PopupCentered is the second best choice and then anything else besides those need a good reason why they are used.

File: src/engine/ControlHelpers.cs [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+    /// <summary>
+    ///   Shows the popup in the center of the screen and shrinks it to the minimum size,
+    ///   alternative to PopupCentered.
+    /// </summary>
+    public static void PopupCenteredShrink(this Popup popup)
+    {
+        popup.PopupCentered(popup.GetMinimumSize());
+
+        // In case the popup sizing stuck (this happens sometimes)
+        Invoke.Instance.Queue(() =>
```
Comment (hhyyrylainen) [inline src/engine/ControlHelpers.cs:17]: I'd prefer to add a boolean parameter to this method that defaults to true, called something like runSizeUnstuck. So if something ever needs to skip this code, they can.

File: src/gui_common/fonts/Lato-Regular-SlightlySmall.tres [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+
+[ext_resource path="res://assets/fonts/Lato-Regular.ttf" type="DynamicFontData" id=1]
+[ext_resource path="res://assets/fonts/NotoSans-Regular.ttf" type="DynamicFontData" id=2]
+[ext_resource path="res://assets/fonts/NotoSansHebrew-Regular.ttf" type="DynamicFontData" id=3]
+[ext_resource path="res://assets/fonts/NotoSansCJKsc-Regular.otf" type="DynamicFontData" id=4]
+[ext_resource path="res://assets/fonts/NotoSansCJKtc-Regular.otf" type="DynamicFontData" id=5]
+[ext_resource path="res://assets/fonts/NotoEmoji-Regular.ttf" type="DynamicFontData" id=6]
+
+[resource]
+size = 18
```
Comment (hhyyrylainen) [inline src/gui_common/fonts/Lato-Regular-SlightlySmall.tres:11]: This file should be named `AlmostSmaller` to be consistent with the existing files (`Jura-DemiBold-AlmostSmaller.tres`)

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
A few code related comments. I tested this briefly and didn't notice serious issues. One note about the new dialogs, though, many of them seem to have bit unoptimal word wrapping:

**Comment by hhyyrylainen** [comment]
It doesn't look like this actually fixes https://github.com/Revolutionary-Games/Thrive/issues/1859
Still seeing this:

**Comment by Kasterisk** [comment]
Huh, that's weird, I remember fixing that. The changes must have reset or something.. so does the color picker tooltips.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
I re-tested everything and looked at the code, everything except this one thing is fine: when pressing enter (regarding issue #2011) if the name is invalid, it shouldn't unfocus the name, to indicate to the player that it is invalid.

**Comment by hhyyrylainen** [comment]
Actually I just noticed another bug: when quickly going left and right from the organelle panel back to the editor, I got the MP bar stuck like this:

**Comment by Kasterisk** [comment]
> Actually I just noticed another bug: when quickly going left and right from the organelle panel back to the editor, I got the MP bar stuck like this:

Maybe has to do with the `delta` multiplying? I really couldn't get it to happen by rapidly moving the mouse in and out of the panel though, so I guess this only happens in a high enough framerate. Could you confirm whether the MP bar lerp changes were the one causing the bug by reverting it?

**Comment by hhyyrylainen** [comment]
At least when testing the latest BOTD, it doesn't happen.
Could this also be related to the ATP bar getting stuck?
One potential fix (if that problem description is accurate), would be to Queue Invoke a special method that updates the lerping progress *if* there isn't a follow up _Process call with proper delta, to update the bar progress. Now that I typed that out, I'm not so sure about that... one more idea: just flat out get a current time from C# standard method, and then in each _Process call just check how long it's been since the animation started or something?

**Comment by Kasterisk** [comment]
I've been looking more into this and looks like the typical way of doing lerps `value = Mathf.Lerp(value, targetValue, constant * deltatime)` is wrong, which could lead to unintended behaviors. See this [article](http://www.blueraja.com/blog/404/how-to-use-unity-3ds-linear-interpolation-vector3-lerp-correctly) (intended for Unity's Vector3 but the concept should be the same). If I understand correctly, the current lerp form makes so the value only move closer to `targetValue` by `constant` thus never actually reaching the target, usually not noticeable but multiplying by `delta` might exacerbate it, especially on the bars. At least, that is my understanding why the bar appears stuck, there could be other causes to this though.

I did a workaround which might keep the thing from happening, at least for the MP bar by using Tween nodes (which I think is already framerate independent) for interpolations and only doing the lerps if needed in a separate method and not inside `_Process`, this should alleviate the behavior described above. If this fixes the issue, I think we should just go with this for now and fix other bar lerp related problems in future PRs.

Unrelated to the Lerp bug, I've now disabled the editor button's Light2D node which might potentially fix the editor button disappearing bug (the button still flashes, though with no extra effect). If there are no more reports of it happening, I think we could close #2022.

**Comment by hhyyrylainen** [comment]
> I did a workaround which might keep the thing from happening, at least for the MP bar by using Tween nodes (which I think is already framerate independent) for interpolations and only doing the lerps if needed in a separate method and not inside _Process, this should alleviate the behavior described above. If this fixes the issue, I think we should just go with this for now and fix other bar lerp related problems in future PRs.

What about writing a custom Lerp (with moving target?) implementation for use in GUI? It would be a pretty straightforward lerp implementation, but it would snap to the final value once it gets close enough. It could also have explicit stuck prevention (if the target value hasn't changed, and hasn't been reached for some time, just snap to the target value)

> Unrelated to the Lerp bug, I've now disabled the editor button's Light2D node which might potentially fix the editor button disappearing bug (the button still flashes, though with no extra effect). If there are no more reports of it happening, I think we could close #2022.

If it doesn't affect the visuals, shouldn't the node be deleted instead of disabled?

**Comment by hhyyrylainen** [comment]
I playtested this now and the bar no longer gets stuck. Unless I'm misremembering how the button worked before, it seems to look slightly different now? If that's the case, then could / should we have an option in the graphics menu for using 2D light in the GUI, so that people who get the disappearing problem could toggle it off to see if that fixes things?I playtested this now and the bar no longer gets stuck. Unless I'm misremembering how the button worked before, it seems to look slightly different now? If that's the case, then could / should we have an option in the graphics menu for using 2D light in the GUI, so that people who get the disappearing problem could toggle it off to see if that fixes things?

**Comment by Kasterisk** [comment]
> What about writing a custom Lerp (with moving target?) implementation for use in GUI? It would be a pretty straightforward lerp implementation, but it would snap to the final value once it gets close enough. It could also have explicit stuck prevention (if the target value hasn't changed, and hasn't been reached for some time, just snap to the target value)

Yeah I think that could also work. I didn't add that for now since Tween is used for the bars (the only ones that seems bugged) and other `Mathf.Lerp` uses in other places doesn't have apparent problems. But I'll try experiment with that maybe tomorrow.

> If it doesn't affect the visuals, shouldn't the node be deleted instead of disabled?

Well, in case if it turns out to not fix the bug, it could be re-enabled later if wanted.

> I playtested this now and the bar no longer gets stuck.

Nice :)

> Unless I'm misremembering how the button worked before, it seems to look slightly different now? If that's the case, then could / should we have an option in the graphics menu for using 2D light in the GUI, so that people who get the disappearing problem could toggle it off to see if that fixes things?

The Light2D adds that spotlight effect on the button, the button just flashes like in the old versions without it. Also I don't think it's necessary enough to warrant adding an option for toggling a single trivial effect. Maybe add a single option that toggles all GUI effects instead (in case more to be added in the future) to avoid cluttering the options menu?

**Comment by hhyyrylainen** [comment]
> The Light2D adds that spotlight effect on the button, the button just flashes like in the old versions without it. Also I don't think it's necessary enough to warrant adding an option for toggling a single trivial effect. But maybe we could add a single option that toggles all GUI effects instead (in case more to be added in the future) to avoid cluttering the options menu?

I think without the extra pulse effect, it is much more unnoticeable that the button is active. Already when watching let's plays I'm in physical pain because people are super oblivious to when the button becomes active. So I think that problem only becomes worse if the effect isn't as noticeable as before.

**Comment by Kasterisk** [comment]
Yeah, that's a fair point but an editor button tutorial #2056 could hopefully help with that though.

**Comment by hhyyrylainen** [comment]
Would it be possible for you to put that light 2D disable to a separate branch, so that we can handle that separate as otherwise getting this PR merged will drag on even longer?

**Comment by Kasterisk** [comment]
Reverted the Light2D node change.

**Review by hhyyrylainen — APPROVED** [review]

**Comment by hhyyrylainen** [comment]
Still doesn't fully fix the ATP bar, but it now at least has a chance to fix itself, but it gets stuck for up to like a second. Especially noticeable when suiciding.
