### PR TITLE
Fix player microbe name not getting updated when species name is modified

### LINKED ISSUE #4924: Player microbe name doesn't get updated when species name is modified
Got a report that when exiting the editor after renaming the player species the player cell still shows the old name when hovered over. I think that maybe the readable name component is not being updated on the player, which would explain this if someone confirms that respawning fixes the problem.

https://discord.com/channels/228300288023461893/958598553389903913/1211965857744420925

### PR DESCRIPTION
**Pull request by CI09**
**Brief Description of What This PR Does**

Sets name to species name when re-applying cell properties

**Related Issues**

Closes #4924

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/microbe_stage/components/CellProperties.cs [hunk 1]
```diff
@@ -532,6 +532,9 @@ public static bool IsMembraneReady(this ref CellProperties cellProperties)
             cellProperties.Colour = newDefinition.Colour;
             cellProperties.MembraneRigidity = newDefinition.MembraneRigidity;
 
+            // Sets name; uses baseReproductionCostFrom as it is species
+            entity.Get<ReadableName>().Name = new LocalizedString(baseReproductionCostFrom.FormattedName);
```
Comment (hhyyrylainen) [inline src/microbe_stage/components/CellProperties.cs:536]: This should have a safety check to ensure the component exists as it is not critical to the primary function of this method.

**Comment by CI09** [comment]
I realized it actually doesn't work right now (I'm running debug differently now and I need to do some extra steps to get newest code changes into the build)

**Comment by CI09** [comment]
Nevermind, it actually works, I just forgot that I switched back to master branch

**Comment by hhyyrylainen** [comment]
The code change looks fine. Let's wait a couple of days to see if anyone else can playtest this.

**Comment by hhyyrylainen** [comment]
Looks like I forgot about this due to focusing entirely on the Godot 4 version, but this should be fine to merge now.
