### PR TITLE
Fixes to ATP and health bars

### LINKED ISSUE #1658: ATP and health bar can get stuck
https://github.com/Revolutionary-Games/Thrive/pull/1587#issuecomment-700172281

### LINKED ISSUE #2249: Max Health resets to 100 (in health bar) when Player Dies
**Describe the bug**

When a player dies, the health meter shows the default max health of 100 than whatever the player microbe had.

**To Reproduce**
1. Click the suicide button
2. Observe health meter

**Expected behavior**
Health bar should show 0 out of actual max health.

### LINKED ISSUE #2367: ATP can sometimes be shown to be above the storage limit
maybe linked to low FPS as with the same save where this shows up this doesn't happen on my computer.

screenshot

Save file: [max_atp_problem.zip](https://github.com/Revolutionary-Games/Thrive/files/6682601/max_atp_problem.zip)

### PR DESCRIPTION
**Pull request by adQuid**
**Brief Description of What This PR Does**

HUD now remembers the player's max health on death. Also earmarked in a change to fix the ATP and health bars not fully filling/draining, and not rounding to the nearest whole number since some organelles have 0.5 capacity.

**Related Issues**

Fixes #2249 
Fixes #1658 
Fixes #2367 

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

File: src/microbe_stage/MicrobeHUD.cs [hunk 1]
```diff
@@ -170,6 +170,12 @@ public class MicrobeHUD : Node
     private GridContainer environmentPanelBarContainer;
     private Panel compoundsPanel;
 
+    // Store these statefully for after player death
+    private float hp;
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeHUD.cs:174]: hp and atpAmount shouldn't need saving, right? As if the player is dead they can't have any health or ATP.

File: src/microbe_stage/MicrobeHUD.cs [hunk 2]
```diff
@@ -805,20 +814,28 @@ private void UpdateHealth(float delta)
...
+            hp = 0.0f;
+        }
 
         healthBar.MaxValue = maxHP;
-        healthBar.Value = MathUtils.Lerp((float)healthBar.Value, hp, 3.0f * delta, 0.1f);
+        SmoothlyUpdateBar(healthBar, hp, delta);
         hpLabel.Text = StringUtils.FormatNumber(Mathf.Round(hp)) + " / " + StringUtils.FormatNumber(maxHP);
     }
 
+    private void SmoothlyUpdateBar(TextureProgress bar, float target, float delta)
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeHUD.cs:833]: Does this truly finally work against the bars getting stuck problem?
Also this should be moved to some helper class in the gui_common folder.

File: src/microbe_stage/MicrobeHUD.cs [hunk 3]
```diff
@@ -805,20 +814,28 @@ private void UpdateHealth(float delta)
...
+    {
+        var weight = (float)Math.Min(3.0f * delta + 0.2f, 1.0f);
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeHUD.cs:835]: I'd put in a 0 or negative delta guard in this method and link that issue that the delta guards link.

File: src/microbe_stage/MicrobeHUD.cs (hunk 1 above)
Comment (adQuid) [reply src/microbe_stage/MicrobeHUD.cs:174]: The fact that a dead microbe doesn't still contain ATP is a current game rule, not a absolute truth, so I'd be reluctant to assume that here just in case. In general it felt neater to treat such closely tied variables in the same way, but I have no objections if you want them as strictly method vars.

File: src/microbe_stage/MicrobeHUD.cs (hunk 2 above)
Comment (adQuid) [reply src/microbe_stage/MicrobeHUD.cs:833]: Happy to take an excuse to shrink this file size, if only by 5 lines.

File: src/microbe_stage/MicrobeHUD.cs (hunk 1 above)
Comment (hhyyrylainen) [reply src/microbe_stage/MicrobeHUD.cs:174]: Even if a dead microbe would contain ATP, what use is it to show the player?
I guess the player could see if they died due to running out of ATP...
But the hp variable here definitely should go as it serves no purpose.

File: src/gui_common/GUICommon.cs [hunk 4]
```diff
@@ -55,6 +57,18 @@ public static void PopupMinSizeMarginPosition(Popup popup)
         popup.RectPosition = new Vector2(left, top);
     }
 
+    public static void SmoothlyUpdateBar(TextureProgress bar, float target, float delta)
+    {
+        if (delta <= 0.0f)
+        {
+            var paramName = "delta must be positive!";
+            throw new ArgumentOutOfRangeException(paramName);
+        }
```
Comment (hhyyrylainen) [inline src/gui_common/GUICommon.cs:66]:
```suggestion
        // https://github.com/Revolutionary-Games/Thrive/issues/1976
        if (delta <= 0)
            return;
```

File: src/microbe_stage/MicrobeHUD.cs [hunk 5]
```diff
@@ -170,6 +170,10 @@ public class MicrobeHUD : Node
     private GridContainer environmentPanelBarContainer;
     private Panel compoundsPanel;
 
+    // Store these statefully for after player death
+    private float maxHP;
+    private float maxATP;
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeHUD.cs:175]: These should default to value of 1 so that there aren't any divide by zero errors if the player object isn't set immediately when the game starts.

File: src/gui_common/GUICommon.cs [hunk 6]
```diff
@@ -1,5 +1,7 @@
-﻿using Godot;
-using Godot.Collections;
+﻿using System;
+using Godot;
+using Array = Godot.Collections.Array;
+using Object = Godot.Object;
```
Comment (hhyyrylainen) [inline src/gui_common/GUICommon.cs:4]: With the exception throwing gone, I think these changes can be reset.

File: src/microbe_stage/MicrobeHUD.cs [hunk 7]
```diff
@@ -779,19 +783,20 @@ private void UpdateATP(float delta)
...
 
+        // Update to the player's current HP, unless the player is dead
         if (stage.Player != null)
         {
             var compounds = GetPlayerColonyOrPlayerStorage();
 
-            atpAmount = Mathf.Ceil(compounds.GetCompoundAmount(atp));
-            capacity = compounds.Capacity;
+            // Only show ATP changes in increments of 0.5
+            atpAmount = Mathf.Ceil(compounds.GetCompoundAmount(atp) * 2) / 2.0f;
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeHUD.cs:793]: What's this change? This changes the ATP display more than the title of this PR gives a clue about...

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

File: src/microbe_stage/MicrobeHUD.cs (hunk 7 above)
Comment (adQuid) [reply src/microbe_stage/MicrobeHUD.cs:793]: My bad; just added it to the PR description. This allows the ATP to be displayed in half increments, since with the balance changes max ATP isn't always a whole number.

Comment (hhyyrylainen) [reply src/microbe_stage/MicrobeHUD.cs:793]: Wouldn't it still be better to use the actual values on the bars? If needed for the numbers, ATP could be shown formatted to just one decimal place.

File: src/gui_common/GUICommon.cs (hunk 4 above)
Comment (adQuid) [reply src/gui_common/GUICommon.cs:66]: Now that this is a public function, I don't think this is a good idea. Future developers will be free to use this code in any UI code, including outside of update methods where "delta" becomes a less obvious concept. Giving a default value of 0.0f, or worse SOMETIMES passing in that value, will result in one of those implicit quiet failures that leads to those hair-pulling kinds of bugs. With code in a helper library you can't make assumptions about how it will be used.

File: src/microbe_stage/MicrobeHUD.cs (hunk 7 above)
Comment (adQuid) [reply src/microbe_stage/MicrobeHUD.cs:793]: The problem with the numbers is that ATP is actually changing every frame, you just don't notice when rounding since it's usually just a few decimal points at the same time. Change the 2s to 10s and you'll see the flicker.

I guess there's no problem with using the real floats for the bar though.

File: src/gui_common/GUICommon.cs (hunk 4 above)
Comment (hhyyrylainen) [reply src/gui_common/GUICommon.cs:66]: The game needs to **not** crash in any GUI functionality because of the silliness done by Godot engine.
Either this code gets added here, or the biggest warning imaginable needs to be added as a documentation comment on this method and all usages of this method that take in a delta value from Godot need to be verified (and preferrably also added a comment there) that negative delta can't be passed in.

Wouldn't this interpolation not do anything anyway passing in a 0 delta? So anyway this method doesn't work if proper delta from Godot is not passed in. An xml doc comment saying that you *must* pass in a real delta otherwise the method won't do anything, would be enough, right?

File: src/microbe_stage/MicrobeHUD.cs (hunk 7 above)
Comment (hhyyrylainen) [reply src/microbe_stage/MicrobeHUD.cs:793]: Would rounding to a single decimal place be a good middle ground, still pretty good precision but it wouldn't change as rapidly as displaying the entire value?

Comment (adQuid) [reply src/microbe_stage/MicrobeHUD.cs:793]: No, you will see a change every frame. That's what I tried first before moving to the 0.5 precision, and even then you still see it flicker once or twice sometimes when you catch it right.

Comment (hhyyrylainen) [reply src/microbe_stage/MicrobeHUD.cs:793]: Has it always been like that, or is this a new problem that needs fixing in this PR?
@Kasterisk @buckly90 thoughts?

Comment (adQuid) [reply src/microbe_stage/MicrobeHUD.cs:793]: My assumption here (and I didn't test it out) is that ATP cost and ATP generation are happening in different places, so sometimes the GUI thread runs after the paycheck comes in but before the bills are paid or vice versa, so sometimes the exact ATP will be a little different. If that's true, then this might be a problem with really big microbes, but I wanted to limit scope since I was already adding more to the issue with this fix.

Comment (buckly90) [reply src/microbe_stage/MicrobeHUD.cs:793]: It does seem that after I set storage amounts to decimal numbers, the ATP bar has trouble remianing completely full when it otherwise should be. I'm not certain what exactly causes it but my assumption is it's something to do with processes shutting off when the player is at capacity, combined with low capacity and high ATP costs.

File: src/gui_common/GUICommon.cs (hunk 4 above)
Comment (adQuid) [reply src/gui_common/GUICommon.cs:66]: Lets face it: you and I don't read all the comments on the helper libraries before we use them, and we can't expect the next guys to do so. More broadly though, I think that we can do better than just saying, "hey, if you use this generic code in a certain way it will do strange stuff." Right now this procedure still makes assumptions about the context in which it's called, which is a clear example of how NOT to do the Single Responsibility Principle. 

I can think of two solutions. The lazy one is to just put this back in MicrobeHUD and not claim it's generic. The more exciting idea would be to replace the delta with a speed parameter that helps determine how fast the bar moves. MicrobeHUD could then pick a speed based on delta within it's on context, and another user can pick speed whatever way they want. I won't shed a tear if a dev sets speed to zero, then wonders why the bar doesn't move.

File: src/microbe_stage/MicrobeHUD.cs (hunk 5 above)
Comment (adQuid) [reply src/microbe_stage/MicrobeHUD.cs:175]: I don't see any places where they are actually used in a denominator. Line 799 is string concatenation, not division.

File: src/gui_common/GUICommon.cs (hunk 6 above)
Comment (adQuid) [reply src/gui_common/GUICommon.cs:4]: Looks like it wants two aliases over a single System.Math call: https://app.circleci.com/pipelines/github/Revolutionary-Games/Thrive/4105/workflows/209b4038-25c7-4d43-9ecf-b0fa9b6ed564/jobs/13356

This is your code on linters.

File: src/microbe_stage/MicrobeHUD.cs (hunk 7 above)
Comment (hhyyrylainen) [reply src/microbe_stage/MicrobeHUD.cs:793]: @adQuid that's very unlikely to be the case because so far threading is only used within a single category of operations, for example compound cloud updates, AI updates, process system, meaning that the ordering between microbe _Process and the process system running (that runs the cellular processes) is fixed. What is more likely is that processes don't run if only partially their output would fit in the cell storage, to not waste resources. So the ATP amount oscillates between the ATP generation running pretty much to fill  the ATP bar, and there being a little bit empty ATP space left over, but not enough to run a process to fill up the storage.

Comment (hhyyrylainen) [reply src/microbe_stage/MicrobeHUD.cs:793]: I guess it's fine then to do this rounding here, then.

File: src/microbe_stage/MicrobeHUD.cs (hunk 5 above)
Comment (hhyyrylainen) [reply src/microbe_stage/MicrobeHUD.cs:175]: Godot does that internally, at least it is not happy to have a bar max value be 0 and it will print errors.

File: src/gui_common/GUICommon.cs (hunk 4 above)
Comment (hhyyrylainen) [reply src/gui_common/GUICommon.cs]: After sleeping on this, I came up with a pretty obvious solution: use GD.PrintErr here to output the error message in red. That way it is noticeable, but will not crash the game.

In general I agree with you that it would be nice to throw an exception if you call a method with bogus data. However, games are a case where you want to avoid crashing much more than in other software. We already have places in the code that get a serious error, but just print that and continue, because it's much better if some part of the game doesn't work than making the game crash on the player.

If it helps you think about this as GUI specific code, then why not rename this to explicitly include the fact that this uses elapsed time to move the bar? That way it is obvious from the name as well that this needs a real elapsed time to work.

File: src/gui_common/GUICommon.cs (hunk 6 above)
Comment (hhyyrylainen) [reply src/gui_common/GUICommon.cs:4]: I like the fact that in actual code body you aren't allowed to use the full name to refer to things, I think that unnecessarily makes the code harder to read.

File: src/gui_common/GUICommon.cs (hunk 4 above)
Comment (adQuid) [reply src/gui_common/GUICommon.cs]: Well while you were sleeping I tried out removing delta from the function altogether: https://github.com/Revolutionary-Games/Thrive/pull/2333/files#diff-d5f5074b2176ba208d7d0381045c36e02b673dd709eb00647a93e9187d15aae9R66

I'm happy to compromise with the PrintErr, but now that I've done it I kind of like the speed param. Let me know what you think.

Comment (hhyyrylainen) [reply src/gui_common/GUICommon.cs]: I think it's better to have the delta in the generic place, I reckon that it is way more common to use it from GUI code that does now the actual delta, meaning that the logic for going to delta to the speed parameter gets duplicated everywhere, which is not good. The reason why delta is used in the first place is so that the bar move speed is tied to real time instead of framerate, as otherwise at 400 FPS vs 60 FPS the GUI animations will be out of wack.

File: src/microbe_stage/MicrobeHUD.cs (hunk 7 above)
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeHUD.cs:793]: In playtesting this part doesn't look good. It seems that the bar smoothing also doesn't work that well...

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Here's a video showing what I experienced: https://youtu.be/9o9QHS9o6os

File: src/microbe_stage/MicrobeHUD.cs (hunk 7 above)
Comment (adQuid) [reply src/microbe_stage/MicrobeHUD.cs:793]: yeah, that's an unfortunate side effect of trying to render microbes with low atp without flickering. I'll see if there's anything I can do about it.

Comment (adQuid) [reply src/microbe_stage/MicrobeHUD.cs]: I think I've figured out a functional, if not very elegant, solution.

File: src/microbe_stage/MicrobeHUD.cs [hunk 8]
```diff
@@ -779,19 +783,25 @@ private void UpdateATP(float delta)
...
 
-            atpAmount = Mathf.Ceil(compounds.GetCompoundAmount(atp));
-            capacity = compounds.Capacity;
+            atpAmount = compounds.GetCompoundAmount(atp);
+            maxATP = compounds.Capacity;
+        }
+
+        atpBar.MaxValue = maxATP * 10.0f;
+
+        if (maxATP - atpAmount < maxATP / 20.0f)
```
Comment (Kasterisk) [inline src/microbe_stage/MicrobeHUD.cs:798]: Not very obvious what's this for, would be nice to have a small explanation comment here.

**Review by Kasterisk — CHANGES_REQUESTED** [review]

**Comment by Kasterisk** [comment]
After playtesting I think this fully fixes #1658 (at least for the ATP bar, I don't see the HP bar being problematic) but at the cost of the bar being a bit spastic which kind of brings back #1065. Regardless I think this is a necessary tradeoff, it's very difficult to get the atp bar to be stable anyways. At the very least the bar is now visualizing the correct amount of atp than occasionally being stuck, which is probably preferable for many.

File: src/microbe_stage/MicrobeHUD.cs [hunk 9]
```diff
@@ -779,19 +783,25 @@ private void UpdateATP(float delta)
...
+        {
+            atpAmount = maxATP;
         }
 
-        atpBar.MaxValue = capacity;
-        atpBar.Value = MathUtils.Lerp((float)atpBar.Value, atpAmount, 3.0f * delta, 0.1f);
-        atpLabel.Text = StringUtils.FormatNumber(atpAmount) + " / " + StringUtils.FormatNumber(capacity);
+        GUICommon.SmoothlyUpdateBar(atpBar, atpAmount * 10.0f, delta);
+        atpLabel.Text = StringUtils.FormatNumber(atpAmount) + " / " + StringUtils.FormatNumber(maxATP);
```
Comment (Kasterisk) [inline src/microbe_stage/MicrobeHUD.cs:804]: Just thought about this, I think we could just round `atpAmount` here so the value text is at least readable to workaround the atp value flickering.

Comment (adQuid) [reply src/microbe_stage/MicrobeHUD.cs:805]: In an earlier version of this branch the value was being rounded to the nearest 0.5, but that results in choppy changes when the microbe has very low max ATP.

Comment (Kasterisk) [reply src/microbe_stage/MicrobeHUD.cs:805]: I mean just the `atpAmount` inside `StringUtils.FormatNumber(atpAmount)` which is just used for displaying the numbers in the HUD, the default `atpAmount` shouldn't be rounded.

Comment (adQuid) [reply src/microbe_stage/MicrobeHUD.cs]: Try it now; I think you'll like it

Comment (Kasterisk) [reply src/microbe_stage/MicrobeHUD.cs]: Sorry for the late reply just tested now. Unfortunately it doesn't fix the text flickers, it still does this:
atp
(It actually flickers much faster ingame at 60fps)

Comment (adQuid) [reply src/microbe_stage/MicrobeHUD.cs]: strange, let me try to reproduce.

**Review by Kasterisk — APPROVED** [review]
Still a bit of flickering but I think this is good enough, other than that specific thing it looks great.

File: src/general/StringUtils.cs [hunk 10]
```diff
@@ -41,4 +41,9 @@ public static string FormatNumber(this double number, bool withSuffix = true)
 
         return number.ToString("0.#", CultureInfo.CurrentCulture);
     }
+
+    public static string FormatDecimal(this double number)
```
Comment (hhyyrylainen) [inline src/general/StringUtils.cs:45]: Isn't this specifically for formatting with just one decimal place? I think the name should reflect that.

Comment (adQuid) [reply src/general/StringUtils.cs]: Went ahead and made the function more generic.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

File: src/general/StringUtils.cs [hunk 11]
```diff
@@ -41,4 +41,15 @@ public static string FormatNumber(this double number, bool withSuffix = true)
 
         return number.ToString("0.#", CultureInfo.CurrentCulture);
     }
+
+    public static string FormatDecimal(this double number, int decimalPlaces)
+    {
+        var format = "0.";
+        for (var i = 0; i < decimalPlaces; i++)
+        {
+            format += "0";
```
[the remark this answers is not in the document]
Comment (adQuid) [reply src/general/StringUtils.cs:50]: The problem isn't chopping off extra digits, it's always printing the ".0" at the end. If you have a more elegant way to generate this format string I'm all ears.

[the remark this answers is not in the document]
Comment (hhyyrylainen) [reply src/general/StringUtils.cs:50]: I think that maybe this method should *not* exist. It's hard to avoid a string object creation without a lookup table.
`F2` is a format string used elsewhere in the code base already. I just don't see how this general helper method could be made.

File: src/microbe_stage/MicrobeHUD.cs [hunk 12]
```diff
@@ -806,16 +818,16 @@ private void UpdateHealth(float delta)
             return;
 
         var hp = 0.0f;
-        var maxHP = 100.0f;
 
+        // Update to the player's current HP, unless the player is dead
         if (stage.Player != null)
```
Comment (FuJa0815) [inline src/microbe_stage/MicrobeHUD.cs:823]:
```suggestion
        if (stage.Player?.Dead == false)
```

File: src/microbe_stage/MicrobeHUD.cs [hunk 13]
```diff
@@ -779,19 +783,27 @@ private void UpdateATP(float delta)
...
+        {
+            atpAmount = maxATP;
         }
 
-        atpBar.MaxValue = capacity;
-        atpBar.Value = MathUtils.Lerp((float)atpBar.Value, atpAmount, 3.0f * delta, 0.1f);
-        atpLabel.Text = StringUtils.FormatNumber(atpAmount) + " / " + StringUtils.FormatNumber(capacity);
+        GUICommon.SmoothlyUpdateBar(atpBar, atpAmount * 10.0f, delta);
+        atpLabel.Text = atpAmount.ToString("F1", CultureInfo.CurrentCulture) + " / "
+            + maxATP.ToString("F1", CultureInfo.CurrentCulture);
```
Comment (FuJa0815) [inline src/microbe_stage/MicrobeHUD.cs:806]: why does ATP use `.ToString("F1"` but HP uses `StringUtils.FormatNumber`?

**Review by FuJa0815 — CHANGES_REQUESTED** [review]

File: src/microbe_stage/MicrobeHUD.cs (hunk 13 above)
Comment (adQuid) [reply src/microbe_stage/MicrobeHUD.cs:806]: Because ATP can be fractional, while HP can't. Using F1 would add a meaningless ".0" to all HP numbers.

File: src/microbe_stage/MicrobeHUD.cs (hunk 12 above)
Comment (adQuid) [reply src/microbe_stage/MicrobeHUD.cs:823]: I committed this suggestion, then thought again and reverted it. The comment was the misleading part; it's really checking if the player is already disposed, since the original point of this PR is to still show the maxHP. I've kept the code the same and updated the comment.

File: src/microbe_stage/MicrobeHUD.cs (hunk 13 above)
Comment (hhyyrylainen) [reply src/microbe_stage/MicrobeHUD.cs:806]: What about `F0` then? (I think that might work)

File: src/microbe_stage/MicrobeHUD.cs [hunk 14]
```diff
@@ -779,19 +783,27 @@ private void UpdateATP(float delta)
             return;
 
         var atpAmount = 0.0f;
-        var capacity = 4.0f;
 
+        // Update to the player's current ATP, unless the player is already disposed
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeHUD.cs:787]: I'd replace "disposed" with doesn't exist currently, as this comment may be misleading if when the player is disposed is changed.

File: src/microbe_stage/MicrobeHUD.cs [hunk 15]
```diff
@@ -806,16 +818,16 @@ private void UpdateHealth(float delta)
             return;
 
         var hp = 0.0f;
-        var maxHP = 100.0f;
 
+        // Update to the player's current HP, unless the player is already disposed
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeHUD.cs:822]: Same here

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Except that one comment this is good to go in my opinion.

**Review by hhyyrylainen — APPROVED** [review]
