### PR TITLE
Rigidity slider fix

### LINKED ISSUE #4150: Rigidity slider breaks when trying to move it at exactly 0 MP
It looks like rigidity slider does a divide by zero to end up with ridiculously wrong numbers when it tries to move when there's exactly 0 MP left. This can be triggered with a very specific MP cost multiplier to be able to place parts to reach 0 MP and then trying to move the rigidity slider.

https://community.revolutionarygamesstudio.com/t/membrane-rigidity-visual-bug/6059

Video: https://youtu.be/9c4ekW5QNI8

### PR DESCRIPTION
**Pull request by Patryk26g**
**Brief Description of What This PR Does**

Hopefully this fixes the rigidity slider issue. The problem was mainly with the division by 0.

**Related Issues**

Closes #4150

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 1]
```diff
@@ -1281,6 +1281,12 @@ public void OnRigidityChanged(int desiredRigidity)
             return;
         }
 
+        if (Editor.MutationPoints == 0 && cost == 0)
```
Comment (dligr) [inline src/microbe_stage/editor/CellEditorComponent.cs:1284]: I think that it would be good to add a comment here clarifying why this check is needed (if I get it right, it handles the corner case of the cost being rounded to zero, while adding up with other costs in such a way that MP ends up at -1)

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 2]
```diff
@@ -1281,6 +1281,14 @@ public void OnRigidityChanged(int desiredRigidity)
             return;
         }
 
+        // Make sure that if there are no mutation points the player cannot drag the slider
+        // when the cost is rounded to zero
+        if (Editor.MutationPoints == 0 && cost == 0)
```
Comment (dligr) [inline src/microbe_stage/editor/CellEditorComponent.cs:1286]: I noticed that when playing with the mutation cost of 1.9, dragging the rigidity slider might bring the MP down to -1. So, I think that this check should be updated to be able to handle any mutation cost. Something like `Editor.MutationPoints < cost + 1 && CostMultiplier % 1 != 0` should probably work (the second part checking if the number is non-integer and might have rounding issues).

Comment (Patryk26g) [reply src/microbe_stage/editor/CellEditorComponent.cs]: Went with a different approch, tested it and couldn't find any more issues

**Comment by dligr** [comment]
I have found a new corner case:
1. Set mutation cost at 1.9
2. Place two cytoplasms
3. Drag the rigidity slider to get the MP to 7
4. Skip two slider steps with a mouse press; the MP ends up at -1

It seems like the issue is that the step cutoff calculations don't take into account the extra 1 that may be added due to rounding

**Comment by Patryk26g** [comment]
I think this corner case is working properly now

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 3]
```diff
@@ -1261,18 +1261,20 @@ public void OnRigidityChanged(int desiredRigidity)
...
             CostMultiplier = CostMultiplier,
         };
 
-        var cost = Editor.WhatWouldActionsCost(new[] { data });
+        // In some cases "theoreticalCost" might get rounded improperly
+        var theoreticalCost = Editor.WhatWouldActionsCost(new[] { data });
+        var cost = (int)Math.Ceiling(Math.Ceiling(theoreticalCost / costPerStep) * costPerStep);
 
-        if (cost > Editor.MutationPoints)
+        if (cost > Editor.MutationPoints && Editor.MutationPoints != 0)
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:1275]: I think adding a comment here as well explaining that the mutation points being zero corner case is handled below.

BTW unrelated to this exact change, but what would you expect to happen once mutation points are converted to floats? That's a stalled PR and a pretty long-wanted fix for the code architecture.

**Comment by dligr** [comment]
I have found another corner case:
1. Set mutation cost at 0.2
2. Get to editor
3. Place some hydrogenases to get MP to 1
4. Move the rigidity slider three steps and it becomes immovable

File: src/microbe_stage/editor/CellEditorComponent.cs (hunk 3 above)
Comment (Patryk26g) [reply src/microbe_stage/editor/CellEditorComponent.cs:1276]: That's hard to tell but I guess the slider code would need some refactoring

Comment (hhyyrylainen) [reply src/microbe_stage/editor/CellEditorComponent.cs:1276]: That's about what I expected... Hopefully this bugfix doesn't make that eventual work harder.

**Comment by Patryk26g** [comment]
> The only issue I could find now is that when choosing rigidity though clicking while having low enough MP, there might be more steps cut off than needed. For example, with the MP cost modifier of 1.9:
> 
> 1. Switch to any membrane type
> 2. Move rigidity one step left
> 3. Click somewhere on the right part of the slider
> 
> The slider's value would then be one step away from the right value due to excessive cut off

Well that seems like a really rare case and not that problematic. I think that in order to cover this one I would actually need to rewrite the whole function from scratch because I don't see any other solution

**Review by hhyyrylainen — APPROVED** [review]
This fixes the primary bug but as @dligr found out this leaves 1 or 2 MP when trying to move too far in one step, which is a pretty noticeable bug when playing with the slider.

As this has been open for a while and fixes the game locking up, I'll merge this but open a follow up issue.

**Comment by hhyyrylainen** [comment]
Opened the new issue: https://github.com/Revolutionary-Games/Thrive/issues/5821
