### PR TITLE
5243 positioning controller tab movement prompts

### LINKED ISSUE #5243: Controller tab movement prompts are positioned incorrectly now
Probably a regression from making the buttons centered. Probably just a case where space expanding nodes are placed on the wrong side of the indicators.

### PR DESCRIPTION
**Pull request by proudnhello**
**Brief Description of What This PR Does**

The goal of this PR is to fix issue 5243, in which the tab buttons prompts on the options menu were too far away from the actual tab menu. I discovered this happened due to the minimum size of the TabButtons node was set to 1200px and the ButtonContainer node the TabButtons script uses was set to expand. This resulted in the IndicatorContainer nodes being pushed out to the edge of the screen. In order to fix this, I set the minimum size of TabButtons to 850px instead. By the looks of things, this was originally done because the additional size of the IndicatorContainers will cause the tab buttons to wrap without a larger min size of at least 813px. Changing this did not seem to break any resolutions I tested, and I thought it looked best at 850px.

**Related Issues**

fixes #5243 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
> By the looks of things, this was originally done because the additional size of the IndicatorContainers will cause the tab buttons to wrap without a larger min size of at least 813px. Changing this did not seem to break any resolutions I tested, and I thought it looked best at 850px.

It sounds like you didn't test different translations, right? Some translations have really long text so that was also a factor which impacted here.

I was kind of hoping that we wouldn't need to just endlessly tweak a minimum size and instead we could get some other kind of solution in place... (let me know if you have ideas)

But if this works well enough with all languages, then we can consider merging this as an improvement even if this isn't like a final fix.

**Comment by proudnhello** [comment]
You're right, other languages had completely slipped my mind. Checking all the languages, Russian (ru), Dutch (nl), and Bulgarian (bg) have buttons that are too long with 850px. The buttons all still work, but the last one moves wraps to the bottom, which doesn't look good. Doing a bit more fiddling, Russian has the longest buttons, so for this method to work, we would need to set the minimum size to 950px. This is... better than it was, but the buttons are still kind of floating in the middle of nowhere for basically every language expect those 3. See English as an example below. And, of course, if another longer language gets translated, this only gets worse. I've pushed that to this pr, in case we want to use it while we work on something better,
image

As for a more comprehensive fix, I do have an idea. Forgive me if this is obviously impossible or goes against best practices/the style guide, I think it should be okay, but I am still getting used to the codebase. We could, when the language changes, sum up the real sizes of all of the tabs, then dynamically set the custom minimum size based on that result. Using English as an example, all of its buttons are set to the minimum size of 130, plus the flow container gap of 4 on each side and 8 between each button gets us that the buttons all together take up 690px. Adding in the 63px from each IndicatorContainer/AlternitivePadding results in a total size of 816px. So, we would set the minimum size to that to get the button indicators next to the buttons (plus maybe a constant 50px for a bit of extra padding). Russian works the same way, except one button has a width of 227px and another has a width of 181px, resulting in a total space of 964px. My calculations do seem slightly off, in game I get the tabs are formatted correctly at slightly smaller custom minimum than the math would suggest, but if this seems like a viable solution, I am sure I could figure out why that is.

If that sounds like a reasonable approach, it would probably be implemented in OptionsMenu. While it could be done by linking TabButtons and Settings somehow, I think that would only be worthwhile if this was a problem in other TabButtons, which doesn't appear to be the case based on the issue. I would add a function called something like UpdateTabButtonsSize and call it in OnLanguageSettingSelected, OnReasetLanguagePressed, OpenFromMainMenu, and OpenFromInGame. I would prefer to only call it during _Ready and when the language changes, instead of also when it is opened, but I believe that control nodes do not have sizes assigned to them until after they are ready, so it would have to be set at some other time. Opening seems like a reasonable time to do that, as it should be quite quick. 

Let me know if that sounds like a reasonable solution, or if there's some obvious consideration/style guide point I have missed.

**Comment by hhyyrylainen** [comment]
> As for a more comprehensive fix, I do have an idea. Forgive me if this is obviously impossible or goes against best practices/the style guide, I think it should be okay, but I am still getting used to the codebase.

It does seem like maybe this is the most reasonable option, because Godot Controls might just be missing the thing making this possible otherwise. And for example the max width option suggestion has been open for years and doesn't seem likely to be added. I'm not saying that would allow fixing this case but that does highlight why we might just need to do a custom hack to get the GUI to behave.

> While it could be done by linking TabButtons and Settings somehow, I think that would only be worthwhile if this was a problem in other TabButtons, which doesn't appear to be the case based on the issue.

Theoretically I think any tab bar can be impacted by this issue. So I think the calculation fix should be made as a general component or a helper class that can be used wherever it is necessary.

> instead of also when it is opened, but I believe that control nodes do not have sizes assigned to them until after they are ready, so it would have to be set at some other time. Opening seems like a reasonable time to do that, as it should be quite quick.

I think all child nodes should have their _Ready called before the parent node's _Ready is called, so theoretically it should work. But I'm also a fan of defensive programming so just quickly refreshing the min width on settings opening seems also like a fine solution to me.

**Comment by proudnhello** [comment]
I added a new function to TabButtons called SetCustomMinimumSize, which calculates and then sets an appropriate minimum size using the method discussed. I also call it in the four places in OptionsMenu mentioned as well, though I had to use a call deferred callback when the language has been changed. I'm not entirely sure what causes it, but it seems as though either the language change or the buttons size being updated is delayed until later in the frame, so it would calculate the size for the current language. For example, if I swapped from Dutch to English, the new function would be called at the end of OnLanguageSettingSelected after the language was updated, but it would still find the button sizes for Dutch. I know callbacks are not preferred, but only running when the language is changed should be uncommon enough to not affect performance. Still, if you have any ideas for a better solution, I'd love to hear them.

File: src/gui_common/menus/OptionsMenu.cs [hunk 1]
```diff
@@ -2835,6 +2841,11 @@ private void OnLanguageSettingSelected(int item)
         Settings.Instance.ApplyLanguageSettings();
         UpdateResetSaveButtonState();
         UpdateCurrentLanguageProgress();
+
+        // Calculate and set the minimum size of the tab buttons, as their size may have changed with the new language.
+        // Has to use a callback as the buttons do not finish resizing until later in the frame.
+        // Not entirely sure why, to be honest, but this only runs when the language changes, so it should be fine
+        Callable.From(tabButtons.SetCustomMinimumSize).CallDeferred();
```
Comment (hhyyrylainen) [inline src/gui_common/menus/OptionsMenu.cs]: We have a custom `Invoke` system which we always prefer over the godot's call deferred. So could you swap this over to that? Depending on if the callback can happen this frame or the next you should either use `Invoke.Instance.Perform` or `Queue`.

I think it is fine to do this kind of deferred update here as it is likely that the translation change happens before all of the Controls have applied their new text. So it makes sense to me to do it with a delay.

One more thing I just noticed when writing this is that this should be unnecessary? Because the language change method should be what triggers the size to change, but you've put this code into the GUI callback for the languages list. Which means that this isn't always guaranteed to trigger if the language changes for other reasons than the GUI control. Putting this code just in the `OnTranslationsChanged` method should make it so that this code doesn't need to be in two places.

File: src/gui_common/TabButtons.cs [hunk 2]
```diff
@@ -241,6 +241,36 @@ public bool OnPreviousSecondaryTab()
...
+    {
+        // Start by adding together the widths of all the tab buttons
+        float newCustomMinimum = 0.0f;
+        foreach (var button in tabButtons)
+        {
+            newCustomMinimum += button.Size.X;
+        }
+
+        // Find the distance between each button (should get 0 if the constant doesn't exist, no need to check)
+        var separationBetweenButtons = tabButtonsContainer.GetThemeConstant("h_separation");
```
Comment (hhyyrylainen) [inline src/gui_common/TabButtons.cs]: As this takes in a StringName, the StringName should be cached as this otherwise causes an extra allocation each time.

See for example in SpecifiedInputkey how this is used:
```
private StringName? marginLeftName;
```

as to how I recommend avoiding the allocation on this line each time it is called. Though I just noticed that code doesn't Dispose it correctly... I'll fix that but in the meantime check `ChromaticFilter` for how the dispose should be done. But I'd still prefer the approach where the min size is initialized in this method the first time it is needed.

File: src/gui_common/menus/OptionsMenu.cs (hunk 1 above)
Comment (proudnhello) [reply src/gui_common/menus/OptionsMenu.cs]: You're right, OnTranslationChanged is a far more reasonable place to put this, I must have missed it when I was reading through options menu the first time. It's been moved, and I've used the custom Invoke instead.

File: src/gui_common/TabButtons.cs (hunk 2 above)
Comment (proudnhello) [reply src/gui_common/TabButtons.cs]: Fixed that, I now have a private horizontalSeparationStringName (the more reasonable horizontalSeparationName is apparently being used somewhere else and caused an error) which uses the format shown in SpecifiedInputKey to create and assign a StringName. I also added a protected overridden Dispose function to dispose of it like is seen in ChromaticFilter. I nested the if statements to make adding potential future disposed variables easier, and to avoid whoever is making that change needing to notice the and statement.

Comment (hhyyrylainen) [reply src/gui_common/TabButtons.cs]: Where is `horizontalSeparationName` from? I just tried changing your code to use that name and I got no error.
