### PR TITLE
#855 #838 #839 fixes 

### LINKED ISSUE #839: The current patch in the patch map should be highlighted
Right now it looks the same as the other patches. The border colour should be changed to indicate it is the current patch.

### LINKED ISSUE #855: TypeError on turning off the FPS counter
Turning off the FPS counter (with F3) causes this error from JS:
```
[CEF] Uncaught TypeError: Cannot read property 'toFixed' of undefined. 
	In: http://leviathan-local/Data/Scripts/gui/main_menu.mjs (287)
[0821/202150.375489:INFO:CONSOLE(287)] "Uncaught TypeError: Cannot read property 'toFixed' of undefined", source: http://leviathan-local/Data/Scripts/gui/main_menu.mjs (287)
```

### PR DESCRIPTION
**Pull request by Dak2896**
* fixes #839 and fixes #855 
* Current patch is now highlighted
* Toggle fps don't throw any TypeError

### CODE REVIEW

**Comment by Dak2896** [comment]
Should the event for activate freeBuild in GUI be called only if is activated or it's good idea send the value also when it's false?  I thought that by making this we avoid problem as if someone go to menu and start again the game and maybe he keep has the freeeBuild also if he didn't choose it.

File: scripts/gui/microbe_editor.mjs [hunk 1]
```diff
@@ -818,15 +830,14 @@ function processPatchMapData(data){
         element.classList.add("PatchContainer");
         element.style.left = patch.screenCoordinates.x + "px";
         element.style.top = patch.screenCoordinates.y + "px";
-
+        element.id = patch.id;
```
Comment (hhyyrylainen) [inline scripts/gui/microbe_editor.mjs]: I think some kind of prefix should be added in order to avoid conflicts, as currently I think this is just a plain number like 0 and might later cause issues. Something like `"patchMapPatch_" + patch.id`

File: scripts/gui/microbe_editor.mjs [hunk 2]
```diff
@@ -921,15 +935,16 @@ function moveToPatchClicked(){
     if(!patchMoveAllowed(selectedPatch.id))
         return;
 
+    // Switch patch in which we are
+    document.getElementById(currentPatchId).classList.remove("Current");
     currentPatchId = selectedPatch.id;
-
+    document.getElementById(currentPatchId).classList.add("Current");
```
Comment (hhyyrylainen) [inline scripts/gui/microbe_editor.mjs]: Adding a blank line after this one would be nice.

File: scripts/microbe_stage/microbe_editor/microbe_editor.as [hunk 3]
```diff
@@ -107,6 +105,13 @@ class MicrobeEditor{
             freeBuilding = false;
         }
 
+        // Sent freebuild value to GUI
+        GenericEvent@ freebuildEvent = GenericEvent("MicrobeEditorFreeBuildToggle");
```
Comment (hhyyrylainen) [inline scripts/microbe_stage/microbe_editor/microbe_editor.as]: I think a more suitable name for the event would be "MicrobeEditorFreeBuildStatus"

File: scripts/gui/microbe_editor.mjs [hunk 4]
```diff
@@ -921,15 +935,16 @@ function moveToPatchClicked(){
     if(!patchMoveAllowed(selectedPatch.id))
```
Comment (GatoCreador887) [inline scripts/gui/microbe_editor.mjs]: `patchMoveAllowed` needs a check for freebuild, otherwise it will return false and prevent the move.
In `patchMoveAllowed`:
```
    if(currentPatchId == targetId){
        return false;
    }

    // Freebuild, allow movement to anywhere
    if(!limitMovesPerSession)
        return true;
```

Comment (Dak2896) [reply scripts/gui/microbe_editor.mjs]: If `limitMovesPerSession` is set to false then in `patchMoveAllowed()` 
this statment is never invoked:
`if(limitMovesPerSession)
        alreadyMovedThisSession = currentPatchId != patchIdOnEnter;`

as consequence  `alreadyMovedThisSession ` keep stay to default value `false` and so we can keep moving.

I'm gonna test it again, maybe i miss something and you're right.

Comment (hhyyrylainen) [reply scripts/gui/microbe_editor.mjs]: My undestanding is that @Dak2896 is right. At least that's how I wanted to write the logic and make it easy to disable the restriction on number of moves.

Comment (GatoCreador887) [reply scripts/gui/microbe_editor.mjs]: I made my own version (before realizing it had already been done). It didn't work until I added that check. Just trying to help.

**Comment by Dak2896** [comment]
At this point i also thing would be better change the colour with green of current patch, what do you think?
image

image

**Comment by hhyyrylainen** [comment]
The second screenshot is exactly what I want.

**Comment by Dak2896** [comment]
And one last thing, in order to apply the border i moved the id from `patchContainer` element to the `inner` span one, do you think it's better keep it on the main container and make a query selector for span child or it's ok move it.

**Comment by hhyyrylainen** [comment]
Why did it need to be moved? If it overall makes the code easier to understand, then it is a good change.

**Comment by Dak2896** [comment]
I've moved it because current class need to be added to the element that have the id, i just upload the code so you can see the difference.

**Comment by Dak2896** [comment]
There are more changes needed here?

**Comment by hhyyrylainen** [comment]
I tested this again and to me it looks like the size of the Active border is different than the normal one. Causing the selected patch to shift by a few pixels when you move to it.

File: scripts/microbe_stage/microbe_editor/microbe_editor.as (hunk 3 above)
Comment (hhyyrylainen) [reply scripts/microbe_stage/microbe_editor/microbe_editor.as]: This hasn't been renamed yet, right? (just to make sure I'm not looking at some old thing).

**Comment by Dak2896** [comment]
I fix the style in order to remove deleted lines or new ones added, the last request change was the name of event that is set to `MicrobeEditorFreeBuildStatus`
