### PR TITLE
Fix not detecting colony mucocyst state

### LINKED ISSUE #6474: Cannot turn off mucocyst shield in multicellular if main cell doesn't have it but others do
Seems like there's a cell colony state handling bug where if your other cells except the first one have the mucocyst shield ability, but your main cell doesn't, it isn't possible to turn off the mucocyst shield.

https://www.youtube.com/watch?v=8wWmwJaU0hM

Original report: https://discord.com/channels/228300288023461893/958598553389903913/1440072393665150976 

This is probably an oversight in the ability buttons handling code not checking the other colony members before deciding whether it needs to turn off or on the mucocyst shield so it always just tries to turn it on.

### PR DESCRIPTION
**Pull request by CI09**
**Brief Description of What This PR Does**

Fixes the case where game would not consider colony state when choosing to activate or deactivate mucocyst on player input. Also added missing applying of the state to the colony

**Related Issues**

Closes #6474

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/microbe_stage/components/MicrobeControl.cs [hunk 1]
```diff
@@ -387,20 +387,27 @@ public static void SetMucocystState(this ref MicrobeControl control,
...
                         mucilageCompound));
+
+            if (entity == colony.Leader)
+                SetStateColonyAware(ref control, entity, stateToSet);
         }
 
         if (organelleInfo.MucocystCount < 1)
             return;
 
+        control.State = stateToSet;
```
Comment (hhyyrylainen) [inline src/microbe_stage/components/MicrobeControl.cs]: Why is this here now? This doesn't now take the activation cost into account, I don't think.

**Comment by hhyyrylainen** [comment]
Upon testing this seemed fine initially though it always caused a message about not having enough mucilage when my main cell didn't have it. But when I added a slime jet to my main cell, it also now suddenly got the ability to make a shield, even though it shouldn't be able to do so (due to missing the upgrade).

File: src/microbe_stage/components/MicrobeControl.cs [hunk 2]
```diff
@@ -394,8 +394,11 @@ public static void SetMucocystState(this ref MicrobeControl control,
             // TODO: is it a good idea to allocate a delegate here?
             colony.PerformForOtherColonyMembersThanLeader(m =>
                 m.Get<MicrobeControl>()
-                    .SetMucocystState(ref m.Get<OrganelleContainer>(), ref m.Get<CompoundStorage>(), m, state,
+                    .SetMucocystState(ref m.Get<OrganelleContainer>(), ref m.Get<CompoundStorage>(), in m, state,
                         mucilageCompound));
+
+            if (entity == colony.Leader)
+                SetStateColonyAware(ref control, entity, state ? MicrobeState.MucocystShield : MicrobeState.Normal);
```
Comment (hhyyrylainen) [inline src/microbe_stage/components/MicrobeControl.cs]: Upon testing, I don't think this change actually makes sense because this overrides mucocyst amount checks in the colony members...

**Review by hhyyrylainen — APPROVED** [review]
I refactored this quite a bit, but I think this is now fine with the problem gone with non-mucocyst capable cells (or cells without enough mucilage) being able to enter mucocyst state.
