### PR TITLE
Barrier and pause fix

### LINKED ISSUE #4996: Find out why SimpleBarrier seems to cause process lock up
It seems to happen even though the threads don't even get stuck in anything related to it, but suddenly when switching to the default Barrier class that lock up goes away. I can't figure this out now so I'm opening an issue for this instead.

### LINKED ISSUE #5728: Find a proper Pause() CPU instruction equivalent for Arm in C#
`X86Base.Pause();` is not usable on ARM so we need some alternative. I tried looking briefly for one but couldn't find any relevant ones.

### PR DESCRIPTION
**Pull request by xfractalino**
**Brief Description of What This PR Does**

This PR addresses #4996 and #5728

It completes the incomplete CPUHelpers.HyperThreadPause() and fixes the SimpleBarrier implementation.

I tested the SimpleBarrier with a few tests, and it seems to work. It would have to be tested in-game replacing the system Barrier. Also, I can't test HyperThreadPause on ARM since I don't have access to it, so it might have to be tested by somebody who can.

This is my last PR on my fork, then I'll switch to the main repo.

**Related Issues**

closes #4996 
closes #5728

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/engine/SimpleBarrier.cs [hunk 1]
```diff
@@ -1,124 +1,44 @@
...
 public class SimpleBarrier
 {
-    private const int BUSY_LOOP_COUNT = 25;
-    private const int READ_TESTS_IN_A_ROW = 5;
-
     private readonly int threadCount;
 
-    private volatile int waitingThreads;
+    // local phase
+    private volatile int currentPhase = 0;
```
Comment (hhyyrylainen) [inline src/engine/SimpleBarrier.cs]: Can this use `uint` or how does this handle wrapping around?

Comment (xfractalino) [reply src/engine/SimpleBarrier.cs]: I just tested it, and it wraps to -int.MaxInt, and keeps working

**Comment by hhyyrylainen** [comment]
`src/general/utils/CPUHelpers.cs:12 Name 'IsARM' does not match rule 'Static readonly fields (private)'. Suggested name is 'IsArm'. type: InconsistentNaming` 

You'll need to add ARM to the allowed list of abbreviations in the resharper config file.

**Comment by xfractalino** [comment]
It still reports the same error. Do I need to add the rule somewhere else?

File: Thrive.sln.DotSettings [hunk 2]
```diff
@@ -520,6 +520,7 @@
 	<s:String x:Key="/Default/CodeStyle/Naming/CSharpNaming/Abbreviations/=AABB/@EntryIndexedValue">AABB</s:String>
 	<s:String x:Key="/Default/CodeStyle/Naming/CSharpNaming/Abbreviations/=AI/@EntryIndexedValue">AI</s:String>
 	<s:String x:Key="/Default/CodeStyle/Naming/CSharpNaming/Abbreviations/=API/@EntryIndexedValue">API</s:String>
+    <s:String x:Key="/Default/CodeStyle/Naming/CSharpNaming/Abbreviations/=ATP/@EntryIndexedValue">ARM</s:String>
```
Comment (hhyyrylainen) [inline Thrive.sln.DotSettings]: `ATP` on this line should be `ARM`

Comment (xfractalino) [reply Thrive.sln.DotSettings]: Ah, yes... It should. Thanks!

Comment (xfractalino) [reply Thrive.sln.DotSettings]: Still failing, apparently.

Comment (hhyyrylainen) [reply Thrive.sln.DotSettings]: I'll check once I'm done with this investigation: https://discord.com/channels/464846402732687391/465937305849298956/1461357914831716463

Comment (hhyyrylainen) [reply Thrive.sln.DotSettings]: I think this is just some CI caching problem as I don't get the error locally so the abbreviation should be correctly setup.

So I think we can ignore this specific failure.

File: src/general/utils/CPUHelpers.cs [hunk 3]
```diff
@@ -15,17 +18,16 @@ public static void HyperThreadPause()
         {
             X86Base.Pause();
         }
+        else if (IsARM)
+        {
+            // This is almost equivalent to X86's Pause.
+            ArmBase.Yield();
```
[the remark this answers is not in the document]
Comment (xfractalino) [reply src/general/utils/CPUHelpers.cs]: After researching a bit on the bus, it seems like a good idea to use WaitForEvent here. Will push tomorrow.

**Comment by hhyyrylainen** [comment]
There's now an actual style problem that jetbrains detected on this PR (`= 0;` shouldn't be used as an initializer as it is the default).

File: src/engine/SimpleBarrier.cs
Comment (hhyyrylainen) [inline src/engine/SimpleBarrier.cs:1]: This is actually beautiful how simple this is now.

**Review by hhyyrylainen — APPROVED** [review]
I tested and this barrier version does not seem to have any dead locking issues and is ever so slightly faster than the system Barrier implementation in tests.

I'll do a separate PR for switching to using the SimpleBarrier as I think we ought to get some more testing to ensure that it doesn't deadlock like the previous implementation did.
