### PR TITLE
Fix editor storage statistic not taking specialized vacuole into account

### LINKED ISSUE #4496: Fix editor storage statistic not taking specialized vacuole into account
It should at least show the non-specialized storage like it did before. I'm not sure how it should really show the specialized storage amounts.

### PR DESCRIPTION
**Pull request by ender-titan1**
**Brief Description of What This PR Does**

This PR updates the code the organism statistics panel uses to display storage to display the correct capacity

**Related Issues**

Closes #4496 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [X] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/microbe_stage/MicrobeInternalCalculations.cs [hunk 1]
```diff
@@ -36,6 +36,38 @@ public static Vector3 GetOrganelleDirection(OrganelleTemplate organelle)
         return (Hex.AxialToCartesian(new Hex(0, 0)) - Hex.AxialToCartesian(organelle.Position)).Normalized();
     }
 
+    public static float GetNominalCapacityForOrganelle(OrganelleUpgrades? upgrades, OrganelleDefinition definition)
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeInternalCalculations.cs:39]:
```suggestion
    public static float GetNominalCapacityForOrganelle(OrganelleDefinition definition, OrganelleUpgrades? upgrades)
```
I'd prefer the method parameters to be this way around as the definition is the more important parameter, and also upgrades is allowed to be null.

File: src/microbe_stage/editor/CellEditorComponent.GUI.cs [hunk 2]
```diff
@@ -174,9 +175,42 @@ private void UpdateHitpoints(float hp)
         hpLabel.Value = hp;
     }
 
-    private void UpdateStorage(float storage)
+    private void UpdateStorage(float nominalStorage, Dictionary<Compound, float> storage)
     {
-        storageLabel.Value = (float)Math.Round(storage, 1);
+        storageLabel.Value = nominalStorage;
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.GUI.cs:180]: I think the nominal storage value should still be rounded like it was before.

File: src/microbe_stage/editor/CellEditorComponent.GUI.cs [hunk 3]
```diff
@@ -174,9 +175,42 @@ private void UpdateHitpoints(float hp)
...
+
+        var tooltip = ToolTipManager.Instance.GetToolTip("storageDetails", "editor");
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.GUI.cs:182]: This will print an error if it can't find the tooltip. If tooltipLoaded is allowed to be false, you should use GetToolTipIfExists instead.

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 4]
```diff
@@ -1037,9 +1037,33 @@ public float CalculateHitpoints()
...
+    public float GetNominalCapacity()
     {
-        return MicrobeInternalCalculations.CalculateCapacity(editedMicrobeOrganelles);
+        return editedMicrobeOrganelles.Sum(o => MicrobeInternalCalculations
+            .GetNominalCapacityForOrganelle(o.Upgrades, o.Definition));
+    }
+
+    public Dictionary<Compound, float> GetAdditionalCapacities()
+    {
+        var dict = new Dictionary<Compound, float>();
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:1048]:
```suggestion
        var capacities = new Dictionary<Compound, float>();
```

"dict" is not a descriptive variable name.

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 5]
```diff
@@ -1037,9 +1037,33 @@ public float CalculateHitpoints()
...
+
+        foreach (var organelle in editedMicrobeOrganelles)
+        {
+            var capacity = MicrobeInternalCalculations
+                .GetAdditionalCapacityForOrganelle(organelle.Upgrades, organelle.Definition);
+
+            if (capacity.Compound == null)
+                continue;
+
+            if (dict.TryGetValue(capacity.Compound, out var currentCapacity))
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:1058]: Multiline if conditions must use braces.

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 6]
```diff
@@ -1037,9 +1037,33 @@ public float CalculateHitpoints()
...
+                dict[capacity.Compound] = currentCapacity + capacity.Capacity;
+            else
+                dict.Add(capacity.Compound, capacity.Capacity);
+        }
+
+        var nominalCap = GetNominalCapacity();
+        return dict.Select(e => new KeyValuePair<Compound, float>(e.Key, e.Value + nominalCap))
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:1065]: Instead of needing to redo the dictionary you could get the nominal capacity at the start of this method and then in the line 1061 do `dict.Add(capacity.Compound, capacity.Capacity + nominalCap)`

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 7]
```diff
@@ -1037,9 +1037,33 @@ public float CalculateHitpoints()
         return maxHitpoints;
     }
 
-    public float CalculateStorage()
+    public float GetNominalCapacity()
     {
-        return MicrobeInternalCalculations.CalculateCapacity(editedMicrobeOrganelles);
+        return editedMicrobeOrganelles.Sum(o => MicrobeInternalCalculations
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:1042]: I think the internal calculations should still have a method that takes in an enumerable to calculate the nominal capacity, instead of needing to use LINQ here in the editor code.

File: src/microbe_stage/editor/CellEditorComponent.GUI.cs [hunk 8]
```diff
@@ -174,9 +175,42 @@ private void UpdateHitpoints(float hp)
...
+            description.Append(": ");
+            description.Append(entry.Value);
+        }
+
+        storageLabel.RegisterToolTipForControl("storageDetails", "editor");
+
+        if (tooltipLoaded)
+            tooltip!.Description = description.ToString();
+        else
+            GD.PrintErr("Can't update storage tooltip");
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.GUI.cs:213]: The "RegisterToolTipForControl" already fails if tooltip is not loaded, I assume so you should just early exit and print an error on line 183 (instead of storing the info in a bool).

File: src/microbe_stage/MicrobeInternalCalculations.cs [hunk 9]
```diff
@@ -36,6 +36,38 @@ public static Vector3 GetOrganelleDirection(OrganelleTemplate organelle)
...
+        }
+
+        if (definition.Components.Storage == null)
+            return 0;
+
+        return definition.Components.Storage!.Capacity;
+    }
+
+    public static (Compound? Compound, float Capacity)
+        GetAdditionalCapacityForOrganelle(OrganelleUpgrades? upgrades, OrganelleDefinition definition)
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeInternalCalculations.cs:54]: I'd like to see the same argument swap here.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
The approach looks fine to me but I'd like to get some of the specifics reworked a bit to be more consistent with the other places in the code and some logic related to error handling improved a bit.

File: src/microbe_stage/editor/CellEditorComponent.GUI.cs (hunk 3 above)
Comment (hhyyrylainen) [reply src/microbe_stage/editor/CellEditorComponent.GUI.cs:182]: I see later you basically error out if the tooltip is not found, so no reason to swap to GetToolTipIfExists here instead. As it is an error condition to not find the tooltip.

File: src/microbe_stage/editor/CellEditorComponent.cs (hunk 6 above)
Comment (ender-titan1) [reply src/microbe_stage/editor/CellEditorComponent.cs:1065]: Problem with that approach is that if two organelles have specific capacity for the same compound, the nominal capacity will be added twice if I understand the suggestion correctly

Comment (hhyyrylainen) [reply src/microbe_stage/editor/CellEditorComponent.cs:1065]: The TryGetValue returns true *only* when the value exists, so the `Add` call is made only on the first time (when TryGetValue returns false). But feel free to point out if I misunderstood.

Comment (ender-titan1) [reply src/microbe_stage/editor/CellEditorComponent.cs:1065]: Yeah, you're right, my bad

**Comment by buckly90** [comment]
No apparent errors, works fine. I feel like there could be a more elegant solution to presenting varied storage capacity, but this should suffice for now. Good job!

**Review by hhyyrylainen — APPROVED** [review]
I fixed this up a bit by removing two unnecessary places of memory allocation.
