### PR TITLE
Auto evo prediction now shows energy first and population second

### LINKED ISSUE #3845: Modify auto-evo prediction to show total energy first (and population second)
this way players can see their energy gain of their species, this should hopefully reduce people incorrectly interpreting becoming bigger having a negative impact on their population.

https://forum.revolutionarygamesstudio.com/t/redefining-species-success/964

I'd say the display should be "energy (population)", and the tutorial about the prediction should be also updated a bit to make this clear. If there's an icon to be shown it should be for the total energy and not the less important, secondary value of population.

### PR DESCRIPTION
**Pull request by CI09**
**Brief Description of What This PR Does**

This PR makes auto evo prediction in editor show energy first and population second, in brackets.
image
Also renames population label variable to energy label for consistency.

***Tutorial is not yet updated and there might be tooltip necessary perhaps.*** 
Edit: not anymore.

**Related Issues**

Closes #3845 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
> Tutorial is not yet update and there might be tooltip necessary perhaps.

In my opinion the tutorial is an absolute requirement before this can be merged. A tooltip would be really good for existing players to find out what the new change is about, but I don't consider that as absolutely required.

**Comment by CI09** [comment]
Like this `This panel shows a prediction of your future total energy gathered and population. These numbers are from the simulation of auto-evo.`?

**Comment by hhyyrylainen** [comment]
That seems pretty good, tough maybe I'd recommend `This panel shows a prediction of your future total energy gathered (and population in parentheses). These numbers are from the simulation of auto-evo.`

That way it explains the number format as well to avoid any confusion.

**Comment by CI09** [comment]
Ok now just the conflicts left to go... I just don't know how to resolve them. @ender-titan1  already explained me to merge (thanks), but I think I just lack the skill to even do it correctly, so uhh...

**Comment by hhyyrylainen** [comment]
You need an up to date copy of the Thrive main repo master branch locally on your computer. Then you need to either rebase this branch on that or merge master into this branch. How to get that depends on how you've setup your git remotes.

**Comment by CI09** [comment]
I might have messed up my local files. (format_script check)...

**Comment by ender-titan1** [comment]
Try running the localization update script again

**Comment by CI09** [comment]
I merged some fog-of-war translations too, that might be causing the problem.

**Comment by ender-titan1** [comment]
Idk what's happening here, but the best course of action would probably be to delete the locale folder on your local project and grab the newest folder from master, then run the translation update script again.

**Comment by CI09** [comment]
Ok I did some changes, tutorial might need some testing though because I don't know how to trigger auto-evo explaination tutorial. Also tooltip is yet (if) to be implemented.

**Comment by hhyyrylainen** [comment]
That tutorial should trigger automatically the second time you go into the microbe editor (and as long as tutorials are enabled).

**Comment by CI09** [comment]
Okay, it is updated.

**Comment by CI09** [comment]
image

By the way why git shows me changes to margin in .tscn files? Should I avoid them?

**Comment by hhyyrylainen** [comment]
> By the way why git shows me changes to margin in .tscn files? Should I avoid them?

They happen all the time, it's fine to leave them in files you have otherwise modified.

I think the tooltip is a bit weird to have "Energy" capitalized. We don't us the style of capitalizing random words in the game. Also it should clarify that the population number is in parentheses as I think that's a pretty key term to use to guide the player to read the numbers correctly.

**Comment by CI09** [comment]
> I think the tooltip is a bit weird to have "Energy" capitalized.

Yeah, I didn't notice it.

**Comment by CI09** [comment]
image
Other than energy word parentheses I tweaked the sentence a bit.

**Comment by hhyyrylainen** [comment]
Seems pretty fine to me. Do the other numbers also have a tooltip? I think they should also have it as the player might not hover over the first number (only first looking at the other numbers) and then be confused maybe something like "Energy gathered by your species and resulting population (in parentheses)", something like that could work as the tooltip for all the other prediction panel numbers.

**Comment by CI09** [comment]
For some reason the others (best path, etc.) tooltips don't work (they just don't display while hovering above them). I also noticed auto-evo panel tooltip would likely need small update, like this maybe?
`This panel shows the expected total energy gathered and population numbers from auto-evo for the edited species.
Auto-evo runs the population simulation that is the other part (besides your own performance) that affects your population.`

**Comment by hhyyrylainen** [comment]
I think it is a good idea to update that as well. That tooltip could have the info that population is in parentheses. I suspect the other numbers have mouse ignore set to on so that the prediction panel tooltip is easier to see, which I think is fine if that tooltip also properly explains the format of the numbers.

**Comment by CI09** [comment]
`This panel shows the expected total energy gathered and population numbers in parentheses from auto-evo for the edited species.
Auto-evo runs the population simulation that is the other part (besides your own performance) that affects your population.
`

> if that tooltip also properly explains the format of the numbers.

Explaining best/worst patch indicators?

**Comment by hhyyrylainen** [comment]
I guess that could be added but if you have trouble with getting tooltips for them to show up, it's fine to not have them. The players have managed so far without tooltips on those.

**Comment by CI09** [comment]
It would be ready then I think.

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 1]
```diff
@@ -2410,10 +2410,23 @@ private void OnAutoEvoPredictionComplete(PendingAutoEvoPrediction run)
         autoEvoPredictionRunSuccessful = true;
 
         // Set the initial value
-        totalPopulationLabel.ResetInitialValue();
-        totalPopulationLabel.Value = run.PlayerSpeciesOriginal.Population;
+        totalEnergyLabel.ResetInitialValue();
+        totalEnergyLabel.Value = run.PlayerSpeciesOriginal.Population;
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:2414]: Why is the total energy label assigned the value of population here? It seems this is overridden anyway a few lines below this, but it seems pretty silly to set this at all to the wrong value.

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 2]
```diff
@@ -2410,10 +2410,23 @@ private void OnAutoEvoPredictionComplete(PendingAutoEvoPrediction run)
...
+            totalEnergyLabel.Value = newTotalPatchEnergyGathered.TotalEnergyGathered;
+            if (totalEnergyLabelText != null)
+            {
+                totalEnergyLabelText.Text =
+                    @$"{StringUtils.ThreeDigitFormat(
+                        newTotalPatchEnergyGathered.TotalEnergyGathered)} ({newPopulation})";
+            }
+        }
 
         var sorted = results.GetPopulationInPatches(run.PlayerSpeciesNew).OrderByDescending(p => p.Value).ToList();
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:2431]: It seems you didn't modify the best patch and worst patch numbers. They should also be updated to the new format (energy first and then in parentheses the population).

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 3]
```diff
@@ -2410,10 +2410,23 @@ private void OnAutoEvoPredictionComplete(PendingAutoEvoPrediction run)
...
-        totalPopulationLabel.Value = run.PlayerSpeciesOriginal.Population;
+        totalEnergyLabel.ResetInitialValue();
+        totalEnergyLabel.Value = run.PlayerSpeciesOriginal.Population;
 
-        totalPopulationLabel.Value = newPopulation;
+        results.GetPatchEnergyResults(run.PlayerSpeciesNew).TryGetValue(
+            Editor.CurrentPatch, out var newTotalPatchEnergyGathered);
+        var totalEnergyLabelText = totalEnergyLabel.GetNode<Label>(totalEnergyLabel.ValuePath);
+
+        if (newTotalPatchEnergyGathered != null)
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:2420]: The usual style I do is `if (thing.TryGetValue()) ...` and then use null suppression inside the if-statement if necessary.

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 4]
```diff
@@ -2410,10 +2410,23 @@ private void OnAutoEvoPredictionComplete(PendingAutoEvoPrediction run)
...
+        {
+            totalEnergyLabel.Value = newTotalPatchEnergyGathered.TotalEnergyGathered;
+            if (totalEnergyLabelText != null)
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:2423]: Isn't this a label that should be always set so null override should be used here?

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 5]
```diff
@@ -2410,10 +2410,23 @@ private void OnAutoEvoPredictionComplete(PendingAutoEvoPrediction run)
...
+            {
+                totalEnergyLabelText.Text =
+                    @$"{StringUtils.ThreeDigitFormat(
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:2426]: Why is the `@` symbol here? Is it required.

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 6]
```diff
@@ -2410,10 +2410,23 @@ private void OnAutoEvoPredictionComplete(PendingAutoEvoPrediction run)
...
+                        newTotalPatchEnergyGathered.TotalEnergyGathered)} ({newPopulation})";
+            }
+        }
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:2429]: If this if doesn't succeed, then I think an error message should be printed as otherwise the wrong number is displayed in the GUI without further information as to what went wrong.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

File: src/microbe_stage/editor/CellEditorComponent.cs (hunk 5 above)
Comment (CI09) [reply src/microbe_stage/editor/CellEditorComponent.cs:2426]: I had to somehow split the line, @ is used for strings in such case if I am familiar with it enough (Correct me if I'm wrong).

Comment (hhyyrylainen) [reply src/microbe_stage/editor/CellEditorComponent.cs:2426]: I kind of assumed that after writing the comment. I think it would be cleaner to have a temporary variable to hold the result of ThreeDigitFormat call, that way the string interpolation should then fit on a single line.

Comment (CI09) [reply src/microbe_stage/editor/CellEditorComponent.cs:2426]: `string formatted = StringUtils.ThreeDigitFormat(newTotalPatchEnergyGathered.TotalEnergyGathered);`
Can I leave the name `formatted` as is? it barely fits and I can fit just up to 6 characters more there.

File: src/microbe_stage/editor/CellEditorComponent.cs (hunk 6 above)
Comment (CI09) [reply src/microbe_stage/editor/CellEditorComponent.cs:2429]: Does the red text that pops up saying something like "prediction failed" has to display?

Also I noticed the icon is somewhat small when prediction fails:
image

File: src/microbe_stage/editor/CellEditorComponent.cs (hunk 5 above)
Comment (hhyyrylainen) [reply src/microbe_stage/editor/CellEditorComponent.cs:2426]: I'd use `var formatted` here. `formatted` is not the most descriptive variable name but as it is used in such a small scope I think it is fine to compromise on it.

File: src/microbe_stage/editor/CellEditorComponent.cs (hunk 6 above)
Comment (hhyyrylainen) [reply src/microbe_stage/editor/CellEditorComponent.cs:2429]: > Also I noticed the icon is somewhat small when prediction fails:

I think it's been like that since it was added. It's visible for such a small amount of time / rarely in case of failure, that I haven't bothered fixing it as it might be a bit tricky to fix it.

Comment (CI09) [reply src/microbe_stage/editor/CellEditorComponent.cs:2429]: I meant should I make it display when game can't get the gathered energy. I don't know if it displays when auto-evo fails itself, but I don't think I messed up anything to make it not do so.

Comment (hhyyrylainen) [reply src/microbe_stage/editor/CellEditorComponent.cs:2429]: That would be pretty nice. Otherwise we might get a really confusing bug report in the future about the numbers not making sense (and only a log file being able to clarify the situation).

File: src/microbe_stage/editor/CellEditorComponent.cs (hunk 2 above)
Comment (CI09) [reply src/microbe_stage/editor/CellEditorComponent.cs:2431]: Theoretically I made it work, but I don't know if it looks pretty enough:
image

Comment (hhyyrylainen) [reply src/microbe_stage/editor/CellEditorComponent.cs:2431]: >  Edit: also predicted global population is lower than predicted local population, is that normal?

It *might* be a case of population number adjustment being kinder on the player, so the population result has that lower strength applied, but the per patch result might not.

It does look a bit busy so maybe just showing the energy numbers in the best and worst patches would be better? If I remember right that was my original idea I had about this, but I didn't recall that until just now.

Comment (hhyyrylainen) [reply src/microbe_stage/editor/CellEditorComponent.cs:2431]: I guess they could be kept for future reference if they are easy to comment out (you should also comment that they used to be displayed but are now kept just for the potential future use they might have).

**Comment by CI09** [comment]
I was playtesting and when moved away from my origin patch, entered the editor and went into editor tab game crashed with error:
https://pastebin.com/VzA4bDnY](https://pastebin.com/VzA4bDnY)
(sorry if it is poorly visible, lines got wrapped)

**Comment by hhyyrylainen** [comment]
Like the error says, there's is a call to LINQ OrderBy that is told to sort things it doesn't have a clue in `CellEditorComponent.OnAutoEvoPredictionComplete`. The solution is to 1) verify that the list to be sorted contains expected data and not anything weird 2) writing a custom comparer that correctly compares the object types and 3) passing that as the sorter object to the OrderBy (or Sort call if done directly on the data structure). That should switch to using the custom sorter and the exception `Failed to compare two elements in the array. ---> System.ArgumentException: At least one object must implement IComparable.`. Or I guess the other solution is to make the custom types in the collection implement the IComparable interface, this is also done in Thrive in a few places.

**Comment by CI09** [comment]
I didn't fix it yet, do I am gonna mark it as draft (and if anyone is willing, to, they can try to fix it instead; I might do it later).

**Comment by CI09** [comment]
Someone might have to do it for me because I'm just too newbie to do it myself🤔 But take as much time as you want.

**Comment by CI09** [comment]
This is now fixed, there is still a problem which causes indicator to show NaN when moved to a new patch though, but it theoretically could be merged.

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 7]
```diff
@@ -2426,31 +2435,65 @@ private void OnAutoEvoPredictionComplete(PendingAutoEvoPrediction run)
...
+            totalEnergyLabel.Value = newTotalPatchEnergyGathered.TotalEnergyGathered;
+
+            var formatted = StringUtils.ThreeDigitFormat(newTotalPatchEnergyGathered.TotalEnergyGathered);
+            totalEnergyLabelText.Text =
+                $"{formatted} ({newPopulation})";
+        }
+        else
+        {
+            // TODO: Make indicator not show NaN when moved to a new patch
+            GD.PrintErr("Failed to get total patch energy gathered");
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:2456]: Reading this logic, I now realize that there is a problem here: the total energy needs to be the total energy gathered, not any per-patch energy. I'll modify this to calculate the total energy gathered and show it properly.

**Review by hhyyrylainen — APPROVED** [review]
I fixed the small issues with the text left I saw, and the bigger problem of the comparing to previous data not working and showing only the current patch energy info. This should be now all good to go but I'll give @CI09 a chance to check that I didn't accidentally break anything with the rebase/squash or my intended changes.

**Comment by CI09** [comment]
I changed patch and it didn't show me NaN, that's good; game also didn't crash during second editor session, but weird thing was that Energy Gathered tooltip again capitalized Energy, like before:
> image

even though in changed files on github it is not (line 2452 in en.po file I think). May be something on my side - I'm still kinda tripping with git.

**Comment by hhyyrylainen** [comment]
> even though in changed files on github it is not (line 2452 in en.po file I think). May be something on my side - I'm still kinda tripping with git.

I probably broke it somehow in the rebase. I fixed it at least like 3 times, but apparently that wasn't enough.

**Comment by hhyyrylainen** [comment]
Actually, I'm not seeing that. As I did a rebase, you need to force pull to get the latest changes.

**Comment by CI09** [comment]
Okay, I checked out remote branch instead of local branch and everything looks fine to me.
(Maybe I had to checkout remote branch due to me already fetching (without force) and trying to force pull later, I don't know.)
