### PR TITLE
Infinite MP achieved by abusing Duplicate and Delete to cell types

### LINKED ISSUE #3912: Infinite MP achieved by abusing `Duplicate` and `Delete` to cell types
To reproduce:

image

1. Do something

image

2. Duplicate cell type
3. Undo all changes (MP regain, but Stem2 still preserves all changes)
4. Loop 1-3 until you are satisfied
5. Add the final cell and delete the initial one. Now you can delete all medium celltypes
6. You can do anything with 25 MP (or less)

image

(Sorry there isn't any more images because I accidentally triggered #3906 and crashed it.)

### PR DESCRIPTION
**Pull request by Kashnox**
**Brief Description of What This PR Does**

This PR makes duplicating and deleting cell types undoable editor actions so trying to undo actions to regain MP will also undo the duplication, preventing the infinite MP exploit. This approach will also made the multicellular editor more manageable by preventing cases where the action to undo/redo exists on a cell type that's been deleted.

**Related Issues**

closes #3912

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/early_multicellular_stage/editor/EarlyMulticellularEditor.cs [hunk 1]
```diff
@@ -435,14 +435,14 @@ private void OnStartEditingCellType(string name, bool switchTab)
             return;
         }
 
-        var newTypeToEdit = EditedSpecies.CellTypes.First(c => c.TypeName == name);
+        var newTypeToEdit = EditedSpecies.CellTypes.FirstOrDefault(c => c.TypeName == name);
```
Comment (hhyyrylainen) [inline src/early_multicellular_stage/editor/EarlyMulticellularEditor.cs:438]: Why is this change required? If the new type to edit is not found shouldn't the code print an error, clear the cell type to be edited and then skip the rest of the code?

Comment (Kashnox) [reply src/early_multicellular_stage/editor/EarlyMulticellularEditor.cs:438]: Using FirstOrDefault saves us from having to handle a null selection as a special case. If I leave that as just First, it'll throw an exception when we emit OnCellTypeToEditSelected with a null or empty name. Until now, we never actually cleared the selection once it was set, so deleted cell types could still be seen in the editor.

Comment (hhyyrylainen) [reply src/early_multicellular_stage/editor/EarlyMulticellularEditor.cs:438]: See my later comment, I did eventually discover this situation. I'd prefer an explicit check against null at the start of this method which would act as a special value meaning "clear selection" instead of try to pick a cell type like that.

File: src/early_multicellular_stage/editor/EarlyMulticellularEditor.cs [hunk 2]
```diff
@@ -435,14 +435,14 @@ private void OnStartEditingCellType(string name, bool switchTab)
...
 
         // Only reinitialize the editor when required
         if (selectedCellTypeToEdit == null || selectedCellTypeToEdit != newTypeToEdit)
```
Comment (hhyyrylainen) [inline src/early_multicellular_stage/editor/EarlyMulticellularEditor.cs:441]: The check against null edited cell type, doesn't work as intended here anymore. I think the intention was to force initialize the editing if the previous type to be selected was null (which would mean that now this is used), but with being able to call this with a null type now, this code will always trigger even if the previous type was null and the new type was null.

File: src/early_multicellular_stage/editor/EarlyMulticellularEditor.cs [hunk 3]
```diff
@@ -435,14 +435,14 @@ private void OnStartEditingCellType(string name, bool switchTab)
...
         {
             selectedCellTypeToEdit = newTypeToEdit;
 
-            GD.Print("Start editing cell type: ", selectedCellTypeToEdit.TypeName);
+            GD.Print("Start editing cell type: ", selectedCellTypeToEdit?.TypeName);
```
Comment (hhyyrylainen) [inline src/early_multicellular_stage/editor/EarlyMulticellularEditor.cs:445]: Also this message should be vastly different if there's no type selected. A message saying "Start editing cell type: " is going to be really confusing to realize that literally nothing there means that previous cell type to be edited was actually cleared, rather than new edit just began.

File: src/early_multicellular_stage/editor/EarlyMulticellularEditor.cs (hunk 2 above)
Comment (Kashnox) [reply src/early_multicellular_stage/editor/EarlyMulticellularEditor.cs]: Yeah, that's a good point

**Review by hhyyrylainen — APPROVED** [review]
Code is fine enough now as long as https://github.com/Revolutionary-Games/Thrive/issues/3910 gets done before next release.
