### PR TITLE
Fixed remaining cases where mutation code could get auto-evo stuck

### LINKED ISSUE #3373: Auto-evo can get stuck in organelle mutations calculation
Seems like my fix to the islands fixing code can still get stuck in some cases.

My guess as to how this could be fixed: what if the code just doesn’t calculate all of the hexes to move at once? Instead just calculating the move direction for each island organelle separately and move that in the needed direction. That way the symmetry related not knowing how to move code shouldn't be able to happen.

https://community.revolutionarygamesstudio.com/t/auto-evolve-issue/4843/7?u=hhyyrylainen

### PR DESCRIPTION
**Pull request by Leinourdian**
**Brief Description of What This PR Does**

I found two problems that caused the issue. First, the code didn't always recognize island hexes correctly meaning that they could be next to main hexes. Second, the code could calculate the movement path incorrectly if `minSubHex.Q == minSubHex.R`. This PR fixes both of them. I tested this quite a bit and think that auto-evo should now never get stuck.

**Related Issues**

Fixes #3373

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/general/HexLayout.cs [hunk 1]
```diff
@@ -220,7 +220,7 @@ public List<Hex> GetIslandHexes()
         var hexesWithNeighbours = new List<Hex> { initHex };
 
         // These are all of the existing hexes, that if there are no islands will all be visited
-        var shouldBeVisited = existingHexes.Select(p => p.Position).ToList();
+        var shouldBeVisited = ComputeHexCache();
```
Comment (hhyyrylainen) [inline src/general/HexLayout.cs:223]: I think I see. The bug here was that as there are many organelles that are multiple hexes large, this didn't properly loop *all* hexes instead only the first hex of an organelle. Did I understand this right?

**Comment by hhyyrylainen** [comment]
Seeing as the hex island fixing math got very complex looking, I'll just leave the code be, and ask for testing. Though if you could, could you add a line or two of a comment to explain the if and the new calculation there a bit?

File: src/general/HexLayout.cs (hunk 1 above)
Comment (Leinourdian) [reply src/general/HexLayout.cs:223]: Yes, exactly.

**Comment by Leinourdian** [comment]
Sure, I added a comment. The if statement is there because otherwise the path could be too short if minSubHex is (1, 1) for example. Without it the path would become (0, 0) when it needs to be (1, 0) or (0, 1). It basically adds a default direction like your fix but it also works for negative numbers and bigger numbers.

**Comment by buckly90** [comment]
Couldn't get any freezes to happen during loading, so it looks good from my end.

**Review by Kasterisk — APPROVED** [review]
Great fix. No more stuck issue even by changing the mutation constants.
