### PR TITLE
Fixed double counting

### LINKED ISSUE #1387: ATP balance calculation double counts some organelles
Basically I think that there is a bug in: https://github.com/Revolutionary-Games/Thrive/blob/b30560489f7809d3d413b29250ff726e579b7f9e/src/microbe_stage/ProcessSystem.cs#L65

Where we loop each organelle, and then look at all the efficiencies, and count processes in there that the organelle does. This can lead to double counting some processes of the organelle.

So what I think needs to be done is change the loop so that it calculates the efficiency values for each organelle separately. Roughly:

```
        foreach (var organelle in enumerated)
        {
            foreach (var process in organelle.RunnableProcesses)
            {
                 var processData = CalculateProcessMaximumSpeed(process, biome);
            --
```

### PR DESCRIPTION
**Pull request by icedjuro**
Closes #1387

### CODE REVIEW

File: src/microbe_stage/ProcessSystem.cs [hunk 1]
```diff
@@ -64,35 +64,34 @@ public ProcessSystem(Node worldRoot)
```
Comment (hhyyrylainen) [inline src/microbe_stage/ProcessSystem.cs:64]: The above two lines should be removed
```
        // Compute all process efficiencies once
        var efficiencies = ComputeOrganelleProcessEfficiencies(enumerated, biome);
```
because after this change they shouldn't be required.

File: src/microbe_stage/ProcessSystem.cs [hunk 2]
```diff
@@ -64,35 +64,34 @@ public ProcessSystem(Node worldRoot)
...
-            foreach (var efficiencyInfo in efficiencies)
+            foreach (var process in organelle.RunnableProcesses)
             {
-                foreach (var processData in efficiencyInfo.Value.Processes)
+                var processData = CalculateProcessMaximumSpeed(process, biome);
+
+                // Find process inputs and outputs that use/produce ATP
+                // and that are performed by this organelle
+                // and add to totals
+                if (!organelle.Processes.ContainsKey(processData.Process.InternalName))
```
Comment (hhyyrylainen) [inline src/microbe_stage/ProcessSystem.cs:74]: I think that this check can be entirely removed, as it was added originally to guard against counting processes in organelles that don't do them, but now as we calculate the per process data in this loop, this should not be necessary.
