### PR TITLE
Fixed compound graph having the same values in all data points

### LINKED ISSUE #2238: Glucose amount graph doesn't react to the reduced glucose amount
Now that glucose reduction works: https://github.com/Revolutionary-Games/Thrive/pull/2235 it seems that the glucose amount graph is bugged as it doesn't seem to go down.

unknown

### PR DESCRIPTION
**Pull request by Kasterisk**
Was a simple mistake in the code. The compound amount calculation in the compound graph update should now return the correct amount in each recorded snapshots of the current patch.

Fixes #2238

### CODE REVIEW

File: src/microbe_stage/editor/MicrobeEditorGUI.cs [hunk 1]
```diff
@@ -1885,24 +1886,29 @@ private LineChart GetChartForCompound(string compoundName)
     }
 
     private float GetCompoundAmount(Patch patch, string compoundName)
+    {
+        return GetCompoundAmount(patch, patch.Biome, compoundName);
+    }
+
+    private float GetCompoundAmount(Patch patch, BiomeConditions biome, string compoundName)
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditorGUI.cs:1893]: isn't the patch parameter unused here now?

Comment (hhyyrylainen) [reply src/microbe_stage/editor/MicrobeEditorGUI.cs:1893]: never mind, it's used for the chunk amounts. Had to open my editor to see where it was used

**Review by hhyyrylainen — APPROVED** [review]
