### PR TITLE
Prevented quickload crash by checking if quick load was finished before allowing another

### LINKED ISSUE #1728: Prevent quickloading while currently quick loading
as really quickly hitting the quick load key crashes the game.

### PR DESCRIPTION
**Pull request by icedjuro**
Closes #1728

### CODE REVIEW

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
I'd say this is not the right way to go about this. This will prevent *all* loading while the game is paused, right?
Instead the InProgressLoad should have like a static property that is true when loading is currently happening. That just needs a little care to make sure it doesn't get stuck on in case of errors.

File: src/saving/InProgressLoad.cs [hunk 1]
```diff
@@ -13,6 +13,7 @@
 /// </remarks>
 public class InProgressLoad
 {
+    public static bool IsLoading;
```
Comment (hhyyrylainen) [inline src/saving/InProgressLoad.cs:16]: This should not be public. Also add a comment explaining what this is used for.

File: src/saving/SaveHelper.cs [hunk 2]
```diff
@@ -109,8 +109,11 @@ public static void AutoSave(MicrobeEditor state)
     /// <param name="name">The name of the save to load</param>
     public static void LoadSave(string name)
     {
-        GD.Print("Starting load of save: ", name);
-        new InProgressLoad(name).Start();
+        if (!InProgressLoad.IsLoading)
+        {
+            GD.Print("Starting load of save: ", name);
+            new InProgressLoad(name).Start();
+        }
```
Comment (hhyyrylainen) [inline src/saving/SaveHelper.cs:116]: Move this check to quick load handler. I still don't want to completely lock the player out from loading a save from manually.
Also add an else with a print to say why it wasn't loaded.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

File: src/saving/InProgressLoad.cs [hunk 3]
```diff
@@ -49,6 +49,11 @@ public void ReportStatus(bool success, string message, string exception = "")
         this.exception = exception;
     }
 
+    public static bool CheckIsLoading()
```
Comment (hhyyrylainen) [inline src/saving/InProgressLoad.cs]: This should be replaced with a static property. That way there is no need to have a separate backing variable, as long as the set is private so that it isn't unnecessarily exposed.

File: src/saving/InProgressLoad.cs [hunk 4]
```diff
@@ -41,6 +42,11 @@ private enum State
         Finished,
     }
 
+    public static bool CheckIsLoading()
```
Comment (hhyyrylainen) [inline src/saving/InProgressLoad.cs:45]: You should make this a static property instead, that way the backing field is also not needed as long as the setter is private.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

File: src/saving/InProgressLoad.cs [hunk 5]
```diff
@@ -153,6 +155,7 @@ private void Step()
                 if (success)
                 {
                     LoadingScreen.Instance.Hide();
+                    isLoading = false;
```
Comment (hhyyrylainen) [inline src/saving/InProgressLoad.cs:158]: This should be set to false even if this fails. I'd put this line just before the return on line 169.

File: src/saving/InProgressLoad.cs [hunk 6]
```diff
@@ -13,6 +13,7 @@
 /// </remarks>
 public class InProgressLoad
 {
+    public static bool isLoading { get; private set; }
```
Comment (hhyyrylainen) [inline src/saving/InProgressLoad.cs:16]: Add a blank line after this, and also add a documentation comment on this for what this is used for and when it is true.

Comment (hhyyrylainen) [reply src/saving/InProgressLoad.cs:16]: Also as the CI correctly detected this should be named IsLoading

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

File: src/saving/InProgressLoad.cs [hunk 7]
```diff
@@ -13,6 +13,12 @@
 /// </remarks>
 public class InProgressLoad
 {
+    /// <summary>
+    ///   Used to stop quick load starting while a load is in progress already
+    ///   True when a save is currently being loaded
+    /// </summary>
+    public static bool IsLoading{ get; private set; }
```
Comment (hhyyrylainen) [inline src/saving/InProgressLoad.cs:20]: Put the explanation for what it is first, then put the one specific use case description.

**Review by hhyyrylainen — APPROVED** [review]
Fixed problems I still found with this. 
Could you also retest this to make sure no issues popped up?
