### PR TITLE
1863 catch argumentnullexception

### LINKED ISSUE #1863: Make Converter classes also catch ArgumentNullException
as I noticed that the null pointer catch doesn't actually trigger, instead the non existing key read from JObject seems to result in argument null exception instead.

### PR DESCRIPTION
**Pull request by FuJa0815**
**Brief Description of What This PR Does**

`GodotBasisConverter.ReadJson` now also catches `ArgumentNullException`s

**Related Issues**

closes #1863
closes #2064 

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
I think there was another converter where this change should be made...

File: src/saving/serializers/RandomConverter.cs [hunk 1]
```diff
@@ -73,11 +73,9 @@ public override object ReadJson(JsonReader reader, Type objectType, object exist
 
             return random;
         }
-        catch (ArgumentException e)
-        {
-            throw new JsonException("Can't read Random (missing property)", e);
-        }
-        catch (NullReferenceException e)
+        catch (Exception e) when (
+            e is ArgumentException ||
```
Comment (FuJa0815) [inline src/saving/serializers/RandomConverter.cs:77]: I didn't add `ArgumentNullException` here, because rider complained that `this is always false`

**Review by hhyyrylainen — APPROVED** [review]
