### PR TITLE
Fix the spawn system by making it time based (+other fixes)

### LINKED ISSUE #124: Refactor spawn system to be time based
The spawn system seems to be acting a bit wierd with regards to AI entities. It doesn't seem to take number of existing entities into account, which can cause a serious buildup of AI entities around the player and possibly other unwanted effects.

### LINKED ISSUE #1264: Make the spawn system more consistent on respawn
Basically on respawn you get all the stuff, whereas while just swimming around you get very little stuff.
The amount of stuff spawned when swimming around should probably be slightly increased, and the stuff you get when respawning should be *greatly* reduced:
Kuvakaappaus - 2020-05-15 23-25-31

### PR DESCRIPTION
**Pull request by icedjuro**
Closes #124 
Closes #1264

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
The issue is titled "refactor spawn system to be *time* based" so this definitely won't close that, even if this improves the spawn system.

**Comment by hhyyrylainen** [comment]
This needs gameplay testing.

**Comment by buckly90** [comment]
Feels alot better than the old system, spawns feel more consistent! There are only some minor issues I have that are not really game breaking or anything.
* Objects spawn within the player's view, atleast when zoomed out at max.
* While usually pretty consistent, the spawns can sometimes be less consistent and more bunched up or not seen at all. Having the spawn interval be 4 seconds seems to have better remedied this though.

**Comment by hhyyrylainen** [comment]
I suppose further playtesting, perhaps with more team members should be done after the latest changes.

**Comment by buckly90** [comment]
After playing around with the variables, it seems that the following lines and numbers prevents items from spawning within the player's sight.

public const int MICROBE_SPAWN_RADIUS = 170;
public const int CLOUD_SPAWN_RADIUS = 170;
public const float MIN_SPAWN_RADIUS_RATIO = 0.95f;
private float interval = 1.0f;

Would prefer if someone else tried this with these tweaks to get a second opinion on the balance and such.

**Comment by hhyyrylainen** [comment]
I think that increasing the spawn radiuses is not a problem. The despawn logic should handle it correctly as it uses the spawn radius to despawn stuff.

**Comment by hhyyrylainen** [comment]
So @buckly90 is this now balance tested?

File: src/microbe_stage/SpawnSystem.cs [hunk 1]
```diff
@@ -259,23 +257,18 @@ private void SpawnEntities(Vector3 playerPosition, int existing, int spawnsLeftT
                     will fail the second condition, so entities still only
                     spawn within the spawning region.
                     */
-                    float distanceX = (float)random.NextDouble() * spawnType.SpawnRadius -
-                        (float)random.NextDouble() * spawnType.SpawnRadius;
-                    float distanceZ = (float)random.NextDouble() * spawnType.SpawnRadius -
-                        (float)random.NextDouble() * spawnType.SpawnRadius;
+                    float displacementDistance = (float)random.NextDouble() * spawnType.SpawnRadius;
```
Comment (hhyyrylainen) [inline src/microbe_stage/SpawnSystem.cs:260]: I think I added an extension method called NextFloat use that instead of NextDouble here.

File: src/microbe_stage/SpawnSystem.cs [hunk 2]
```diff
@@ -259,23 +257,18 @@ private void SpawnEntities(Vector3 playerPosition, int existing, int spawnsLeftT
...
+                    float displacementRotation = WeightedRandomRotation(playerRotation.y);
+
+                    float distanceX = (float)Math.Sin(displacementRotation) * displacementDistance;
```
Comment (hhyyrylainen) [inline src/microbe_stage/SpawnSystem.cs:263]: Use Mathf to get float math and not double.

File: src/microbe_stage/SpawnSystem.cs [hunk 3]
```diff
@@ -390,6 +383,39 @@ private void ProcessSpawnedEntity(ISpawned entity, Spawner spawnType)
...
 
+    /// <summary>
+    ///   Returns a random rotation (in radians)
+    ///   It is more likely to return a rotation closer to the target rotation than not
+    /// </summary>
+    private float WeightedRandomRotation(float targetRotation)
+    {
+        targetRotation = WithNegativesToNormalRadians(targetRotation);
+
+        float rotation1 = (float)(random.NextDouble() * 2 * Math.PI);
```
Comment (hhyyrylainen) [inline src/microbe_stage/SpawnSystem.cs:394]: use `NextFloat`. `Mathf.PI` might exist

**Comment by buckly90** [comment]
> 
> 
> So @buckly90 is this now balance tested?

Yes sir, seems to work just fine, as I did not encounter any sparse moments that would starve me out. Icedjuro seemed to approve the changes as well, gameplay wise.
