### PR TITLE
Corrected dynamic MP logic to prioritize ReplacesOther action

### LINKED ISSUE #4083: OrganellePlacementAction should detect all hexes when replacing cytoplasms in dynamic MP
Currently only the mouse hex is detected, resulting in incorrect MP prediction.

image

image

The expected value is `12 -> 30`

### PR DESCRIPTION
**Pull request by 84634E1A607A**
Also partly #2900 
Fixes #4083

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Does this fix the upgrades MP cost which can be triggered with:
> That is triggered by adding cilia, modifying the cilia, and then removing it, which should result in 100 MP but doesn't.

?

**Comment by 84634E1A607A** [comment]
Yes.

**Comment by hhyyrylainen** [comment]
I'll actually merge my PR first, and rebase this to be going into master. And start looking at the changes here to try to understand what is going on.
Oh, looks like github did it automatically...

File: src/microbe_stage/editor/EditorActionHistory.cs [hunk 1]
```diff
@@ -187,24 +187,56 @@ public bool HexPlacedThisSession<THex>(THex hex)
...
+                ActionInterferenceMode.NoInterference => (Cost: 0, Priority: 0),
+
                 _ => throw new ArgumentOutOfRangeException(nameof(interferenceMode)),
             }, data, interferenceMode);
-        }).OrderBy(p => p.Item1).FirstOrDefault();
+        }).OrderByDescending(p => p.Item1.Priority).ThenBy(p => p.Item1.Cost);
+
+        // Calculate actual cost delta by adding up all replacement refunds, and if any, the first non-replacement one
+        var costDelta = 0;
+        using var combinationDataEnumerator = combinationDataEnumerable.GetEnumerator();
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/EditorActionHistory.cs:221]: Why is this not a foreach loop?

You can use variables that are set to not-null the first time the loop runs.

File: src/microbe_stage/editor/EditorActionHistory.cs [hunk 2]
```diff
@@ -187,24 +187,56 @@ public bool HexPlacedThisSession<THex>(THex hex)
...
+
+        // Get the first combination data, which is what we'll return
+        var firstData = combinationDataEnumerator.Current;
+
+        do
+        {
+            costDelta += combinationDataEnumerator.Current.Item1.Cost;
+        }
+
+        // We first make sure the current one is replacement type, then make sure the enumerator hasn't reached an end
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/EditorActionHistory.cs:235]: This spacing here makes this do loop especially hard to read as they are super rare in the Thrive code. In my other comment I suggested how to rewrite this as a foreach loop, which is what I'd do as I find reading them much easier.

**Comment by hhyyrylainen** [comment]
You added a comment that says this now fixes #4083 but didn't update the description of this PR. Did you forget or is there another reason?

**Comment by 84634E1A607A** [comment]
Just I'm not sure if fix statement is effective in commit message.

**Comment by hhyyrylainen** [comment]
It is when this is *merged* but github won't show in the right panel that this closes that issue, and it's much less clear when the PR description doesn't have that info. 
Someone might at some point accidentally merge a PR that closes an issue etehat didn't get properly tested in the PR if that issue is just in a commit message.

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 3]
```diff
@@ -1455,14 +1455,16 @@ private bool IsUpgradingPossibleFor(OrganelleDefinition organelleDefinition)
...
                         CostMultiplier = CostMultiplier,
                     };
 
-                    if (replacedHex != null)
-                        data.ReplacedCytoplasm = new List<OrganelleTemplate> { replacedHex };
+                    var replacedHex = organelle.RotatedHexes.Select(h => editedMicrobeOrganelles.GetElementAt(hex + h))
+                        .WhereNotNull().ToList();
+
+                    if (replacedHex.Count > 0)
+                        data.ReplacedCytoplasm = replacedHex;
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:1467]:
```suggestion
                    var replacedHexes = organelle.RotatedHexes.Select(h => editedMicrobeOrganelles.GetElementAt(hex + h))
                        .WhereNotNull().ToList();

                    if (replacedHexes.Count > 0)
                        data.ReplacedCytoplasm = replacedHexes;
```

Suggestion to have grammatically more correct variable name.

File: src/microbe_stage/editor/action_data/OrganelleRemoveActionData.cs [hunk 4]
```diff
@@ -50,6 +50,7 @@ protected override CombinableActionData CreateDerivedMoveAction(HexPlacementActi
 
     protected override CombinableActionData CreateDerivedRemoveAction(HexMoveActionData<OrganelleTemplate> data)
     {
-        return new OrganelleRemoveActionData(RemovedHex, data.OldLocation, data.OldRotation);
+        return new OrganelleRemoveActionData(RemovedHex, data.OldLocation, data.OldRotation)
+            { GotReplaced = GotReplaced };
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/action_data/OrganelleRemoveActionData.cs:54]: Should the placement and move actions also be updated to preserve the list of replaced things?

Comment (84634E1A607A) [reply src/microbe_stage/editor/action_data/OrganelleRemoveActionData.cs:54]: This property is a bool, indicating whether the remove action is because that something replaces it (so the remove action has 0 cost). Placement and move action don't have this property.

Comment (hhyyrylainen) [reply src/microbe_stage/editor/action_data/OrganelleRemoveActionData.cs:54]: Okay, I see, I was confusing this variable with the list of replaced cytoplasms that exists in the placement action.

**Review by hhyyrylainen — APPROVED** [review]
I don't have any more code comments related to this. I have not playtested this.

As there doesn't seem to be any active people doing testing, I'll either test this a bit myself later today (or more likely) just merge and hope this fully addresses the issues this is marked as solving.

**Comment by 84634E1A607A** [comment]
I must say that dynamic MP is still *rather* buggy that I cannot say for sure whether this change produces some other bugs or not.

**Comment by hhyyrylainen** [comment]
I can confirm at least that the MP bug with deleting an upgraded organelle in the same editor cycle now refunds the MP. 

I'll merge this tomorrow even if no one else has time to test this.
