### PR TITLE
2370 - Editor access in colony

### LINKED ISSUE #2370: Editor button needs to lock if the player joins a colony
Got a report that if you are ready to go to the editor and you join a colony, the editor button stays enabled (and pressing it crashes the game).

### PR DESCRIPTION
**Pull request by Maxonovien**
**Brief Description of What This PR Does**

This PR does disable editor upon creating colony and reenables it upon unbinding (only if it was possible already).

**Related Issues**

Fixes #2370 .

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

File: src/microbe_stage/Microbe.cs [hunk 1]
```diff
@@ -1382,6 +1382,12 @@ internal void OnColonyMemberRemoved(Microbe microbe)
             RevertNodeParent();
             ai?.ResetAI();
 
+            // Colony reset at the end, to allow for previous operations on it.
+            Colony = null;
+
+            // Checks if the cell is ready to reproduce (allows editor access on unbind).
+            if (allOrganellesDivided)
+                OnReproductionStatus?.Invoke(this, true);
```
Comment (Kasterisk) [inline src/microbe_stage/Microbe.cs:1390]: A little nitpick but it's nice to have a whitespace separating the `return` and this.

**Review by Kasterisk — APPROVED** [review]
Seems to work great overall.

File: src/microbe_stage/Microbe.cs [hunk 2]
```diff
@@ -1382,6 +1382,13 @@ internal void OnColonyMemberRemoved(Microbe microbe)
             RevertNodeParent();
             ai?.ResetAI();
 
+            // Colony reset at the end, to allow for previous operations on it.
+            Colony = null;
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:1386]: Why was this added here, as there's already:
https://github.com/Revolutionary-Games/Thrive/blob/cf56b89a03d8dbf5067a260d14e319170fc6d1b4/src/microbe_stage/MicrobeColony.cs#L61
?
I think a better design would be to reset allOrganellesDivided to false when joining a colony (and then make sure that after unbind the reproduction progress checks will properly enable the editor if needed).

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

File: src/microbe_stage/Microbe.cs (hunk 2 above)
Comment (Maxonovien) [reply src/microbe_stage/Microbe.cs:1386]: Hm, that's indeed a good point. But I added this because I realised that, at this point, the colony was not set to null (commenting my line restores the issue).

After investigating, this line in facts sets the microbe Colony to null, but after Microbe-related methods (those which allow to reproduce). I tried moving it, but it disables full unbinding of colony, because, well, the colony to unbind is null. It would make sense, however to delete the `microbe.Colony = null;` line in MicrobeColony.

Comment (hhyyrylainen) [reply src/microbe_stage/Microbe.cs:1386]: Did you try using the allOrganellesDivided variable approach? I think it might remove the need to fiddle with where the Colony variable is set to null.

Comment (Maxonovien) [reply src/microbe_stage/Microbe.cs:1386]: It would only work for disabling editor, not reenabling it : to activate the editor button from the HUD, I have to use MicrobeHUD.ShowReproductionDialog(); through MicrobeStage.OnPlayerReproductionStatusChanged, which checks player.Colony == null. 

So I need to nullify the Colony beforehand, or change/circumvene other files safety check (which is not advisable in general).

Comment (hhyyrylainen) [reply src/microbe_stage/Microbe.cs:1386]: Then setting allOrganellesDivided to false here, might work? I think the logic would go like this:
- microbe runs update
- microbe leaves a colony
- microbe runs update (reproduction progress gets re-checked here, and Colony is now null)

Comment (Maxonovien) [reply src/microbe_stage/Microbe.cs:1386]: I wanted to rely on such logic at first but did not consider allOrganellesDivided shortcuts. It may work, in fact. I'll take a look at it after reworking AI code

Comment (Maxonovien) [reply src/microbe_stage/Microbe.cs]: You were fully right on this it seems to work perfectly well, including when saving & loading. It seems much nicer as well. Thanks!

File: src/microbe_stage/Microbe.cs [hunk 3]
```diff
@@ -1420,25 +1420,29 @@ internal void SuccessfulKill()
...
     {
-        var oldRotation = Rotation;
-        var vectorToParent = GlobalTransform.origin - ColonyParent.GlobalTransform.origin;
-        ChangeNodeParent(ColonyParent);
-
         State = MicrobeState.Normal;
 
-        var vectorToParentRotated = vectorToParent.Rotated(Vector3.Down, Rotation.y);
-        var vectorToMembrane = Membrane.GetExternalOrganelle(vectorToParentRotated.x, vectorToParentRotated.y);
+        if (ColonyParent != null)
```
Comment (FuJa0815) [inline src/microbe_stage/Microbe.cs:1425]: I think an early return would be better. Something like
```cs
if (ColonyParent == null)
{
    UnreadyToReproduce();
    return;
}
// code...
```
would be more readable

**Review by FuJa0815 — CHANGES_REQUESTED** [review]

**Review by FuJa0815 — APPROVED** [review]

**Comment by hhyyrylainen** [comment]
I opened a separate issue about the unbinding mode being exited: https://github.com/Revolutionary-Games/Thrive/issues/2409

**Review by hhyyrylainen — APPROVED** [review]
If @FuJa0815 tested this, that's good enough for me.
