### PR TITLE
Fix species preview tooltips not working in Timeline tab of Editor's report

### LINKED ISSUE #4912: Make species preview hover tooltip work in timeline of report tab
Follow up to: https://github.com/Revolutionary-Games/Thrive/pull/4817
Honorable mention: https://github.com/Revolutionary-Games/Thrive/issues/4842

If you hover over a species name in the timeline, it does not show a species preview. Unlike the one in auto-evo exploring tool, the cursor does not change color when you hover over a species name.

### PR DESCRIPTION
**Pull request by dligr**
**Brief Description of What This PR Does**

Makes species preview tooltips work in Timeline tab by making logs use bbcode species names.

Also fixes External effects section of Auto-evo report not having species preview tooltips, since it's somewhat related.

**Related Issues**

Closes #4912

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/general/Species.cs [hunk 1]
```diff
@@ -119,13 +119,21 @@ public Color GUIColour
...
-        $"[url=species:{ID}][b][i]{FormattedName}[/i][/b][/url]" :
-        $"[url=species:{ID}][i]{FormattedName}[/i][/url]";
+        $"[b][i]{FormattedNameBbCodeUnstyled}[/i][/b]" :
+        $"[i]{FormattedNameBbCodeUnstyled}[/i]";
+
+    /// <summary>
+    ///   Returns <see cref="FormattedName"/> but includes bbcode tags for hover-over tooltips.
+    /// </summary>
+    [JsonIgnore]
+    public string FormattedNameBbCodeUnstyled => PlayerSpecies ?
```
Comment (hhyyrylainen) [inline src/general/Species.cs:134]: Isn't the values same regardless of what PlayerSpecies is here?

Comment (dligr) [reply src/general/Species.cs]: Right, didn't notice this somehow

**Review by hhyyrylainen — APPROVED** [review]
Code change looks good now.

**Comment by hhyyrylainen** [comment]
Formatting checks failed. You can run those locally for faster iteration on the problem. Or you can run the reformat tool to fix it all: `dotnet run --project Scripts -- check cleanupcode` and then commit the result.
