### PR TITLE
Fixed loading text not updating when pressing Esc

### LINKED ISSUE #2501: Pressing Esc while loading pauses loading
**Describe the bug**

When in the loading screen you can press Esc and the text won't update anymore. Pressing Esc resumes the text updating. While in this Esc state the game won't finish loading until you end this buggy state via pressing Esc again.

### PR DESCRIPTION
**Pull request by FuJa0815**
**Brief Description of What This PR Does**

The MicrobeEditor (which updates the loading description text) is now initially in Process-Pausemode. Once loading is complete it changes to Inherit-Pausemode

**Related Issues**

closes #2501

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
I think it would be much better if the pause menu would be prevented from opening while the game is loading.

**Comment by hhyyrylainen** [comment]
I just looked through the code and it looks fine to me and did a bit of playtesting. So once my one concern is addressed this is fine by me to be merged: https://github.com/Revolutionary-Games/Thrive/pull/2573#commitcomment-55986459

**Review by 84634E1A607A — DISMISSED** [review]
When you press Editor button then F1 or Esc before animation completes, Editor gets stuck -- Without recovery!

**Comment by hhyyrylainen** [comment]
Sounds like a pretty serious problem and should be fixed. But maybe my suggestion that *closing* the pause menu should always be allowed to avoid very serious getting stuck problems like that.
Thanks for testing this!

File: src/gui_common/TransitionManager.cs [hunk 1]
```diff
@@ -36,6 +37,7 @@ private TransitionManager()
     public List<ITransition> TransitionSequence { get; } = new List<ITransition>();
 
     public bool HasQueuedTransitions => TransitionSequence.Count > 0;
+    public bool HasTransitionInProgress => TransitionSequence.Any(ts => IsInstanceValid((Node)ts));
```
Comment (hhyyrylainen) [inline src/gui_common/TransitionManager.cs:40]: @Kasterisk you wrote this system, right? So could you comment on how possible it is that there is an *invalid* object in here?
I personally think this should just be a `HasQueuedTransitions and currently running transitions` (however that latter thing could be checked).

Comment (FuJa0815) [reply src/gui_common/TransitionManager.cs:40]: I've slightly based this upon the `CancelQueuedTransitions` method and tested the functionality with a debugger, although I wasn't able to test all cases.

Comment (Kasterisk) [reply src/gui_common/TransitionManager.cs:40]: The transitions queue free themselves after finished which is why there's an invalid object in `TransitionSequence`. In a way usage of `IsInstanceValid` works as a check for any active transitions or currently running transitions in a set sequence.

An alternative in this case that I could think of (haven't tested) without any need for IsInstanceValid is turning the local variable at line 160 to a private member variable maybe as currentTransition, and so you can just make the in progress check as `HasQueuedTransitions && currentTransition != null`. This variable can later be cleared in the if block at line 152 when the sequence finishes.

Comment (hhyyrylainen) [reply src/gui_common/TransitionManager.cs:40]: Why don't the objects remove themselves from the sequence when they are done, then? That seems much better than keeping disposed objects around.

Comment (Kasterisk) [reply src/gui_common/TransitionManager.cs:40]: Yes that's also preferable. I just didn't find a good way to do that back when implementing the class.

Comment (hhyyrylainen) [reply src/gui_common/TransitionManager.cs:40]: I've used this kind of approach:
```
                    if (runSteps.Peek().RunStep(results))
                        runSteps.Dequeue();
```
to remove an object once it was done. A similar thing could probably be adapted here so that the transitions tell the main code when to remove it.

Comment (Kasterisk) [reply src/gui_common/TransitionManager.cs:40]: Now that you mention `Dequeue`, I forgot to mention that `TransitionSequence` is a list and just a helper to capture `queuedTransition`'s initial sequence structure. `queuedTransitions` is the actual queue that's used for advancing through the transition sequence which also removes the current transition from itself. So maybe we can use `queuedTransitions` Count for the in progress check?

Comment (hhyyrylainen) [reply src/gui_common/TransitionManager.cs:40]: Why there's actually multiple of those lists?
Wouldn't it be simpler if we had a method that requires you to give it a list of actions already, which would immediately go to the running things?
That would solve the problem as well, or?

Comment (Kasterisk) [reply src/gui_common/TransitionManager.cs:40]: > Why there's actually multiple of those lists?

It's mainly due to CancelQueuedTransitions. I think I remember the problem when implementing it was that queudTransitions doesn't include the currently running transition (because of Dequeue) so what happen was all subsequent transitions got skipped but not the one that's currently running, the solution I came up with was the `TransitionSequence` to hold references to all transition objects from initial queuedTransitions...

You know, I now realize it's a bit silly. In hindsight it probably makes most sense to go with the `currentTransition` variable I mentioned earlier and then just iterate through queuedTransitions to skip all remaining transitions without needing an extra list, so only one queuedTransitions needed, probably will be more robust as well.

> Wouldn't it be simpler if we had a method that requires you to give it a list of actions already, which would immediately go to the running things?

Yes, the current system works a bit like that. We first give TransitionManager "a list" of actions by adding to the transitions queue by calling either `AddScreenFade` or `AddCutscene` and then we call StartTransitions which will immediately advance through the sequence.

Comment (FuJa0815) [reply src/gui_common/TransitionManager.cs:40]: So, is this line fine? 😅

Comment (hhyyrylainen) [reply src/gui_common/TransitionManager.cs:40]: I say this is not because "IsInstanceValid" is a huge design smell to me. This PR needs to be designed some other way but I think we can leave the overall approach changing to @Kasterisk

Comment (Kasterisk) [reply src/gui_common/TransitionManager.cs:40]: I think for now it's fine to use `HasQueuedTransitions`. It kind of already functions as `HasTransitionInProgress` and is relevant until sequence is finished and the list is cleared. Any further will probably warrant a medium rework as mentioned in earlier discussions.

File: src/general/PauseMenu.cs [hunk 2]
```diff
@@ -99,6 +101,25 @@ private ActiveMenuType ActiveMenu
...
 
+    /// <summary>
+    ///   If true the user may not open or close the pause menu.
+    /// </summary>
+    /// <remarks>
+    ///   <para>
+    ///     Does not automatically close the pause menu when set to true.
+    ///   </para>
+    /// </remarks>
+    public bool IsPausingBlocked()
```
Comment (hhyyrylainen) [inline src/general/PauseMenu.cs:112]: This could be a get only property

File: src/gui_common/TransitionManager.cs [hunk 3]
```diff
@@ -1,4 +1,5 @@
 ﻿using System.Collections.Generic;
+using System.Linq;
```
Comment (hhyyrylainen) [inline src/gui_common/TransitionManager.cs:2]: This added line is probably why CI fails.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

File: src/general/PauseMenu.cs [hunk 4]
```diff
@@ -64,6 +64,33 @@ private enum ActiveMenuType
     /// </summary>
     public GameProperties GameProperties { get; set; }
 
+    public bool GameLoading { get; set; }
+
+    /// <summary>
+    ///   If true the user may not open or close the pause menu.
```
Comment (hhyyrylainen) [inline src/general/PauseMenu.cs:70]: This comment is now wrong.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
One tiny code related thing. I now playtested this and (with tutorials enabled) I wasn't able to open the pause menu with ESC at all...

**Comment by FuJa0815** [comment]
> One tiny code related thing. I now playtested this and (with tutorials enabled) I wasn't able to open the pause menu with ESC at all...

Sorry, was only able to make swift changes and haven't had time to test them. This had a logic error.

**Review by hhyyrylainen — APPROVED** [review]
I didn't find anything wrong with this. I assume that other issue that someone else found is also fixed so that this is finally good to merge.
