### PR TITLE
Multicellular editor can crash when undoing due to System.InvalidOperationException: Sequence contains no matching element

### LINKED ISSUE #3906: Multicellular editor can crash when undoing due to System.InvalidOperationException: Sequence contains no matching element
```
Thrive has crashed at 2022-12-04T16:36:17.3887650Z (crash happened immediately before creating this report)
Exit code: 1
Description: Crash is an unhandled exception
==== START OF LAUNCHER OUTPUT ====
Thrive is starting. Log output (due to buffering this is likely not in real time):
Setting breakpad minidump AppID = 1779200
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197974187562 [API loaded no]
Godot Engine v3.5.stable.mono.thrive.d2ad79a40 - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 570/PCIe/SSE2
Async. shader compilation: OFF
 
Mono: Log file is: 'C:/Users/Besitzer/AppData/Roaming/Thrive/mono/mono_logs/2022-12-04_16.56.10_11676.log'
This is Thrive version: 0.6.0.0-rc1 (see below for exact build info)
Unhandled exception logger attached
Startup C# locale is: de-DE Godot locale is: de_DE
user:// directory is: C:/Users/Besitzer/AppData/Roaming/Thrive
Game logs are written to: C:/Users/Besitzer/AppData/Roaming/Thrive\logs latest log is 'log.txt'
Doing delayed apply for some settings
Set audio output device to: Default
Set C# locale to: de-DE Godot locale is: de
Starting Steam load
Steam load finished
Game is owned by current Steam user
Our app id is: 1779200
SimulationParameters are good
This version of Thrive was built at Saturday, 03 December 2022 12:30:42 from commit 9f508dfde02abd66411319256b59aa80bbef107d on branch master
Detected store name from launch parameters: 
Launcher tells us that we are store version: steam
Launcher told us store name: steam
We were opened through the Thrive Launcher
Launcher opening us is hidden
Thrive Launcher started us, launcher hidden: True
Loading mod Nodes into the scene tree
Jukebox now playing from: Menu
Jukebox: starting track: res://assets/sounds/main-menu-theme-1.ogg position: 0
Startup successful, removing startup info file
------------ Thrive Startup Succeeded ------------
Previous patch doesn't exist, despawning all entities.
Applying patch (Dolerurun Gezeitent�mpel) settings
Number of clouds in this patch = 9
Registering new spawner: Name: ammonia density: 1,2
Registering new spawner: Name: glucose density: 0,6
Registering new spawner: Name: phosphates density: 1,2
hydrogensulfide spawn density is 0. It won't spawn
oxygen spawn density is 0. It won't spawn
carbondioxide spawn density is 0. It won't spawn
nitrogen spawn density is 0. It won't spawn
sunlight spawn density is 0. It won't spawn
temperature spawn density is 0. It won't spawn
Number of chunks in this patch = 4
Registering new spawner: Name: FLOATING_HAZARD density: 1
Registering new spawner: Name: SMALL_IRON_CHUNK density: 0,9
Registering new spawner: Name: BIG_IRON_CHUNK density: 0,6
Registering new spawner: Name: GOOGLY_EYE_CELL density: 0,001
Number of species in this patch = 1
Registering new spawner: Name: 1 density: 0,172129
Player Microbe spawned
World generation settings: [LAWK: True, Difficulty: easy preset, Life origin: Pond, Seed: 1892751535, Map type: Procedural, Day/night cycle enabled: True, Day length: 60, Include multicellular: True, Easter eggs: True]
Jukebox now playing from: MicrobeStage
TaskExecutor started with parallel job count: 2
Jukebox: starting track: res://assets/sounds/microbe-theme-1.ogg position: 0
Jukebox: starting track: res://assets/sounds/soundeffects/microbe-ambience-3.ogg position: 0
Move to editor pressed
Starting microbe editor with: 1 organelles in the microbe
Elapsing time on editor entry
TimedWorldOperations: running effects. elapsed: 1 total passed: 100000000
Applying auto-evo results. Auto-evo run took: 00:00:00.0718397
Jukebox now playing from: MicrobeEditor
Creating a save with name: auto_save_2.thrivesave
save finished, success: True message: Speichern erfolgreich elapsed: 00:00:02.6784004
JSON trace written to: user://logs/json_debug.txt
There's a very long JSON trace, only written to: user://logs/json_debug.txt
JSON serialization trace: 2022-12-04T16:59:39.308 Info Started serializing SaveInformation. Path ''.

2022-12-04T16:59:39.309 Info Finished serializing SaveInformation. Path ''.

2022-12-04T16:59:39.309 Verbose Serialized JSON: 

{

  "ThriveVersion": "0.6.0.0-rc1",

  "Platform": "Windows",

  "Creator": "[SNM]Magician",

  "CreatedAt": "2022-12-04T16:59:37.6282487+01:00",

  "Description": "",

  "ID": "a8072aab-6872-4cd8-9009-a5f4181488da",

  "Type": 1,

  "IsPrototype": false

}
Jukebox: starting track: res://assets/sounds/microbe-editor-theme-4.ogg position: 0
Placing organelle 'chromatophore' at: 1, -1
Placing organelle 'metabolosome' at: 1, 0
MicrobeEditor: applying changes to edited Species
MicrobeEditorReportComponent: applying changes of component
MicrobeEditorPatchMap: applying changes of component
CellEditorComponent: applying changes of component
Edited species name is now Primum thrivium
MicrobeEditor: updated organelles for species: Primum thrivium
Applying patch (Dolerurun Gezeitent�mpel) settings
Number of clouds in this patch = 9
Changing spawn density of glucose from 0,6 to 0,54
hydrogensulfide spawn density is 0. It won't spawn
oxygen spawn density is 0. It won't spawn
carbondioxide spawn density is 0. It won't spawn
nitrogen spawn density is 0. It won't spawn
sunlight spawn density is 0. It won't spawn
temperature spawn density is 0. It won't spawn
Number of chunks in this patch = 4
Number of species in this patch = 1
Changing spawn density of 1 from 0,172129 to 0,2461259
Jukebox now playing from: MicrobeStage
Creating a save with name: auto_save_5.thrivesave
save finished, success: True message: Speichern erfolgreich elapsed: 00:00:01.7437668
JSON trace written to: user://logs/json_debug.txt
There's a very long JSON trace, only written to: user://logs/json_debug.txt
JSON serialization trace: 2022-12-04T17:00:52.785 Info Started serializing SaveInformation. Path ''.

2022-12-04T17:00:52.785 Info Finished serializing SaveInformation. Path ''.

2022-12-04T17:00:52.785 Verbose Serialized JSON: 

{

  "ThriveVersion": "0.6.0.0-rc1",

  "Platform": "Windows",

  "Creator": "[SNM]Magician",

  "CreatedAt": "2022-12-04T17:00:52.0709639+01:00",

  "Description": "",

  "ID": "8c859fa2-cfb8-40f1-ac9c-0191ea5ed71f",

  "Type": 1,

  "IsPrototype": false

}
Jukebox: starting track: res://assets/sounds/microbe-theme-1.ogg position: 97,52962
Jukebox: starting track: res://assets/sounds/soundeffects/microbe-ambience-3.ogg position: 97,52962
Move to editor pressed
Starting microbe editor with: 3 organelles in the microbe
Elapsing time on editor entry
TimedWorldOperations: running effects. elapsed: 1 total passed: 200000000
Applying auto-evo results. Auto-evo run took: 00:00:00.0299340
Jukebox now playing from: MicrobeEditor
Creating a save with name: auto_save_1.thrivesave
save finished, success: True message: Speichern erfolgreich elapsed: 00:00:01.7929401
JSON trace written to: user://logs/json_debug.txt
There's a very long JSON trace, only written to: user://logs/json_debug.txt
JSON serialization trace: 2022-12-04T17:02:52.805 Info Started serializing SaveInformation. Path ''.

2022-12-04T17:02:52.805 Info Finished serializing SaveInformation. Path ''.

2022-12-04T17:02:52.805 Verbose Serialized JSON: 

{

  "ThriveVersion": "0.6.0.0-rc1",

  "Platform": "Windows",

  "Creator": "[SNM]Magician",

  "CreatedAt": "2022-12-04T17:02:51.928593+01:00",

  "Description": "",

  "ID": "2da13fc6-e552-4ec7-a9ab-e07d28bcd561",

  "Type": 1,

  "IsPrototype": false

}
Jukebox: starting track: res://assets/sounds/microbe-editor-theme-4.ogg position: 73,58984
Placing organelle 'chromatophore' at: 1, 0
Placing organelle 'chromatophore' at: 1, 1
MicrobeEditor: applying changes to edited Species
MicrobeEditorReportComponent: applying changes of component
MicrobeEditorPatchMap: applying changes of component
CellEditorComponent: applying changes of component
Edited species name is now Primum thrivium
MicrobeEditor: updated organelles for species: Primum thrivium
Applying patch (Dolerurun Gezeitent�mpel) settings
Number of clouds in this patch = 9
Changing spawn density of glucose from 0,54 to 0,4859999
hydrogensulfide spawn density is 0. It won't spawn
oxygen spawn density is 0. It won't spawn
carbondioxide spawn density is 0. It won't spawn
nitrogen spawn density is 0. It won't spawn
sunlight spawn density is 0. It won't spawn
temperature spawn density is 0. It won't spawn
Number of chunks in this patch = 4
Number of species in this patch = 2
Changing spawn density of 1 from 0,2461259 to 0,2676269
Registering new spawner: Name: 2 density: 0,172129
Jukebox now playing from: MicrobeStage
Creating a save with name: auto_save_2.thrivesave
save finished, success: True message: Speichern erfolgreich elapsed: 00:00:01.8592286
JSON trace written to: user://logs/json_debug.txt
There's a very long JSON trace, only written to: user://logs/json_debug.txt
JSON serialization trace: 2022-12-04T17:03:55.813 Info Started serializing SaveInformation. Path ''.

2022-12-04T17:03:55.813 Info Finished serializing SaveInformation. Path ''.

2022-12-04T17:03:55.813 Verbose Serialized JSON: 

{

  "ThriveVersion": "0.6.0.0-rc1",

  "Platform": "Windows",

  "Creator": "[SNM]Magician",

  "CreatedAt": "2022-12-04T17:03:55.00353+01:00",

  "Description": "",

  "ID": "b2fd43be-c26b-4922-94d1-6edde59ddbab",

  "Type": 1,

  "IsPrototype": false

}
Jukebox: starting track: res://assets/sounds/microbe-theme-1.ogg position: 217,2575
Jukebox: starting track: res://assets/sounds/soundeffects/microbe-ambience-3.ogg position: 217,2575
Jukebox: starting track: res://assets/sounds/microbe-theme-3.ogg position: 0
Move to editor pressed
Starting microbe editor with: 5 organelles in the microbe
Elapsing time on editor entry
TimedWorldOperations: running effects. elapsed: 1 total passed: 300000000
Applying auto-evo results. Auto-evo run took: 00:00:00.0300515
Jukebox now playing from: MicrobeEditor
Creating a save with name: auto_save_5.thrivesave
save finished, success: True message: Speichern erfolgreich elapsed: 00:00:02.2184675
JSON trace written to: user://logs/json_debug.txt
There's a very long JSON trace, only written to: user://logs/json_debug.txt
JSON serialization trace: 2022-12-04T17:06:38.647 Info Started serializing SaveInformation. Path ''.

2022-12-04T17:06:38.648 Info Finished serializing SaveInformation. Path ''.

2022-12-04T17:06:38.648 Verbose Serialized JSON: 

{

  "ThriveVersion": "0.6.0.0-rc1",

  "Platform": "Windows",

  "Creator": "[SNM]Magician",

  "CreatedAt": "2022-12-04T17:06:37.3503687+01:00",

  "Description": "",

  "ID": "4a26edfd-e644-4e38-94ee-8adb7b8e88ba",

  "Type": 1,

  "IsPrototype": false

}
Jukebox: starting track: res://assets/sounds/microbe-editor-theme-4.ogg position: 136,8468
Placing organelle 'nucleus' at: -1, 2
Placing organelle 'chromatophore' at: 1, 1
MicrobeEditor: applying changes to edited Species
MicrobeEditorReportComponent: applying changes of component
MicrobeEditorPatchMap: applying changes of component
CellEditorComponent: applying changes of component
Edited species name is now Primum thrivium
MicrobeEditor: updated organelles for species: Primum thrivium
Applying patch (Dolerurun Gezeitent�mpel) settings
Number of clouds in this patch = 9
Changing spawn density of glucose from 0,4859999 to 0,4374
hydrogensulfide spawn density is 0. It won't spawn
oxygen spawn density is 0. It won't spawn
carbondioxide spawn density is 0. It won't spawn
nitrogen spawn density is 0. It won't spawn
sunlight spawn density is 0. It won't spawn
temperature spawn density is 0. It won't spawn
Number of chunks in this patch = 4
Number of species in this patch = 2
Changing spawn density of 1 from 0,2676269 to 0,2733546
Changing spawn density of 2 from 0,172129 to 0,2310813
Jukebox now playing from: MicrobeStage
Creating a save with name: auto_save_1.thrivesave
save finished, success: True message: Speichern erfolgreich elapsed: 00:00:02.6670362
JSON trace written to: user://logs/json_debug.txt
There's a very long JSON trace, only written to: user://logs/json_debug.txt
JSON serialization trace: 2022-12-04T17:07:19.239 Info Started serializing SaveInformation. Path ''.

2022-12-04T17:07:19.239 Info Finished serializing SaveInformation. Path ''.

2022-12-04T17:07:19.239 Verbose Serialized JSON: 

{

  "ThriveVersion": "0.6.0.0-rc1",

  "Platform": "Windows",

  "Creator": "[SNM]Magician",

  "CreatedAt": "2022-12-04T17:07:17.9961337+01:00",

  "Description": "",

  "ID": "824a162c-6de1-4897-ac2b-81aa7b09a71b",

  "Type": 1,

  "IsPrototype": false

}
Jukebox: starting track: res://assets/sounds/microbe-theme-3.ogg position: 23,80626
Jukebox: starting track: res://assets/sounds/soundeffects/microbe-ambience-3.ogg position: 379,8262
Jukebox: starting track: res://assets/sounds/soundeffects/microbe-ambience.ogg position: 0
Move to editor pressed
Starting microbe editor with: 7 organelles in the microbe
Elapsing time on editor entry
TimedWorldOperations: running effects. elapsed: 1 total passed: 400000000
Applying auto-evo results. Auto-evo run took: 00:00:00.0703106
Jukebox now playing from: MicrobeEditor
Creating a save with name: auto_save_2.thrivesave
save finished, success: True message: Speichern erfolgreich elapsed: 00:00:03.0577294
JSON trace written to: user://logs/json_debug.txt
There's a very long JSON trace, only written to: user://logs/json_debug.txt
JSON serialization trace: 2022-12-04T17:10:03.290 Info Started serializing SaveInformation. Path ''.

2022-12-04T17:10:03.291 Info Finished serializing SaveInformation. Path ''.

2022-12-04T17:10:03.291 Verbose Serialized JSON: 

{

  "ThriveVersion": "0.6.0.0-rc1",

  "Platform": "Windows",

  "Creator": "[SNM]Magician",

  "CreatedAt": "2022-12-04T17:10:01.1862305+01:00",

  "Description": "",

  "ID": "ea88e77a-ff62-408d-8bde-f7527a1c41f7",

  "Type": 1,

  "IsPrototype": false

}
Jukebox: starting track: res://assets/sounds/microbe-editor-theme-4.ogg position: 178,068
Placing organelle 'chloroplast' at: -2, 0
Placing organelle 'chloroplast' at: 1, 2
Jukebox: starting track: res://assets/sounds/microbe-editor-theme-2.ogg position: 0
Placing organelle 'chloroplast' at: -2, 0
Placing organelle 'mitochondrion' at: 1, 2
MicrobeEditor: applying changes to edited Species
MicrobeEditorReportComponent: applying changes of component
MicrobeEditorPatchMap: applying changes of component
CellEditorComponent: applying changes of component
Edited species name is now Primum thrivium
MicrobeEditor: updated organelles for species: Primum thrivium
Applying patch (Dolerurun Gezeitent�mpel) settings
Number of clouds in this patch = 9
Changing spawn density of glucose from 0,4374 to 0,3936599
hydrogensulfide spawn density is 0. It won't spawn
oxygen spawn density is 0. It won't spawn
carbondioxide spawn density is 0. It won't spawn
nitrogen spawn density is 0. It won't spawn
sunlight spawn density is 0. It won't spawn
temperature spawn density is 0. It won't spawn
Number of chunks in this patch = 4
Number of species in this patch = 2
Changing spawn density of 1 from 0,2733546 to 0,2732949
Changing spawn density of 2 from 0,2310813 to 0,2623799
Jukebox now playing from: MicrobeStage
Creating a save with name: auto_save_5.thrivesave
save finished, success: True message: Speichern erfolgreich elapsed: 00:00:03.4822369
JSON trace written to: user://logs/json_debug.txt
There's a very long JSON trace, only written to: user://logs/json_debug.txt
JSON serialization trace: 2022-12-04T17:11:26.642 Info Started serializing SaveInformation. Path ''.

2022-12-04T17:11:26.642 Info Finished serializing SaveInformation. Path ''.

2022-12-04T17:11:26.642 Verbose Serialized JSON: 

{

  "ThriveVersion": "0.6.0.0-rc1",

  "Platform": "Windows",

  "Creator": "[SNM]Magician",

  "CreatedAt": "2022-12-04T17:11:24.5681021+01:00",

  "Description": "",

  "ID": "4365a185-0fb1-4f5a-a52d-8ab0227f2de8",

  "Type": 1,

  "IsPrototype": false

}
Jukebox: starting track: res://assets/sounds/microbe-theme-3.ogg position: 187,2573
Jukebox: starting track: res://assets/sounds/soundeffects/microbe-ambience.ogg position: 77,28181
Move to editor pressed
Starting microbe editor with: 8 organelles in the microbe
Elapsing time on editor entry
TimedWorldOperations: running effects. elapsed: 1 total passed: 500000000
Applying auto-evo results. Auto-evo run took: 00:00:00.2409789
Jukebox now playing from: MicrobeEditor
Creating a save with name: auto_save_1.thrivesave
save finished, success: True message: Speichern erfolgreich elapsed: 00:00:04.4268285
JSON trace written to: user://logs/json_debug.txt
There's a very long JSON trace, only written to: user://logs/json_debug.txt
JSON serialization trace: 2022-12-04T17:14:25.836 Info Started serializing SaveInformation. Path ''.

2022-12-04T17:14:25.837 Info Finished serializing SaveInformation. Path ''.

2022-12-04T17:14:25.837 Verbose Serialized JSON: 

{

  "ThriveVersion": "0.6.0.0-rc1",

  "Platform": "Windows",

  "Creator": "[SNM]Magician",

  "CreatedAt": "2022-12-04T17:14:22.3761371+01:00",

  "Description": "",

  "ID": "dfc05041-517a-4f5f-8d4b-e15744b07285",

  "Type": 1,

  "IsPrototype": false

}
Jukebox: starting track: res://assets/sounds/microbe-editor-theme-2.ogg position: 64,71982
Jukebox: starting track: res://assets/sounds/microbe-editor-theme-1.ogg position: 0
Placing organelle 'mitochondrion' at: 1, 4
Placing organelle 'chloroplast' at: -4, -1
Placing organelle 'chloroplast' at: 1, 6
MicrobeEditor: applying changes to edited Species
MicrobeEditorReportComponent: applying changes of component
MicrobeEditorPatchMap: applying changes of component
CellEditorComponent: applying changes of component
Edited species name is now Primum thrivium
MicrobeEditor: updated organelles for species: Primum thrivium
Applying patch (Dolerurun Gezeitent�mpel) settings
Number of clouds in this patch = 9
Changing spawn density of glucose from 0,3936599 to 0,3542939
hydrogensulfide spawn density is 0. It won't spawn
oxygen spawn density is 0. It won't spawn
carbondioxide spawn density is 0. It won't spawn
nitrogen spawn density is 0. It won't spawn
sunlight spawn density is 0. It won't spawn
temperature spawn density is 0. It won't spawn
Number of chunks in this patch = 4
Number of species in this patch = 2
Changing spawn density of 1 from 0,2732949 to 0,274514
Changing spawn density of 2 from 0,2623799 to 0,2380791
Jukebox now playing from: MicrobeStage
Jukebox: starting track: res://assets/sounds/microbe-theme-3.ogg position: 365,8478
Jukebox: starting track: res://assets/sounds/soundeffects/microbe-ambience.ogg position: 255,8723
Creating a save with name: auto_save_2.thrivesave
save finished, success: True message: Speichern erfolgreich elapsed: 00:00:04.6356797
JSON trace written to: user://logs/json_debug.txt
There's a very long JSON trace, only written to: user://logs/json_debug.txt
JSON serialization trace: 2022-12-04T17:21:00.095 Info Started serializing SaveInformation. Path ''.

2022-12-04T17:21:00.096 Info Finished serializing SaveInformation. Path ''.

2022-12-04T17:21:00.096 Verbose Serialized JSON: 

{

  "ThriveVersion": "0.6.0.0-rc1",

  "Platform": "Windows",

  "Creator": "[SNM]Magician",

  "CreatedAt": "2022-12-04T17:20:56.6711488+01:00",

  "Description": "",

  "ID": "d9a761a8-a215-4fad-9aa8-4f0b64b36251",

  "Type": 1,

  "IsPrototype": false

}
Jukebox: starting track: res://assets/sounds/microbe-theme-6.ogg position: 0
Jukebox: starting track: res://assets/sounds/soundeffects/microbe-ambience2.ogg position: 0
Move to editor pressed
Starting microbe editor with: 7 organelles in the microbe
Elapsing time on editor entry
TimedWorldOperations: running effects. elapsed: 1 total passed: 600000000
Applying auto-evo results. Auto-evo run took: 00:00:00.5038051
Jukebox now playing from: MicrobeEditor
Creating a save with name: auto_save_5.thrivesave
save finished, success: True message: Speichern erfolgreich elapsed: 00:00:05.0799480
JSON trace written to: user://logs/json_debug.txt
There's a very long JSON trace, only written to: user://logs/json_debug.txt
JSON serialization trace: 2022-12-04T17:24:21.187 Info Started serializing SaveInformation. Path ''.

2022-12-04T17:24:21.187 Info Finished serializing SaveInformation. Path ''.

2022-12-04T17:24:21.187 Verbose Serialized JSON: 

{

  "ThriveVersion": "0.6.0.0-rc1",

  "Platform": "Windows",

  "Creator": "[SNM]Magician",

  "CreatedAt": "2022-12-04T17:24:17.0581402+01:00",

  "Description": "",

  "ID": "98bd2f7b-150a-4290-a5ab-b8f6ac7b243c",

  "Type": 1,

  "IsPrototype": false

}
Jukebox: starting track: res://assets/sounds/microbe-editor-theme-1.ogg position: 250,4795
Jukebox: starting track: res://assets/sounds/microbe-editor-theme-3.ogg position: 0
Placing organelle 'bindingAgent' at: 0, -3
Placing organelle 'mitochondrion' at: 0, 2
MicrobeEditor: applying changes to edited Species
MicrobeEditorReportComponent: applying changes of component
MicrobeEditorPatchMap: applying changes of component
CellEditorComponent: applying changes of component
Edited species name is now Primum thrivium
MicrobeEditor: updated organelles for species: Primum thrivium
Applying patch (Dolerurun Gezeitent�mpel) settings
Number of clouds in this patch = 9
Changing spawn density of glucose from 0,3542939 to 0,3188646
hydrogensulfide spawn density is 0. It won't spawn
oxygen spawn density is 0. It won't spawn
carbondioxide spawn density is 0. It won't spawn
nitrogen spawn density is 0. It won't spawn
sunlight spawn density is 0. It won't spawn
temperature spawn density is 0. It won't spawn
Number of chunks in this patch = 4
Number of species in this patch = 2
Changing spawn density of 1 from 0,274514 to 0,2753164
Changing spawn density of 2 from 0,2380791 to 0,2063154
Jukebox now playing from: MicrobeStage
Creating a save with name: auto_save_1.thrivesave
save finished, success: True message: Speichern erfolgreich elapsed: 00:00:05.5631194
JSON trace written to: user://logs/json_debug.txt
There's a very long JSON trace, only written to: user://logs/json_debug.txt
JSON serialization trace: 2022-12-04T17:25:57.970 Info Started serializing SaveInformation. Path ''.

2022-12-04T17:25:57.970 Info Finished serializing SaveInformation. Path ''.

2022-12-04T17:25:57.970 Verbose Serialized JSON: 

{

  "ThriveVersion": "0.6.0.0-rc1",

  "Platform": "Windows",

  "Creator": "[SNM]Magician",

  "CreatedAt": "2022-12-04T17:25:53.9470139+01:00",

  "Description": "",

  "ID": "80f8defb-5c94-4652-9ff0-681b0ef1a988",

  "Type": 1,

  "IsPrototype": false

}
Jukebox: starting track: res://assets/sounds/microbe-theme-6.ogg position: 133,0329
Jukebox: starting track: res://assets/sounds/soundeffects/microbe-ambience2.ogg position: 41,29089
Move to editor pressed
Starting microbe editor with: 7 organelles in the microbe
Elapsing time on editor entry
TimedWorldOperations: running effects. elapsed: 1 total passed: 700000000
Applying auto-evo results. Auto-evo run took: 00:00:01.1552698
Jukebox now playing from: MicrobeEditor
Creating a save with name: auto_save_2.thrivesave
save finished, success: True message: Speichern erfolgreich elapsed: 00:00:04.2383292
JSON trace written to: user://logs/json_debug.txt
There's a very long JSON trace, only written to: user://logs/json_debug.txt
JSON serialization trace: 2022-12-04T17:29:19.791 Info Started serializing SaveInformation. Path ''.

2022-12-04T17:29:19.791 Info Finished serializing SaveInformation. Path ''.

2022-12-04T17:29:19.791 Verbose Serialized JSON: 

{

  "ThriveVersion": "0.6.0.0-rc1",

  "Platform": "Windows",

  "Creator": "[SNM]Magician",

  "CreatedAt": "2022-12-04T17:29:16.5855421+01:00",

  "Description": "",

  "ID": "fb676f61-99e4-4eb6-9ff8-5e9937c693b5",

  "Type": 1,

  "IsPrototype": false

}
Jukebox: starting track: res://assets/sounds/microbe-editor-theme-3.ogg position: 61,77089
Placing organelle 'oxytoxy' at: 1, -2
Placing organelle 'chloroplast' at: 0, 3
MicrobeEditor: applying changes to edited Species
MicrobeEditorReportComponent: applying changes of component
MicrobeEditorPatchMap: applying changes of component
CellEditorComponent: applying changes of component
Edited species name is now Primum thrivium
MicrobeEditor: updated organelles for species: Primum thrivium
Applying patch (Dolerurun Gezeitent�mpel) settings
Number of clouds in this patch = 9
Changing spawn density of glucose from 0,3188646 to 0,2869781
hydrogensulfide spawn density is 0. It won't spawn
oxygen spawn density is 0. It won't spawn
carbondioxide spawn density is 0. It won't spawn
nitrogen spawn density is 0. It won't spawn
sunlight spawn density is 0. It won't spawn
temperature spawn density is 0. It won't spawn
Number of chunks in this patch = 4
Number of species in this patch = 3
Changing spawn density of 1 from 0,2753164 to 0,2751359
Registering new spawner: Name: 3 density: 0,2532348
Changing spawn density of 2 from 0,2063154 to 0,2519114
Jukebox now playing from: MicrobeStage
Creating a save with name: auto_save_5.thrivesave
Note: error lines may not match up when they happened in relation to normal output due to buffering.
Error lines are any lines received from the game's stderr output stream.
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: SPECIES_POPULATION chart missing datasets, aborting plotting data
ERROR: Index p_shape_index = 17 is out of bounds (total_subshapes = 16).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 17 is out of bounds (total_subshapes = 16).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 31 is out of bounds (total_subshapes = 27).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 31 is out of bounds (total_subshapes = 27).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 11 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Touched eligible microbe has disappeared before binding could start
ERROR: Touched eligible microbe has disappeared before binding could start
ERROR: Index p_shape_index = 12 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 12 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 12 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 12 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 12 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 12 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 12 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Touched eligible microbe has disappeared before binding could start
ERROR: Index p_shape_index = 15 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 15 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 19 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 15 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 15 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 12 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 12 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 12 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 12 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 11 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 11 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 11 is out of bounds (total_subshapes = 0).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: 
ERROR: Unhandled Exception:
ERROR: System.InvalidOperationException: Sequence contains no matching element
ERROR: 
ERROR:   at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00011] in <8dc7f7cf628440cbb575eaa126cc9c6d>:0 
ERROR: 
ERROR:   at CellEditorComponent.UndoOrganellePlaceAction (OrganellePlacementActionData data) [0x0002b] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at SingleEditorAction`1[T].UndoAction () [0x0000c] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at CombinedEditorAction.UndoAction () [0x00019] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at CombinedEditorAction.UndoAction () [0x00019] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at CombinedEditorAction.UndoAction () [0x00019] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at ReversibleAction.Undo () [0x00013] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at ActionHistory`1[T].Undo () [0x00026] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at EditorActionHistory`1[TAction].Undo () [0x00000] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at EditorActionHistory`1[TAction].PopTopAction () [0x00032] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at EarlyMulticellularEditor.CheckAndApplyCellTypeEdit () [0x00038] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at EarlyMulticellularEditor.ApplyEditorTab () [0x0008a] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at EditorBase`2[TAction,TStage].SetEditorTab (EditorTab tab) [0x00040] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at (wrapper managed-to-native) Godot.NativeCalls.godot_icall_2_695(intptr,intptr,string,object[])
ERROR: 
ERROR:   at Godot.Object.EmitSignal (System.String signal, System.Object[] args) [0x0000b] in <19daba5d5ae94c7483bcc78b7907d0ef>:0 
ERROR: 
ERROR:   at MicrobeEditorTabButtons.SetEditorTab (System.String tab) [0x00037] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: ------------ Begin of Unhandled Exception Log ------------
ERROR: The following exception prevented the game from running:
ERROR: 
ERROR: System.InvalidOperationException: Sequence contains no matching element
ERROR: 
ERROR:   at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00011] in <8dc7f7cf628440cbb575eaa126cc9c6d>:0 
ERROR: 
ERROR:   at CellEditorComponent.UndoOrganellePlaceAction (OrganellePlacementActionData data) [0x0002b] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at SingleEditorAction`1[T].UndoAction () [0x0000c] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at CombinedEditorAction.UndoAction () [0x00019] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at CombinedEditorAction.UndoAction () [0x00019] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at CombinedEditorAction.UndoAction () [0x00019] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at ReversibleAction.Undo () [0x00013] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at ActionHistory`1[T].Undo () [0x00026] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at EditorActionHistory`1[TAction].Undo () [0x00000] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at EditorActionHistory`1[TAction].PopTopAction () [0x00032] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at EarlyMulticellularEditor.CheckAndApplyCellTypeEdit () [0x00038] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at EarlyMulticellularEditor.ApplyEditorTab () [0x0008a] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at EditorBase`2[TAction,TStage].SetEditorTab (EditorTab tab) [0x00040] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at (wrapper managed-to-native) Godot.NativeCalls.godot_icall_2_695(intptr,intptr,string,object[])
ERROR: 
ERROR:   at Godot.Object.EmitSignal (System.String signal, System.Object[] args) [0x0000b] in <19daba5d5ae94c7483bcc78b7907d0ef>:0 
ERROR: 
ERROR:   at MicrobeEditorTabButtons.SetEditorTab (System.String tab) [0x00037] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR: Please provide us with this log, thank you.
save finished, success: True message: Speichern erfolgreich elapsed: 00:00:04.5068577
JSON trace written to: user://logs/json_debug.txt
There's a very long JSON trace, only written to: user://logs/json_debug.txt
JSON serialization trace: 2022-12-04T17:30:10.199 Info Started serializing SaveInformation. Path ''.

2022-12-04T17:30:10.199 Info Finished serializing SaveInformation. Path ''.

2022-12-04T17:30:10.199 Verbose Serialized JSON: 

{

ERROR: ------------  End of Unhandled Exception Log  ------------
  "ThriveVersion": "0.6.0.0-rc1",

  "Platform": "Windows",

  "Creator": "[SNM]Magician",

  "CreatedAt": "2022-12-04T17:30:07.1402275+01:00",

  "Description": "",

  "ID": "e16e2cd0-93e7-4833-bc1c-8d48717f1e5c",

  "Type": 1,

  "IsPrototype": false

}
Jukebox: starting track: res://assets/sounds/microbe-theme-6.ogg position: 333,8681
Jukebox: starting track: res://assets/sounds/soundeffects/microbe-ambience2.ogg position: 242,1261
Created a new colony
Jukebox: starting track: res://assets/sounds/microbe-theme-7.ogg position: 0
ERROR: 
ERROR: Unhandled Exception:
ERROR: System.InvalidOperationException: Sequence contains no matching element
ERROR: 
ERROR:   at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00011] in <8dc7f7cf628440cbb575eaa126cc9c6d>:0 
ERROR: 
ERROR:   at CellEditorComponent.UndoOrganellePlaceAction (OrganellePlacementActionData data) [0x0002b] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at SingleEditorAction`1[T].UndoAction () [0x0000c] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at CombinedEditorAction.UndoAction () [0x00019] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at CombinedEditorAction.UndoAction () [0x00019] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at CombinedEditorAction.UndoAction () [0x00019] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at ReversibleAction.Undo () [0x00013] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at ActionHistory`1[T].Undo () [0x00026] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at EditorActionHistory`1[TAction].Undo () [0x00000] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at EditorActionHistory`1[TAction].PopTopAction () [0x00032] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at EarlyMulticellularEditor.CheckAndApplyCellTypeEdit () [0x00038] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at EarlyMulticellularEditor.ApplyEditorTab () [0x0008a] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at EditorBase`2[TAction,TStage].SetEditorTab (EditorTab tab) [0x00040] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
ERROR: 
ERROR:   at (wrapper managed-to-native) Godot.NativeCalls.godot_icall_2_695(intptr,intptr,string,object[])
ERROR: 
ERROR:   at Godot.Object.EmitSignal (System.String signal, System.Object[] args) [0x0000b] in <19daba5d5ae94c7483bcc78b7907d0ef>:0 
ERROR: 
ERROR:   at MicrobeEditorTabButtons.SetEditorTab (System.String tab) [0x00037] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 
Becoming multicellular. NOTE: game is moving to prototype parts of the game, expect non-finished and buggy things!
Disbanding colony and becoming multicellular
Game is in now in prototypes. EXPECT MAJOR BUGS!
Moving species Primum thrivium (1) from MicrobeSpecies to EarlyMulticellularSpecies
Canceling and restarting auto-evo to have stage changed species versions in it
Switching to multicellular editor
Starting early multicellular editor with: 1 cells in the microbe
Jukebox now playing from: EarlyMulticellularEditor
Jukebox: starting track: res://assets/sounds/microbe-editor-theme-5.ogg position: 0
Elapsing time on editor entry
TimedWorldOperations: running effects. elapsed: 1 total passed: 800000000
Applying auto-evo results. Auto-evo run took: 00:00:02.0953934
New cell type created: UrStamm
New cell type created: Feet
Start editing cell type: Feet
Starting microbe editor with: 9 organelles in the microbe
Placing organelle 'flagellum' at: 0, 5
Creating cell type change action for type: Feet
Placing organelle 'flagellum' at: 0, 5
MicrobeEditor: updated organelles for cell: Feet
Undone / redone action affected cell types
MicrobeEditor: updated organelles for cell: Feet
Placing organelle 'flagellum' at: 0, 5
MicrobeEditor: updated organelles for cell: Feet
Undone / redone action affected cell types
MicrobeEditor: updated organelles for cell: Feet
Undone / redone action affected cell types
MicrobeEditor: updated organelles for cell: Feet
Placing organelle 'flagellum' at: -1, 5
Placing organelle 'flagellum' at: 0, 5
Creating cell type change action for type: Feet
Placing organelle 'flagellum' at: -1, 5
MicrobeEditor: updated organelles for cell: Feet
Start editing cell type: Stamm
Starting microbe editor with: 9 organelles in the microbe
Preview microbe already setup
Creating cell type change action for type: Stamm
MicrobeEditor: updated organelles for cell: Poison
Jukebox: starting track: res://assets/sounds/microbe-editor-theme-1.ogg position: 0
New cell type created: Hand
Start editing cell type: Hand
Starting microbe editor with: 9 organelles in the microbe
Preview microbe already setup
Placing organelle 'pilus' at: -1, -4
Creating cell type change action for type: Hand
MicrobeEditor: updated organelles for cell: Hand
Start editing cell type: Feet
Starting microbe editor with: 9 organelles in the microbe
Preview microbe already setup
Starting microbe editor with: 9 organelles in the microbe
Preview microbe already setup
Starting microbe editor with: 9 organelles in the microbe
Preview microbe already setup
Creating cell type change action for type: Poison
Starting microbe editor with: 9 organelles in the microbe
Preview microbe already setup
ERROR: src\steamnetworkingsockets\clientlib\steamnetworkingsockets_lowlevel.cpp (3243) : Trying to close low level socket support, but we still have sockets open!
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_lowlevel.cpp (3243) : Trying to close low level socket support, but we still have sockets open!
Child process exited with code 1
Thrive exited abnormally with an error
ERROR: Thrive has encountered an unhandled exception, please report this to us. In the future there will be support for automatically reporting these crashes.
Crash dumps have been detected but they may be from a previous Thrive run. To stop being notified about the crash dumps, please open the reporter and clear the crash dumps.
==== END OF LAUNCHER OUTPUT ====

Crash happened due to an unhandled exception:
------------ Begin of Unhandled Exception Log ------------
The following exception prevented the game from running:

System.InvalidOperationException: Sequence contains no matching element

  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00011] in <8dc7f7cf628440cbb575eaa126cc9c6d>:0 

  at CellEditorComponent.UndoOrganellePlaceAction (OrganellePlacementActionData data) [0x0002b] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 

  at SingleEditorAction`1[T].UndoAction () [0x0000c] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 

  at CombinedEditorAction.UndoAction () [0x00019] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 

  at CombinedEditorAction.UndoAction () [0x00019] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 

  at CombinedEditorAction.UndoAction () [0x00019] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 

  at ReversibleAction.Undo () [0x00013] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 

  at ActionHistory`1[T].Undo () [0x00026] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 

  at EditorActionHistory`1[TAction].Undo () [0x00000] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 

  at EditorActionHistory`1[TAction].PopTopAction () [0x00032] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 

  at EarlyMulticellularEditor.CheckAndApplyCellTypeEdit () [0x00038] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 

  at EarlyMulticellularEditor.ApplyEditorTab () [0x0008a] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 

  at EditorBase`2[TAction,TStage].SetEditorTab (EditorTab tab) [0x00040] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 

  at (wrapper managed-to-native) Godot.NativeCalls.godot_icall_2_695(intptr,intptr,string,object[])

  at Godot.Object.EmitSignal (System.String signal, System.Object[] args) [0x0000b] in <19daba5d5ae94c7483bcc78b7907d0ef>:0 

  at MicrobeEditorTabButtons.SetEditorTab (System.String tab) [0x00037] in <1a5d77ad7df64921933b3a1f8a920f4b>:0 

Please provide us with this log, thank you.
------------  End of Unhandled Exception Log  ------------
```

### PR DESCRIPTION
**Pull request by Kashnox**
**Brief Description of What This PR Does**

This PR applies changes to cell types in early multicellular editor when switching between them using undos and redos.

**Related Issues**

closes #3906 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
If this change actually works and fixes that bug, this is *much* simpler than what I expected the fix for that issue to be. Which is awesome.

**Comment by buckly90** [comment]
Hmmm, I am still getting the OrganelleTemplate Exception when reproducing the crash.

**Comment by buckly90** [comment]
Is there a precise way you recreated the crash you're fixing? A save you can toss over?

**Comment by Kashnox** [comment]
> Hmmm, I am still getting the OrganelleTemplate Exception when reproducing the crash.
> 
> Or maybe it's the _other_ crash ([3836](https://github.com/Revolutionary-Games/Thrive/issues/3836)) I'm triggering. God these two are confusing.
Yeah, in hindsight, I probably should have just fixed both errors on the same branch. The OrganelleTemplate error happens when the center of mass for the cell changes, so if you can make changes without changing the center of mass, you can cause the error this PR fixes. 
I have a save file that can easily reproduce it that I can send you later today.

File: src/early_multicellular_stage/editor/EarlyMulticellularEditor.cs [hunk 1]
```diff
@@ -555,16 +555,26 @@ private void UndoEndCellTypeEditAction(EndCellTypeEditActionData data)
...
-        // This fixes complex cases where multiple types are redoing actions
-        selectedCellTypeToEdit = data.StartedCellTypeEdit;
-        cellEditorTab.OnEditorSpeciesSetup(EditedBaseSpecies);
+        SwapEditingCell(data.StartedCellTypeEdit);
     }
 
     [DeserializedCallbackAllowed]
     private void UndoStartCellTypeEditAction(StartCellTypeEditActionData data)
     {
+        SwapEditingCell(data.StartedCellTypeEdit);
```
Comment (hhyyrylainen) [inline src/early_multicellular_stage/editor/EarlyMulticellularEditor.cs:564]: Hang on, help me understand what's going on here... So the way this works is that when a cell start action is undone, it still swaps to that cell type edit? If I remember right the undo history should be something like:
```
start cell type|organelle edit|end cell type|start different cell type|organelle edit
```
and going back in the history for a start cell type being undone should already work. Well I guess it doesn't really work if this change fixes the crash (I originally thought this was not necessary). The clarification on why this is necessary hit to performance (needing to start a cell type edit just to overwrite it immediately afterwards) should then be put in the code.

**Comment by Kashnox** [comment]
I found another way to trigger this crash related to the way EndCellTypeEditActions are combined. I think I have a fix for it, but I'm going to make this a draft until I have time to test that more thoroughly.

**Comment by Kashnox** [comment]
[Plants.zip](https://github.com/Revolutionary-Games/Thrive/files/12705374/Plants.zip)
I ended up doing a pretty big rework of the way we handle switching back and forth between cell types in the multicellular editor.

I removed the EndCellTypeEditAction and StartCellTypeEditAction entirely and started tracking which edit belongs to which cell inside the action data using the Context property. Then, when an action belonging to a different cell is undone or redone, the changes to the current cell are applied and the editor switches to the other cell.

The undo/redo buttons still won't move the player from the cell type editor to the body plan editor. That's covered in issue #3910, but it should be easier to fix with the changes from this PR.

I attached the save I've been using to test this. If you become multicellular immediately after loading, you can safely remove the Signaling Agent and the Pilus without causing the crash from #3836.

**Comment by buckly90** [comment]
I smashed those buttons as much as I could and had no luck triggering the crash with various configurations. Looks like we've got a fix, excellent job!

**Comment by hhyyrylainen** [comment]
I think that context approach is good to take, and the way this PR should be done. I think my earlier design was too complicated to get correct (well at least without very extensive unit testing which we don't have currently, but maybe would someday). Similarly to how the editor action combining for minimum cost is a super complicated design that has required a ton of thinking from multiple people to get it as good as it is right now.

File: src/microbe_stage/editor/action_data/EditorCombinableActionData.cs [hunk 2]
```diff
@@ -22,3 +22,21 @@ public override CombinableActionData Combine(CombinableActionData other)
 
     protected abstract int CalculateCostInternal();
 }
+
+public abstract class EditorCombinableActionData<TContext> : EditorCombinableActionData
+{
+    /// <summary>
+    ///   What this action was performed on.
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/action_data/EditorCombinableActionData.cs:29]: Isn't this comment wrong? Shouldn't this be something like "The optional context this action was performed in. This is additional data in addition to the action target. Not all editors use context info." something like that.

File: src/microbe_stage/editor/CellEditorComponent.cs [hunk 3]
```diff
@@ -1865,9 +1865,8 @@ private void UpdateAlreadyPlacedVisuals()
 
         // TODO: The code below is partly duplicate to CellHexPhotoBuilder. If this is changed that needs changes too.
         // Build the entities to show the current microbe
-        UpdateAlreadyPlacedHexes(
-            editedMicrobeOrganelles.Select(o => (o.Position, o.RotatedHexes, Editor.HexPlacedThisSession(o))), islands,
-            microbePreviewMode);
+        UpdateAlreadyPlacedHexes(editedMicrobeOrganelles.Select(o => (o.Position, o.RotatedHexes,
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/CellEditorComponent.cs:1868]: Was this reformatting of code necessary? I think this reduces readability.

File: src/late_multicellular_stage/editor/action_data/MetaballResizeActionData.cs [hunk 4]
```diff
@@ -1,7 +1,7 @@
 ﻿using System;
 using Godot;
 
-public class MetaballResizeActionData<TMetaball> : EditorCombinableActionData
+public class MetaballResizeActionData<TMetaball> : EditorCombinableActionData<LateMulticellularSpecies>
```
Comment (hhyyrylainen) [inline src/late_multicellular_stage/editor/action_data/MetaballResizeActionData.cs:4]: Does this need the context info? Can the metaball edit actions be left without a context?

File: src/microbe_stage/editor/action_data/EditorCombinableActionData.cs [hunk 5]
```diff
@@ -22,3 +22,21 @@ public override CombinableActionData Combine(CombinableActionData other)
...
+    /// </summary>
+    public TContext? Context { get; set; }
+
+    public override ActionInterferenceMode GetInterferenceModeWith(CombinableActionData other)
+    {
+        // If the other action was performed on a different context, we can't combine with it
+        if (other is not EditorCombinableActionData<TContext> editorActionData || editorActionData.Context is null ||
+            !editorActionData.Context.Equals(Context))
+            return ActionInterferenceMode.NoInterference;
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/action_data/EditorCombinableActionData.cs:38]: Multiline if should have braces

File: src/early_multicellular_stage/editor/EarlyMulticellularEditor.cs [hunk 6]
```diff
@@ -155,6 +149,48 @@ public override bool CancelCurrentAction()
         return false;
     }
 
+    public override void Redo()
+    {
+        CellType? cellType = null;
+
+        // We don't allow combining actions from different contexts,
+        // so we only need to check the first data for the cell type
+        var redoData = history.ActionToRedo()?.Data.FirstOrDefault();
```
Comment (hhyyrylainen) [inline src/early_multicellular_stage/editor/EarlyMulticellularEditor.cs:158]: This seems like duplicated code with Undo, and I think also with the late multicellular editor I saw similar changes. Could this maybe be made into a generic method in the action history to check if the context is changed (and return the new context value)?

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
I think the approach is now good, but I have some tweak suggestions. I didn't review all of the files yet as I have a few general comments that will if done the way I envision change the two files I didn't review yet quite a bit.

File: src/late_multicellular_stage/editor/action_data/MetaballResizeActionData.cs (hunk 4 above)
Comment (Kashnox) [reply src/late_multicellular_stage/editor/action_data/MetaballResizeActionData.cs:4]: I added that in because I thought we might need it when we start working on the late multicellular editor, but I'll take it out to reduce the number of changed files.

Comment (hhyyrylainen) [reply src/late_multicellular_stage/editor/action_data/MetaballResizeActionData.cs]: That'd be better I think, because I can't foresee needing this for the reason that the metaball actions are related to the metaballs that are placed, their context would always be related to the species that is being edited (I never want to have to refactor the editors to support editing multiple species at once).

**Review by hhyyrylainen — APPROVED** [review]
The code change looks good to me now. I assume the testing results are still valid so this can be merged in order for us to move onto that other multicellular editor crash PR.
