### PR TITLE
Fix auto evo editor prediction mistakenly requiring occupied leaf nodes

### LINKED ISSUE #6699: Auto-evo (editor prediction) not calculating for unfilled miche leaf nodes
I've mentioned this elsewhere, but I have been thus far unable to solve this, and I think it would be good to track this problem more generally, since it's technically a general bug (not limited to the mentioned PR):

It seems there is a bug that makes Auto-evo prediction not take into account any energy source that is not already being used by a species (including the player themselves). That is a per-patch condition. This is quite apparent in the auto-evo in-editor prediction if you turn off AI auto-evo. I don't know for sure if that also affects real Auto-evo results (but it has been said that the calculations should be exactly the same), but either way it does not seem ideal.

The only reason it does not stand out so much in master is that there is some method that kind of force-evolves species to fill the available miches (more so for food sources than predation). These are the ones that show up in the editoy report as "X split off to fill a niche" rather than "split off due to differing selection pressures". But even with that, I have noticed this bug in the past, for example when moving to a new surface patch while having or placing a thylakoid before other photosynthesizers exist there. In that case, auto-evo prediction in the editor does not detect any energy gain.

This is not a bug caused by this PR. But this PR does not seem to show the "forced evolution" I mentioned before, and those are masking the bug in master.

So I do suspect that this issue is also affecting "real" auto-evo (not just player predictions), because without the forced evolutions, creation of new species that use the other energy sources is pretty much stalled for the first few generations in this PR.

Long story short, I can probably not properly balance PR unless that bug is fixed or the forced evolution can be included here.

This is blocking #6209 

I have been able to confirm that the editor prediction is still calling the score calculations for most of therelevant miche nodes, just not for the *leaf* miche nodes (the ones at the end of the tree, that also contain energy distribution).

### PR DESCRIPTION
**Pull request by Accidental-Explorer**
**Brief Description of What This PR Does**

This PR makes it so auto-evo no longer require a current occupant in order to calculate a score for a leaf node, and instead assumes the "occupant's score" is 0 if there isn't one.

This will mainly apparent when looking at the editor auto-evo prediction numbers while moving to a new empty patch, since by definition none of its miches have occupants yet.

**Related Issues**

closes #6699 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/auto-evo/simulation/MichePopulation.cs [hunk 1]
```diff
@@ -273,8 +272,14 @@ private static void SimulatePatchStep(SimulationConfiguration simulationConfigur
...
 
-                    var occupantScore =
-                        cache.GetPressureScore(currentMiche.Pressure, patch, (MicrobeSpecies)node.Occupant!);
+                    var occupantScore = 0.0f;
+
+                    // TODO: When supporting multicellular species replace the is MicrobeSpecies with a null check
+                    if (currentMiche.Occupant is MicrobeSpecies)
+                    {
+                        occupantScore =
+                            cache.GetPressureScore(currentMiche.Pressure, patch, (MicrobeSpecies)node.Occupant!);
```
Comment (hhyyrylainen) [inline src/auto-evo/simulation/MichePopulation.cs]:
```suggestion
                    if (currentMiche.Occupant is MicrobeSpecies microbeSpecies)
                    {
                        occupantScore =
                            cache.GetPressureScore(currentMiche.Pressure, patch, microbeSpecies);
```

I believe this would be the right syntax to use the cast result directly rather than doing the second cast and null suppression.

Actually hang on, you use `(MicrobeSpecies)node.Occupant!` which is not the same as `currentMiche.Occupant`, right? So this code assumes that if a microbe holds the miche then the node also must have a microbe in it? I suppose this is a somewhat safe assumption right now but might not work in the future...

File: src/auto-evo/simulation/MichePopulation.cs [hunk 2]
```diff
@@ -273,8 +272,14 @@ private static void SimulatePatchStep(SimulationConfiguration simulationConfigur
...
 
-                    var occupantScore =
-                        cache.GetPressureScore(currentMiche.Pressure, patch, (MicrobeSpecies)node.Occupant!);
+                    var occupantScore = 0.0f;
+
+                    // TODO: When supporting multicellular species replace the is MicrobeSpecies with a null check
+                    if (currentMiche.Occupant is MicrobeSpecies occupantMicrobeSpecies)
+                    {
+                        occupantScore =
+                            cache.GetPressureScore(currentMiche.Pressure, patch, occupantMicrobeSpecies);
```
Comment (hhyyrylainen) [inline src/auto-evo/simulation/MichePopulation.cs:283]: What about the removed `node` usage here? This variant now takes the data from a different source. Is that still correct, or was the previous version the more correct one?

File: src/auto-evo/simulation/MichePopulation.cs (hunk 1 above)
Comment (Accidental-Explorer) [reply src/auto-evo/simulation/MichePopulation.cs]: Well, your proposed syntax does seem to work fine right now, so I set it to that.

In this case, we are now checking if the miche has an occupier, and if so what the score is. As long as there is an occupier, that means the species exists in the patch, so GetPressureScore should do fine?

Comment (hhyyrylainen) [reply src/auto-evo/simulation/MichePopulation.cs]: Well yes, that's what the code does now, but before it looked at the `node` object and took its occupant, which may not have been the same as `currentMiche.Occupant`...

File: src/auto-evo/simulation/MichePopulation.cs (hunk 2 above)
Comment (Accidental-Explorer) [reply src/auto-evo/simulation/MichePopulation.cs:283]: Oh, you're right, those are definitely two different things. Occupant of the leaf node, versus occupant of every node on the way back up (not even sure if those can have occupants). I think I should actually change the check I put in to also use node.Occupant, let me see.

Comment (Accidental-Explorer) [reply src/auto-evo/simulation/MichePopulation.cs:283]: > What about the removed `node` usage here? This variant now takes the data from a different source. Is that still correct, or was the previous version the more correct one?

The new version I just pushed preserves the node usage, makes the check use the same, and reads the data a bit less often.

**Comment by Accidental-Explorer** [comment]
> Might be worth double checking that everything works in multicell, but It should be fine.

I did test this myself and nothing broke.
