### PR TITLE
Fix for duplicate cell division when leaving editor.

### LINKED ISSUE #1497: Sometimes returning from the editor spawns an extra daughter cell
When exiting the editor there should be 2 player species cells on screen, sometimes there's a third one, which shouldn't spawn.

### PR DESCRIPTION
**Pull request by Satharis**
Implemented the fix suggested in the linked issue. NPC cells now only receive up to 90% of reproductive compounds required to divide again.
Closes #1497

### CODE REVIEW

File: src/microbe_stage/Microbe.cs [hunk 1]
```diff
@@ -789,21 +789,55 @@ public void Divide()
         copyEntity.Compounds.ClearCompounds();
 
         var keys = new List<Compound>(Compounds.Compounds.Keys);
+        var reproductionCompounds = CalculateTotalCompounds();
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:792]: This would be better to be called on `copyEntity` as that doesn't have the duplicated organelles in it, thought that doesn't break things, I still think that would be nicer
`var reproductionCompounds = copyEntity.CalculateTotalCompounds();`

File: src/microbe_stage/Microbe.cs [hunk 2]
```diff
@@ -789,21 +789,55 @@ public void Divide()
...
 
-        // Split the compounds evenly between the two cells.
+        // Split the compounds between the two cells.
         foreach (var compound in keys)
         {
             var amount = Compounds.GetCompoundAmount(compound);
 
             if (amount > 0)
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:799]: The indentation level starts to be a bit high in this loop.
I think this if doesn't have an else. Would be nicer now to swap this around so that
``` 
if (amount <= 0)
    continue;
```

File: src/microbe_stage/Microbe.cs [hunk 3]
```diff
@@ -789,21 +789,55 @@ public void Divide()
...
             {
-                Compounds.TakeCompound(compound, amount * 0.5f);
+                float divideAmount;
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:801]: This can be inlined in the out specification

File: src/microbe_stage/Microbe.cs [hunk 4]
```diff
@@ -789,21 +789,55 @@ public void Divide()
...
+                    {
+                        // Player microbes only lose half of reproductive compounds.
+                        Compounds.TakeCompound(compound, amount * 0.5f);
+                    }
+                    else
+                    {
+                        // NPC cells may not keep more than 90% of the amount of compound required to divide,
+                        // so they may lose more than half.
+                        float amountToTake = Math.Max(amount * 0.5f, amount - (divideAmount * 0.9f));
+                        Compounds.TakeCompound(compound, amountToTake);
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:818]: I'd prefer just a single call to Compounds.TakeCompound, done something like this:
```
float amountToTake = amount * 0.5f;

if(!IsPlayerMicrobe)
{
    amountToTake = ...;
}

Compounds.TakeCompound(compound, amountToTake);
```

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
The functionality looks fine. Just have some code style and few specific detail related comments.

File: src/microbe_stage/Microbe.cs (hunk 3 above)
Comment (Satharis) [reply src/microbe_stage/Microbe.cs:801]: That one I definitely didn't know, hahah.

File: src/microbe_stage/Microbe.cs (hunk 1 above)
Comment (Satharis) [reply src/microbe_stage/Microbe.cs:792]: I changed this already but I don't think the player has the duplicates either since I believe it resets it before calling divide?

Comment (hhyyrylainen) [reply src/microbe_stage/Microbe.cs]: I'm mainly commenting as we are interested specifically in what compounds the new cell needs for dividing, so it is clearer to ask that cell "hey, what do you need to divide?" than assume it is the same as for this.

Comment (Satharis) [reply src/microbe_stage/Microbe.cs]: Yeah I get where you're coming from, though with how it's coded it technically clamps both cells just in case something crazy happened and the parent NPC cell ended up with a ton of compounds again.

File: src/microbe_stage/Microbe.cs [hunk 5]
```diff
@@ -789,14 +789,41 @@ public void Divide()
...
+
+                if (!IsPlayerMicrobe)
+                {
+                    // NPC cells are capped at 90% of the amount of compound required to divide.
+                    amountToTake = Math.Max(amountToTake, amount - (divideAmount * 0.9f));
+                }
+
+                Compounds.TakeCompound(compound, amountToTake);
+
+                float amountToGive = Math.Min(amount * 0.5f, divideAmount * 0.9f);
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:816]: Shouldn't this be the other way around?
Because this method runs in the player cell.
So when the case is that `IsPlayerCell` then we need to cap the amountToTake from that cell, and then when we do that the amount to give should be equal to amountToTake. Something like:

```
if (!IsPlayerMicrobe)
{
    amountToTake = Math.Min(amountToTake, divideAmount * 0.9f);
}

Compounds.TakeCompound(compound, amountToTake);
var didntFit = copyEntity.Compounds.AddCompound(compound, amountToTake);
```

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

File: src/microbe_stage/Microbe.cs (hunk 5 above)
Comment (hhyyrylainen) [reply src/microbe_stage/Microbe.cs:816]: The functionality in-game seemed fine but I can't wrap my head around the logic which way around the math should be to confirm that the amount taken and amount given to the other cell are equal, and that the non player cell won't end up with enough to reproduce.

Comment (Satharis) [reply src/microbe_stage/Microbe.cs:816]: How it works right now is if the parent cell is a player they get 1/2 the compounds, always. If its an NPC cell they either get half taken away or 90% of divideAmount, whichever is larger. The child cell is always an NPC cell so it gets the same treatment but reversed, adding instead of taking away.

Comment (hhyyrylainen) [reply src/microbe_stage/Microbe.cs:816]: With that explanation I can see that. Could you add like 2-3 clarifying comments in the code as that logic is pretty hard to unpack otherwise?

Comment (Satharis) [reply src/microbe_stage/Microbe.cs]: Is that better?

**Review by hhyyrylainen — APPROVED** [review]

**Comment by hhyyrylainen** [comment]
Looks better now.
Btw as you have now done a couple of PRs you can use those as the work samples for joining the team (https://revolutionarygamesstudio.com/application/), if you want. No pressure to join, you can continue doing PRs without joining the team.
