### PR TITLE
Fixed MP issue, rigidity slider also rounds correctly, mobility label rounds correctly

### LINKED ISSUE #1480: Investigate what drains 1 MP sometimes when entering the editor
My guess that it is caused by some of the bars snapping to a different value on entry, this should be investigated and fixed so that it doesn't drain ATP.

Kuvakaappaus - 2020-07-25 13-42-27

### PR DESCRIPTION
**Pull request by icedjuro**
Closes #1480 
Also fixed some other issues like the slider cost 4 MP at certain points because it rounded poorly, or the labels would show something like 0.0800000001 because of floating point division. Should be fixed now.

### CODE REVIEW

File: src/microbe_stage/editor/MicrobeEditorGUI.cs [hunk 1]
```diff
@@ -471,8 +471,8 @@ public void SetRigiditySliderTooltip(float rigidity)
         var healthChangeLabel = GetNode<Label>(RigiditySliderTooltipHealthLabelPath);
         var mobilityChangeLabel = GetNode<Label>(RigiditySliderTooltipSpeedLabelPath);
 
-        float healthChange = rigidity * Constants.MEMBRANE_RIGIDITY_HITPOINTS_MODIFIER;
-        float mobilityChange = -1 * rigidity * Constants.MEMBRANE_RIGIDITY_MOBILITY_MODIFIER;
+        float healthChange = (float)((decimal)rigidity * (decimal)Constants.MEMBRANE_RIGIDITY_HITPOINTS_MODIFIER);
+        float mobilityChange = (float)(-1 * (decimal)rigidity * (decimal)Constants.MEMBRANE_RIGIDITY_MOBILITY_MODIFIER);
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditorGUI.cs:475]: Wouldn't `double` be enough, according to wiki decimal is 128 bit type? I don't think that kind of floating point has hardware acceleration, and I think it's rarely used so this code is a bit confusing. Double won't be confusing to anyone reading this.

File: src/microbe_stage/editor/MicrobeEditorGUI.cs [hunk 2]
```diff
@@ -774,11 +774,11 @@ internal void UpdateRigiditySlider(float value, int mutationPoints)
             rigiditySlider.Editable = false;
         }
 
-        rigiditySlider.Value = value;
+        rigiditySlider.Value = value * 10;
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditorGUI.cs:777]: It would make more sense if the value was passed as an int to this method. Because OnRigidityChanged sends the value to the editor as is, it would make sense if the value the editor sends here was int as well.

File: src/microbe_stage/editor/MicrobeEditorGUI.cs [hunk 3]
```diff
@@ -765,7 +765,7 @@ internal void UpdateMembraneButtons(string membrane)
 
     internal void UpdateRigiditySlider(float value, int mutationPoints)
     {
-        if (mutationPoints > 0)
+        if (mutationPoints >= 5)
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditorGUI.cs:768]: Please make the amount of MP it costs per step a value in Constants.
Also I think the cost should be something like 2 MP per step so that it is easier to consume all the remaining MP.

File: src/microbe_stage/editor/MicrobeEditorGUI.cs [hunk 4]
```diff
@@ -471,8 +471,8 @@ public void SetRigiditySliderTooltip(float rigidity)
         var healthChangeLabel = GetNode<Label>(RigiditySliderTooltipHealthLabelPath);
         var mobilityChangeLabel = GetNode<Label>(RigiditySliderTooltipSpeedLabelPath);
 
-        float healthChange = rigidity * Constants.MEMBRANE_RIGIDITY_HITPOINTS_MODIFIER;
-        float mobilityChange = -1 * rigidity * Constants.MEMBRANE_RIGIDITY_MOBILITY_MODIFIER;
+        float healthChange = (float)Math.Round(rigidity * Constants.MEMBRANE_RIGIDITY_HITPOINTS_MODIFIER, 2);
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditorGUI.cs:474]: Rounding should be done when converting to string, for example `number.ToString("F3", CultureInfo.CurrentCulture)`
I think that works

File: src/microbe_stage/editor/MicrobeEditor.cs [hunk 5]
```diff
@@ -647,22 +647,19 @@ public void SetMembrane(string membraneName)
         gui.UpdateMembraneButtons(Membrane.InternalName);
     }
 
-    public void SetRigidity(float rigidity)
+    public void SetRigidity(int rigidity)
     {
-        if (Math.Abs(Rigidity - rigidity) < MathUtils.EPSILON)
+        if (Math.Abs(Rigidity * 10 - rigidity) < MathUtils.EPSILON * 10)
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditor.cs:652]: I'd prefer the opposite check. ie. convert Rigidity to int and then compare if the ints are the same.
Also multiplying the EPSILON is not good, it's meant to be a value close to zero to check if a float is basically.

File: src/microbe_stage/editor/MicrobeEditor.cs [hunk 6]
```diff
@@ -647,22 +647,19 @@ public void SetMembrane(string membraneName)
...
             return;
 
-        var cost = (int)(Math.Abs(rigidity - Rigidity) / 2 * 100);
+        int cost = (int)(Math.Abs(rigidity - Rigidity * 10) / 2 * 10);
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditor.cs:655]: Also calculating the cost between ints (and using a constant for MP per rigidity step) will be much nicer here.

File: src/microbe_stage/editor/MicrobeEditor.cs [hunk 7]
```diff
@@ -647,22 +647,19 @@ public void SetMembrane(string membraneName)
...
 
         if (cost > 0)
         {
             if (cost > MutationPoints)
-            {
-                rigidity = Rigidity + (rigidity < Rigidity ? -MutationPoints : MutationPoints) * 2 / 100.0f;
-                cost = MutationPoints;
-            }
+                return;
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditor.cs:660]: I think this should change send feedback to the bar to go back to the previous value.

File: src/microbe_stage/editor/MicrobeEditor.cs [hunk 8]
```diff
@@ -647,35 +647,37 @@ public void SetMembrane(string membraneName)
...
+    public void SetRigidity(int rigidity)
     {
-        if (Math.Abs(Rigidity - rigidity) < MathUtils.EPSILON)
+        int intRigidity = (int)(Rigidity * 10);
+
+        if (Math.Abs(intRigidity - rigidity) < MathUtils.EPSILON)
             return;
 
-        var cost = (int)(Math.Abs(rigidity - Rigidity) / 2 * 100);
+        int cost = (int)(Math.Abs(rigidity - intRigidity) * Constants.MEMBRANE_RIGIDITY_COST_PER_STEP);
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditor.cs:657]: I don't think the int cast here is necessary and should be removed for clarity.

File: src/microbe_stage/editor/MicrobeEditor.cs [hunk 9]
```diff
@@ -647,35 +647,37 @@ public void SetMembrane(string membraneName)
...
 
         if (cost > 0)
         {
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditor.cs:660]: This check can be removed as cost is non-zero always when rigidity != intRigidity

File: src/microbe_stage/editor/MicrobeEditor.cs [hunk 10]
```diff
@@ -647,35 +647,37 @@ public void SetMembrane(string membraneName)
...
             if (cost > MutationPoints)
             {
-                rigidity = Rigidity + (rigidity < Rigidity ? -MutationPoints : MutationPoints) * 2 / 100.0f;
-                cost = MutationPoints;
+                gui.UpdateRigiditySlider(intRigidity, MutationPoints);
+                return;
             }
 
-            var newRigidity = rigidity;
+            var newRigidity = rigidity / 10f;
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditor.cs:667]: `10.0f`

File: src/microbe_stage/editor/MicrobeEditor.cs [hunk 11]
```diff
@@ -647,35 +647,37 @@ public void SetMembrane(string membraneName)
...
             var prevRigidity = Rigidity;
 
             var action = new EditorAction(this, cost,
                 redo =>
                 {
                     Rigidity = newRigidity;
-                    gui.UpdateRigiditySlider(Rigidity, MutationPoints);
+                    gui.UpdateRigiditySlider((int)(Rigidity * 10), MutationPoints);
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditor.cs:674]: add a round here

File: src/microbe_stage/editor/MicrobeEditor.cs [hunk 12]
```diff
@@ -647,35 +647,37 @@ public void SetMembrane(string membraneName)
...
                     gui.UpdateSpeed(CalculateSpeed());
                 },
                 undo =>
                 {
                     Rigidity = prevRigidity;
-                    gui.UpdateRigiditySlider(Rigidity, MutationPoints);
+                    gui.UpdateRigiditySlider((int)(Rigidity * 10), MutationPoints);
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditor.cs:680]: and here

File: src/microbe_stage/editor/MicrobeEditorGUI.cs [hunk 13]
```diff
@@ -471,15 +471,15 @@ public void SetRigiditySliderTooltip(float rigidity)
         var healthChangeLabel = GetNode<Label>(RigiditySliderTooltipHealthLabelPath);
         var mobilityChangeLabel = GetNode<Label>(RigiditySliderTooltipSpeedLabelPath);
 
-        float healthChange = rigidity * Constants.MEMBRANE_RIGIDITY_HITPOINTS_MODIFIER;
-        float mobilityChange = -1 * rigidity * Constants.MEMBRANE_RIGIDITY_MOBILITY_MODIFIER;
+        string healthChange = (rigidity * Constants.MEMBRANE_RIGIDITY_HITPOINTS_MODIFIER).ToString("0.##", CultureInfo.CurrentCulture);
+        string mobilityChange = (-1 * rigidity * Constants.MEMBRANE_RIGIDITY_MOBILITY_MODIFIER).ToString("0.##", CultureInfo.CurrentCulture);
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditorGUI.cs:475]: Don't convert to string here

File: src/microbe_stage/editor/MicrobeEditorGUI.cs [hunk 14]
```diff
@@ -471,15 +471,15 @@ public void SetRigiditySliderTooltip(float rigidity)
...
 
-        healthChangeLabel.Text = ((healthChange > 0) ? "+" : string.Empty)
+        healthChangeLabel.Text = ((Convert.ToDouble(healthChange, CultureInfo.CurrentCulture) > 0) ? "+" : string.Empty)
             + healthChange.ToString(CultureInfo.CurrentCulture);
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditorGUI.cs:478]: add the format specifier to this ToString, also use "F3" as the specifier as I've used that elsewhere for consistency.

File: src/microbe_stage/editor/MicrobeEditorGUI.cs [hunk 15]
```diff
@@ -775,10 +775,10 @@ internal void UpdateRigiditySlider(float value, int mutationPoints)
         }
 
         rigiditySlider.Value = value;
-        SetRigiditySliderTooltip(value);
+        SetRigiditySliderTooltip(value / 10f);
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditorGUI.cs:778]: I feel like this change should be put into the `SetRigiditySliderTooltip` method, because this series of conversions doesn't make sense to me
editor (in float) -> comes to the GUI and is converted to int -> is converted back to float in order to display in the GUI

File: src/gui_common/thrive_theme.tres [hunk 16]
```diff
@@ -110,52 +110,15 @@ corner_radius_bottom_left = 5
...
 content_margin_top = 2.0
-bg_color = Color( 0.054902, 0.145098, 0.168627, 0.784314 )
-border_width_left = 1
-border_width_top = 1
-border_width_right = 1
-border_width_bottom = 1
-border_color = Color( 0.0666667, 0.6, 0.537255, 1 )
-corner_radius_top_left = 3
-corner_radius_top_right = 3
-corner_radius_bottom_right = 3
```
Comment (hhyyrylainen) [inline src/gui_common/thrive_theme.tres:137]: The theme is now broken. This changes how the options menu looks, how the popups look (including making their title unreadable). You should really review all of the deletions and subresources that are set to null by this PR so that things aren't broken.

File: src/microbe_stage/editor/MicrobeEditor.cs [hunk 17]
```diff
@@ -647,40 +647,39 @@ public void SetMembrane(string membraneName)
         gui.UpdateMembraneButtons(Membrane.InternalName);
     }
 
-    public void SetRigidity(float rigidity)
+    public void SetRigidity(int rigidity)
     {
-        if (Math.Abs(Rigidity - rigidity) < MathUtils.EPSILON)
+        int intRigidity = (int)Math.Round(Rigidity * 10);
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditor.cs:652]: I'd really like you replace all places with `10` in the changes with a named constant in Constants.

File: src/microbe_stage/editor/MicrobeEditor.cs [hunk 18]
```diff
@@ -647,40 +647,39 @@ public void SetMembrane(string membraneName)
...
 
-        if (cost > 0)
+        if (cost > MutationPoints)
         {
-            if (cost > MutationPoints)
-            {
-                rigidity = Rigidity + (rigidity < Rigidity ? -MutationPoints : MutationPoints) * 2 / 100.0f;
-                cost = MutationPoints;
-            }
+            gui.UpdateRigiditySlider(intRigidity, MutationPoints);
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditor.cs:661]: I think it would be nice if this went as far as possible, because I can think of a situation where the user presses a specific point on the bar, and that should move it as close as possible to the clicked point.

File: src/microbe_stage/editor/MicrobeEditorGUI.cs [hunk 19]
```diff
@@ -471,13 +471,13 @@ public void SetRigiditySliderTooltip(float rigidity)
         var healthChangeLabel = GetNode<Label>(RigiditySliderTooltipHealthLabelPath);
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditorGUI.cs:471]: This method should be changed to take the rigidity as an int

File: src/microbe_stage/editor/MicrobeEditorGUI.cs [hunk 20]
```diff
@@ -734,7 +734,7 @@ internal void OnMembraneSelected(string membrane)
 
         UpdateMembraneButtons(membrane.InternalName);
 
-        UpdateRigiditySlider(rigidity, editor.MutationPoints);
+        UpdateRigiditySlider((int)(rigidity * 10), editor.MutationPoints);
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditorGUI.cs:737]: This should use Math.round

**Comment by icedjuro** [comment]
The moving the bar as close as possible when you don't have enough could be it's own issue.

File: simulation_parameters/Constants.cs [hunk 21]
```diff
@@ -186,6 +186,16 @@ public static class Constants
     /// </summary>
     public const float ORGANELLE_GROW_STORAGE_MUST_HAVE_AT_LEAST = 0.0f;
 
+    /// <summary>
+    ///   Cost of moving the rigidity slider by one step in the microbe editor
+    /// </summary>
+    public const int MEMBRANE_RIGIDITY_COST_PER_STEP = 2;
+
+    /// <summary>
+    ///   Number used to convert between the valeu from the rigidity slider and the actual value
```
Comment (hhyyrylainen) [inline simulation_parameters/Constants.cs:195]: typo in this comment

File: simulation_parameters/Constants.cs [hunk 22]
```diff
@@ -186,6 +186,16 @@ public static class Constants
...
+    /// </summary>
+    public const int MEMBRANE_RIGIDITY_SLIDER_TO_VALUE_RATIO = 10;
```
Comment (hhyyrylainen) [inline simulation_parameters/Constants.cs:197]: Is this used by converting to float anywhere? If so it would make sense to have it as a float here to avoid a bunch of casts.

File: src/microbe_stage/editor/MicrobeEditorGUI.cs [hunk 23]
```diff
@@ -466,18 +466,20 @@ public void UpdateEnergyBalance(EnergyBalanceInfo energyBalance)
...
-    public void SetRigiditySliderTooltip(float rigidity)
+    public void SetRigiditySliderTooltip(int rigidity)
     {
         var healthChangeLabel = GetNode<Label>(RigiditySliderTooltipHealthLabelPath);
         var mobilityChangeLabel = GetNode<Label>(RigiditySliderTooltipSpeedLabelPath);
 
-        float healthChange = rigidity * Constants.MEMBRANE_RIGIDITY_HITPOINTS_MODIFIER;
-        float mobilityChange = -1 * rigidity * Constants.MEMBRANE_RIGIDITY_MOBILITY_MODIFIER;
+        float healthChange = rigidity * Constants.MEMBRANE_RIGIDITY_HITPOINTS_MODIFIER
+            / (float)Constants.MEMBRANE_RIGIDITY_SLIDER_TO_VALUE_RATIO;
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditorGUI.cs:475]: This part should be done once, introduce like a new local `float convertedRigidity` that's used here and on line 477.

**Comment by hhyyrylainen** [comment]
Follow up issue to improve the functionality: https://github.com/Revolutionary-Games/Thrive/issues/1499
