### PR TITLE
Fixed editor button not enabled after loading a save with full reproduction progress

### LINKED ISSUE #1351: Fix reproduction progress when loading a game when editor was available
I think I saw that if you are ready to go to the editor, save, and load, the reproduction progress bars are left empty.

### PR DESCRIPTION
**Pull request by Kasterisk**
Removes the `[JsonProperty]` attribute from `allOrganellesDivided` flag so the microbe code has a chance to run the `HandleReproduction` method once and notify the gui to activate the editor button after spawning from save. Previously its state was kept true already and the gui isn't aware that the player microbe is ready to split. So far I haven't seen any side effects from removing it.

Fixes #1351

### CODE REVIEW

File: src/microbe_stage/Microbe.cs [hunk 1]
```diff
@@ -123,7 +123,6 @@ public class Microbe : RigidBody, ISpawned, IProcessable, IMicrobeAI, ISaveLoade
     [JsonProperty]
     private Color flashColour = new Color(0, 0, 0, 0);
 
-    [JsonProperty]
     private bool allOrganellesDivided;
```
Comment (hhyyrylainen) [inline src/microbe_stage/Microbe.cs:126]: I wasn't initially super keen on this, but on further thinking, I think this is pretty elegant in the end. Though I want one change, this should have a comment along the lines of:
"True once all organelles are divided to not continuously run code that is triggered when a cell is ready to reproduce. This is not saved so that the player cell can enable the editor when loading a save where the player is ready to reproduce. If more code is added to be ran just once based on this flag, it needs to be made sure that that code re-running after loading a save is not a problem."

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

**Review by FuJa0815 — APPROVED** [review]
I've looked through the code and have not found any way this could break anything. Great fix!

**Comment by hhyyrylainen** [comment]
Could you maybe not run the localization update? As that causes most of the time extra merge conflicts. And on top of that this has the line number disparency in C# code between windows and linux.

**Comment by Kasterisk** [comment]
But isn't the line numbers actually correct? I see in the pot file that `SUCCESSFUL_SCAVENGE` is detected on line 1161 which is what's on the code, or perhaps I'm missing something? https://github.com/Revolutionary-Games/Thrive/blob/3c54665a1ffa5c035b885b8e0c448bf11e596c9f/locale/messages.pot#L1539 https://github.com/Revolutionary-Games/Thrive/blob/3c54665a1ffa5c035b885b8e0c448bf11e596c9f/src/microbe_stage/Microbe.cs#L1161 I've converted all the code files to use LF before running the script, and it doesn't change the other line numbers incorrectly now, so that's nice.

**Comment by Kasterisk** [comment]
Alright but yeah I agree that will probably cause unnecessary merge conflict, I'll revert it.

**Comment by hhyyrylainen** [comment]
> But isn't the line numbers actually correct? I see in the pot file that `SUCCESSFUL_SCAVENGE` is detected on line 1161 which is what's on the code, or perhaps I'm missing something?

Compared to master it isn't. Locally, on master, commit `7feeebc240783d8220cb378c05f13e26f80edcc5`. I have that on a different line. So if things were to be updated, the line numbers should be based of the latest stuff in master.

**Review by hhyyrylainen — APPROVED** [review]
