### PR TITLE
Fixed cloud spawning

### LINKED ISSUE #1210: Make sure that cloud spawns are properly changed on patch change
https://community.revolutionarygamesstudio.com/t/0-5-0-public-beta-godot-version/2617/13?u=hhyyrylainen

### PR DESCRIPTION
**Pull request by CoreyHendrey**
This appears to have fixed the issue. Let me know if you'd like it implemented a different way.

Compounds feel exceedingly rare in the second patch though. At first, I thought only iron was spawning, but upon respawning, I have seen other compounds. It could just be me - or a balancing issue.

Just to show that other compounds to actually spawn.

image

Closes #1210

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Do you mind also fixing this warning in this PR: `src/microbe_stage/PatchManager.cs(183,81): error SA1028: Code should not contain trailing whitespace [/var/lib/jenkins/workspace/Thrive-Jenkins-compile/Thrive.csproj]`
so that we'll get master build fixed?

**Comment by CoreyHendrey** [comment]
> Do you mind also fixing this warning in this PR: `src/microbe_stage/PatchManager.cs(183,81): error SA1028: Code should not contain trailing whitespace [/var/lib/jenkins/workspace/Thrive-Jenkins-compile/Thrive.csproj]`
> so that we'll get master build fixed?

Trying now, the white space doesn't exist there in my editor. Very strange.

**Comment by hhyyrylainen** [comment]
The jenkins build sometimes sees ghost changes from previous commits, I've tried setting even the option to delete workspace before each build, but nothing seems to help. Maybe I should just disable it at some point.

File: src/microbe_stage/PatchManager.cs [hunk 1]
```diff
@@ -245,6 +258,17 @@ private void ClearUnmarkedSingle(List<CreatedSpawner> spawners)
         });
     }
 
+    private void QueueUnmarkedForDestruction(List<CreatedSpawner> spawners)
+    {
+        foreach (CreatedSpawner spawner in spawners)
+        {
+            if (!spawner.Marked)
+            {
+                spawner.Spawner.DestroyQueued = true;
```
Comment (hhyyrylainen) [inline src/microbe_stage/PatchManager.cs:267]: I think that this could be merged with the RemoveNonMarkedSpawners, there's that one print statement anyway that triggers with the same condition, that way there's less of a chance of accidentally removing a spawner that wasn't queued for destruction.

Comment (CoreyHendrey) [reply src/microbe_stage/PatchManager.cs:267]: Yeah no problem, that is how I originally had it (in the first commit there) but was undecided on the best approach. I will change it back.

Comment (CoreyHendrey) [reply src/microbe_stage/PatchManager.cs]: Should fit the requirement now.
