### PR TITLE
Fixed multiple auto-evo exploration tool worlds and balance bar tutorial triggering on wrong tab

### LINKED ISSUE #4731: Auto-evo exploring tool worlds after the first now don't display the map
There's a regression from https://github.com/Revolutionary-Games/Thrive/pull/4670 when going to the auto-evo exploring tool, pressing run 10 generations and then pressing (after that completes) run 5 worlds, then going to the map tab it will be blank. This applies to all the worlds except the first for some reason.

### LINKED ISSUE #4736: ATP tutorial can trigger on the patch map tab
Causing the following:

### PR DESCRIPTION
**Pull request by ender-titan1**
**Brief Description of What This PR Does**

This PR fixes some problems that occurred with my fog-of-war and tutorials PRs.

**Related Issues**

Closes #4736 
Closes #4731

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [X] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by ARecurringProblem** [comment]
#4736 is a tough one to test. I've been playing this build for a few hours and haven't seen that issue come up yet so I can only assume this PR fixed it.

#4731 I can confirm that this was broken in the prior version and seems to work fine in this build.

**Review by ARecurringProblem — APPROVED** [review]
The fixes work and don't appear to break anything else

File: src/tutorial/microbe_editor/MicrobeEditorTutorialGUI.cs [hunk 1]
```diff
@@ -413,7 +413,7 @@ public void HandleShowingATPBarHighlight()
             throw new InvalidOperationException("Balance bar highlight control is not set");
 
         bool eitherVisible = atpBalanceIntroduction.Visible || negativeAtpBalanceTutorial.Visible;
-        AtpBalanceBarHighlight.Visible = atpBalanceIntroduction.Visible;
+        AtpBalanceBarHighlight.Visible = eitherVisible;
```
Comment (hhyyrylainen) [inline src/tutorial/microbe_editor/MicrobeEditorTutorialGUI.cs:416]: I specifically made this change as I found it to not be super nice to blank out the editor multiple times to show the location of the bars. Is this actually better? This doesn't let the player cross reference other information in the editor about their not enough ATP situation.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
This changes behaviour of one tutorial, which I want to confirm is intended before merging this.

File: src/tutorial/microbe_editor/MicrobeEditorTutorialGUI.cs (hunk 1 above)
Comment (hhyyrylainen) [reply src/tutorial/microbe_editor/MicrobeEditorTutorialGUI.cs:416]: Do you mind if I revert this one change so that all the other good parts can be merged?

Comment (ender-titan1) [reply src/tutorial/microbe_editor/MicrobeEditorTutorialGUI.cs:416]: Go right ahead

**Review by hhyyrylainen — APPROVED** [review]
I undid the one change I was unsure about.
