### PR TITLE
1652 Catch broken saves

### LINKED ISSUE #1652: Make save manager catch exceptions from trying to read invalid saves
to make the menu work while there are corrupt saves, so that the player can delete them

### PR DESCRIPTION
**Pull request by FuJa0815**
Closes #1652 

image
image

### CODE REVIEW

File: src/saving/Save.cs [hunk 1]
```diff
@@ -349,50 +359,3 @@ private static byte[] ReadBytesEntry(TarInputStream tar, int length)
...
-    /// </summary>
-    public string Description { get; set; } = string.Empty;
-
-    /// <summary>
-    ///   Unique ID of this save
-    /// </summary>
-    public Guid ID { get; set; } = Guid.NewGuid();
-
-    public SaveType Type { get; set; } = SaveType.Manual;
-}
```
Comment (FuJa0815) [inline src/saving/Save.cs:398]: I moved this class to a new file, because I derived from this class.

Comment (hhyyrylainen) [reply src/saving/Save.cs:398]: It's fine to be in a separate file, but I think deriving an invalid type from the class is not what I would have done. I would have made an additional constructor to create save info filled in with the invalid values.

File: src/saving/SaveListItem.cs [hunk 2]
```diff
@@ -189,6 +192,12 @@ public override void _GuiInput(InputEvent @event)
 
     public void LoadThisSave()
     {
+        if (type.Text == "Broken")
```
Comment (FuJa0815) [inline src/saving/SaveListItem.cs:195]: I'm not happy with this solution, but I didn't find another solution.

Comment (hhyyrylainen) [reply src/saving/SaveListItem.cs:195]: I think that the save shouldn't react to the invalid nature of the file. Instead loading *should* be attempted anyway.

Comment (FuJa0815) [reply src/saving/SaveListItem.cs]: A save is only broken if there is an exception when untaring or when a file in the tar cannot be loaded. This means, that the save is really broken and will crash the game.

Comment (hhyyrylainen) [reply src/saving/SaveListItem.cs]: Looking at the code, it seems possible that a save tar that is missing the info file will trigger an exception. However loading that save could work (I didn't look if the save loading also tries to read the info file, my memory says that it doesn't). So it's possible to have a broken save without the info but one that could load correctly.

File: src/saving/SaveInformation.cs [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+
+        /// <summary>
+        ///   Quick save, separate from manual to make it easier to keep a fixed number of quick saves
+        /// </summary>
+        QuickSave,
+
+        /// <summary>
+        ///   A broken save that cannot be loaded
+        /// </summary>
+        Broken,
```
Comment (hhyyrylainen) [inline src/saving/SaveInformation.cs:28]: I think this should be named Invalid instead, that sounds more like a more commonly used enum value name rather than broken.

File: src/saving/SaveList.cs [hunk 4]
```diff
@@ -188,6 +189,16 @@ private void OnNewSaveLoaded(string saveName)
...
     }
 
+    private void OnBrokenLoaded(string saveName)
+    {
+        saveToBeLoaded = saveName;
+
+        loadConfirmDialog.DialogText = "Thrive could not load this file.\n";
+        loadConfirmDialog.DialogText += "It seems like the save is broken.\n";
+        loadConfirmDialog.DialogText += "Do you want to try loading the save anyway?";
+        loadConfirmDialog.PopupCenteredMinsize();
```
Comment (hhyyrylainen) [inline src/saving/SaveList.cs:199]: The text should be included in the tscn file instead of here as it isn't dynamically generated.

File: src/saving/SaveListItem.cs [hunk 5]
```diff
@@ -172,6 +177,8 @@ public override void _Process(float delta)
         createdOnPlatform.Text = save.Info.Platform;
         description.Text = save.Info.Description;
 
+        isBroken = save.Info is BrokenSaveInformation;
```
Comment (hhyyrylainen) [inline src/saving/SaveListItem.cs:180]: This could use the save info type to determine if it is broken, instead of needing to rely on a subclass existing.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Unless I've completely missed it, you've forgotten to commit the scene file changes related to the new popup dialog.

File: src/saving/BrokenSaveInformation.cs [hunk 6]
```diff
@@ -0,0 +1,7 @@
+public class BrokenSaveInformation : SaveInformation
```
[the remark this answers is not in the document]
Comment (FuJa0815) [reply src/saving/BrokenSaveInformation.cs:1]: Do you mean ctor?
I have made a static create method in my commit

[the remark this answers is not in the document]
Comment (hhyyrylainen) [reply src/saving/BrokenSaveInformation.cs:1]: I don't see it? Have you pushed the latest code?
I just see that you use the default values from the subclass to do that.
I'd be fine with having a static create method to create a SaveInformation object representing a broken save.

File: src/saving/Save.cs [hunk 7]
```diff
@@ -194,32 +202,35 @@ private static void WriteDataToSaveFile(string target, string justInfo, string s
...
 
             // This deserializes a huge tree of objects
-            saveResult = ThriveJsonConverter.Instance.DeserializeObject<Save>(saveStr);
+            try
+            {
+                saveResult = ThriveJsonConverter.Instance.DeserializeObject<Save>(data.saveStr);
+            }
+            catch (Exception ex)
+            {
+                GD.PrintErr("Broken save game: " + ex.Message);
```
Comment (hhyyrylainen) [inline src/saving/Save.cs:222]: This should have a different error message, something like "Error deserializing save info object: "

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

File: src/saving/SaveList.cs (hunk 4 above)
Comment (FuJa0815) [reply src/saving/SaveList.cs:199]: But the other two dialogs also have their text set in code.
Should I move the text for the other dialogs as well?

Comment (hhyyrylainen) [reply src/saving/SaveList.cs:199]: But don't those include dynamic elements? I think they include the save name / some number.

Comment (FuJa0815) [reply src/saving/SaveList.cs:199]: I mean the other two dialogs right above my code

Comment (hhyyrylainen) [reply src/saving/SaveList.cs:199]: I let that slide as the text is different based on if the attempted save load is newer or older, but it uses the same callbacks.
Static text should be defined in the scene file.

Comment (FuJa0815) [reply src/saving/SaveList.cs:199]: But my dialog is also uses the same callbacks

Comment (hhyyrylainen) [reply src/saving/SaveList.cs:199]: I guess this is what I get for letting one PR I'm not absolutely happy with through...
Anyway for your use case the popup title should be different instead of "Load incompatible save?" it should mention that the save info could not be loaded.
I really want different purpose popups to be separate. If you check out the tutorial system, I created a separate box for *each* tutorial popup.

**Review by hhyyrylainen — APPROVED** [review]
I did a bunch of extra cleanup I wanted on this, didn't find any issues after testing with those changes.

File: src/saving/SaveList.tscn [hunk 8]
```diff
@@ -44,26 +46,46 @@ text = "Loading..."
...
 [node name="ItemList" type="VBoxContainer" parent="MarginContainer/VBoxContainer"]
-margin_right = 1356.0
+margin_right = 1270.0
 
-[node name="DeleteConfirmDialog" type="ConfirmationDialog" parent="MarginContainer/VBoxContainer"]
-margin_top = 4.0
-margin_right = 1356.0
-margin_bottom = 80.0
+[node name="DeleteSaveConfirmDialog" type="ConfirmationDialog" parent="MarginContainer/VBoxContainer"]
+margin_top = 15.0
```
Comment (hhyyrylainen) [inline src/saving/SaveList.tscn:52]: @Kasterisk I unset all of the margins except the margin_top to 0 to get the dialogs to be the right size again (instead of always the screen width). Is that the right way to go?

Comment (Kasterisk) [reply src/saving/SaveList.tscn:52]: Probably not since the margins will just get automatically overridden by something else. I would instead disable the dialogs `fill` size flags

Comment (hhyyrylainen) [reply src/saving/SaveList.tscn:52]: I'll give that a try, but it seems that according to this diff, I didn't change the size flags, so it wasn't right before.

Comment (hhyyrylainen) [reply src/saving/SaveList.tscn]: Okay, I changed them.

**Review by Kasterisk — APPROVED** [review]
Looks good
