### PR TITLE
ArgumentException: OrganelleTemplate can't be placed at this location when undoing can crash the game

### LINKED ISSUE #3836: ArgumentException: OrganelleTemplate can't be placed at this location when undoing can crash the game
Got a report that the game crashed with the following exception:
```
------------ Begin of Unhandled Exception Log ------------
The following exception prevented the game from running: System.ArgumentException: OrganelleTemplate can't be placed at this location at HexLayout`1[T].Add (T hex) [0x00022] 
in <370f4a10657247d4be2cb49d705e1ae2>:0 at CellEditorComponent.UndoOrganelleRemoveAction (OrganelleRemoveActionData data) [0x00000] in <370f4a10657247d4be2cb49d705e1ae2>:0 at SingleEditorAction`1[T].UndoAction () [0x0000c] 
in <370f4a10657247d4be2cb49d705e1ae2>:0 at CombinedEditorAction.UndoAction () [0x00019] 
in <370f4a10657247d4be2cb49d705e1ae2>:0 at CombinedEditorAction.UndoAction () [0x00019] 
in <370f4a10657247d4be2cb49d705e1ae2>:0 at CombinedEditorAction.UndoAction () [0x00019] 
in <370f4a10657247d4be2cb49d705e1ae2>:0 at ReversibleAction.Undo () [0x00013] 
in <370f4a10657247d4be2cb49d705e1ae2>:0 at ActionHistory`1[T].Undo () [0x00026] 
in <370f4a10657247d4be2cb49d705e1ae2>:0 at EditorActionHistory`1[TAction].Undo () [0x00000] 
in <370f4a10657247d4be2cb49d705e1ae2>:0 at EditorBase`2[TAction,TStage].Undo () [0x00009] 
in <370f4a10657247d4be2cb49d705e1ae2>:0 at EditorComponentWithActionsBase`2[TEditor,TAction].Undo () [0x00007] 
in <370f4a10657247d4be2cb49d705e1ae2>:0 at (wrapper managed-to-native) Godot.NativeCalls.godot_icall_2_695(intptr,intptr,string,object[]) at Godot.Object.EmitSignal (System.String signal, System.Object[] args) [0x0000b] in <19daba5d5ae94c7483bcc78b7907d0ef>:0 at EditorComponentBottomLeftButtons.UndoPressed () [0x00015] 
in <370f4a10657247d4be2cb49d705e1ae2>:0 
Please provide us with this log, thank you. 
------------ End of Unhandled Exception Log ------------
```

Likely caused by a very specific organelle layout and editing steps, I'll try to ask the reporter for any more details as otherwise this is going to be very difficult to track down.

Edit: actually, I was given the full log so it should be possible to read it to find out the organelle placements at least: https://pastebin.com/kRseUFbQ

### PR DESCRIPTION
**Pull request by Kashnox**
**Brief Description of What This PR Does**

This PR stops repositioning cells to their origin during multicellular editing until the entire multicellular editor is done, which prevents hex information in the action history from becoming outdated.

**Related Issues**

closes #3836 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by Kashnox** [comment]
If anyone tests this PR, watch out for the crash described here:
https://github.com/Revolutionary-Games/Thrive/issues/3906

It has similar steps to reproduce but has a different cause. I'll be looking into that issue next.

File: src/early_multicellular_stage/editor/CellBodyPlanEditorComponent.cs [hunk 1]
```diff
@@ -390,6 +390,13 @@ public override void OnFinishEditing()
         editedSpecies.UpdateNameIfValid(newName);
 
         behaviourEditor.OnFinishEditing();
+
+        foreach (var cellType in cellTypeSelectionButtons.Values)
```
Comment (hhyyrylainen) [inline src/early_multicellular_stage/editor/CellBodyPlanEditorComponent.cs:394]: I think this should instead loop through the cell types inside the species to not rely on GUI state being correct (i.e. if a button is missing for some reason or not detected it would still work, and I think going from simulation data -> GUI is a very good rule to follow and not do GUI -> simulation data transfer of information unless really necessary).

File: src/early_multicellular_stage/editor/CellBodyPlanEditorComponent.cs [hunk 2]
```diff
@@ -390,6 +390,13 @@ public override void OnFinishEditing()
...
+        {
+            // During multicellular editing, we don't reposition cells to the origin
+            // because it messes up the aciton history, so do it here once editing is finished
+            cellType.CellType.RepositionToOrigin();
```
Comment (hhyyrylainen) [inline src/early_multicellular_stage/editor/CellBodyPlanEditorComponent.cs:398]: This is not fully correct because rotation speed calculation (and maybe some other stats are dependent on organelle positions). So this re-apply of the edit would actually need to basically do everything that CellEditorComponent does on finishing editing.

Comment (Kashnox) [reply src/early_multicellular_stage/editor/CellBodyPlanEditorComponent.cs]: I double-checked that rotation speed is the only thing in CellEditorComponent.OnFinishEditing that depends on the organelle positions, so I just started updating that in CellBodyPlanComponent.OnFinishEditing too.

**Comment by Kashnox** [comment]
While testing the changes I made to clean up the code, I realized a crash with the same error message could be caused by undoing a move action from another cell, following these steps:

1. Duplicate Stem
2. Move any organelle in Stem
3. Start editing Stem2
4. Undo
5. Observe that the move was not undone
6. Redo
7. Crash

There was already a fix for this applied to most other actions (including redoing a move action), so I used that same fix here. I also verified any other actions that might cause this crash had the fix.

Because PR #4483 is merged into this PR now, the multicellular editor theoretically shouldn't crash at all anymore, at least under reasonable circumstances.

File: src/microbe_stage/MicrobeSpecies.cs [hunk 3]
```diff
@@ -102,6 +102,12 @@ public void CalculateRotationSpeed()
         BaseRotationSpeed = MicrobeInternalCalculations.CalculateRotationSpeed(Organelles);
     }
 
+    public void UpdatePositionalProperties()
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeSpecies.cs:105]: I added RepositionToOrigin to the base species type as I think it'll be useful for many stages. Related to that maybe CalculateRotationSpeed should be put in the RepositionToOrigin call (on line 98)? Is there a reason why reposition to origin would be done without also re-calculating the rotation speed?

**Comment by buckly90** [comment]
Failed to reproduce the crash with this PR. Very nice.

File: src/microbe_stage/MicrobeSpecies.cs (hunk 3 above)
Comment (Kashnox) [reply src/microbe_stage/MicrobeSpecies.cs:105]: Yeah, I don't think we'd ever want to call one without the other. It seems more likely for someone to do that on accident than on purpose.

File: src/microbe_stage/MicrobeSpecies.cs [hunk 4]
```diff
@@ -95,13 +95,19 @@ public override void OnEdited()
...
         Organelles.RepositionToOrigin();
+        CalculateRotationSpeed();
     }
 
     public void CalculateRotationSpeed()
     {
         BaseRotationSpeed = MicrobeInternalCalculations.CalculateRotationSpeed(Organelles);
     }
 
+    public void RecalculatePositionAndStatistics()
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeSpecies.cs:106]: I commented directly on the commit here that I think this method should be removed (all use of this should go through the base Species.RepositionToOrigin method).

Comment (Kashnox) [reply src/microbe_stage/MicrobeSpecies.cs:106]: MicrobeSpecies implements ICellProperties, so it has to have RecalculatePositionAndStatistics.

I could remove RecalculatePositionAndStatistics from ICellProperties and rework it so RepositionToOrigin calls CalculateRotationSpeed in every class that implements ICellProperties, so RepositionToOrigin would essentially become what RecalculatePositionAndStatistics is now.

Or, we can keep it how it is and accept that if you're interacting with a MicrobeSpecies as a cell, you call RecalculatePositionAndStatistics and if you're interacting with it as a species, you call RepositionToOrigin.

Either way works for me.

Comment (hhyyrylainen) [reply src/microbe_stage/MicrobeSpecies.cs:106]: I originally designed things to be symmetric between the cell properties and the species. So I'd prefer to just have RepositionToOrigin be the method name both in the species and the ICellProperties.

File: src/early_multicellular_stage/editor/CellBodyPlanEditorComponent.cs [hunk 5]
```diff
@@ -390,6 +390,13 @@ public override void OnFinishEditing()
         editedSpecies.UpdateNameIfValid(newName);
 
         behaviourEditor.OnFinishEditing();
+
+        foreach (var cellType in Editor.EditedSpecies.CellTypes)
```
Comment (hhyyrylainen) [inline src/early_multicellular_stage/editor/CellBodyPlanEditorComponent.cs:394]: Looking at the early multicellular species OnEdited method, it seems that is already does RepositionToOrigin for all cell types. So I think this code add here is basically a duplicate operation that is not necessary.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Just one tiny thing I now noticed when looking at the bit wider context. Should be very simple to fix.

File: src/early_multicellular_stage/editor/CellBodyPlanEditorComponent.cs (hunk 5 above)
Comment (Kashnox) [reply src/early_multicellular_stage/editor/CellBodyPlanEditorComponent.cs]: Yeah, everything gets repositioned just fine without that, so it wasn't needed.

**Review by hhyyrylainen — APPROVED** [review]
This should now be fine. I assume the testing results are still valid so that I can merge this without new testing.
