### PR TITLE
Fixed Pilus Physics Size

### LINKED ISSUE #1064: Make pilus physics size match the visual size

### PR DESCRIPTION
**Pull request by CoreyHendrey**
Pilus physics size now takes into account the organelles scale.

There is a commit here that uses a really crappy debug mesh that matches the pilus physics cylinder (because no matter what I did I couldn't get Debug Collision Shapes to show the damn cylinder).

Small (no scaling):
image

Just before splitting:
image

Closed #1064

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
One worry with this that I have is that this impacts performance a lot. I think that adjusting the size is a good thing, but if each cell that is growing gets their pilus physics recreated each frame, that's not super nice. Instead I think that the pilus could also be made so that it doesn't change size when it grows and just keep the initial size adjustements from this.

**Comment by hhyyrylainen** [comment]
The debug draw has been broken for cells from the start. I reopened the issue about that: https://github.com/Revolutionary-Games/Thrive/issues/1095
I think that, that and a bunch of the other physics issues are caused by the same underlying reason.

**Comment by Kasterisk** [comment]
Heh, didn't think of that. Well looks like those has to be fixed I guess

**Comment by CoreyHendrey** [comment]
Yeah I could change it like that. It was adding the shape every frame before my commit though, but I agree with your reasoning. I'll try and make the Pilus not grow. Maybe it's best done by adding a "ShouldScale" flag to the organelles.

**Comment by hhyyrylainen** [comment]
It's definitely a bug if it is readding the pilus each frame, it should only add it again if the position where it should be changed.

:+1: for organelle flag controlling if an organelle visually grows or not, should also be applied to the nucleus.

File: src/microbe_stage/PlacedOrganelle.cs [hunk 1]
```diff
@@ -453,8 +453,7 @@ private void RecalculateGrowthValue()
 
     private void ApplyScale()
     {
-        // Nucleus isn't scaled
-        if (HasComponent<NucleusComponent>())
```
Comment (CoreyHendrey) [inline src/microbe_stage/PlacedOrganelle.cs:457]: We no longer need to manually check for a nucleus

File: src/microbe_stage/OrganelleDefinition.cs [hunk 2]
```diff
@@ -108,6 +108,11 @@ microbe editor.
     /// </summary>
     public int MPCost;
 
+    /// <summary>
+    ///   Should this organelle scale?
```
Comment (hhyyrylainen) [inline src/microbe_stage/OrganelleDefinition.cs:112]: This should be expanded:
```
Controls whether this organelle scales with growth progress (progress towards division and reproduction).
```

File: src/microbe_stage/organelle_components/PilusComponent.cs [hunk 3]
```diff
@@ -8,6 +8,15 @@ public class PilusComponent : ExternallyPositionedComponent
 {
     private List<uint> addedChildShapes = new List<uint>();
 
+    private uint ownerId;
```
Comment (hhyyrylainen) [inline src/microbe_stage/organelle_components/PilusComponent.cs:11]: Why did you add this? There's already addedChildShapes.

File: src/microbe_stage/organelle_components/PilusComponent.cs [hunk 4]
```diff
@@ -33,41 +42,40 @@ protected override bool NeedsUpdateAnyway()
             membraneCoords *= 0.5f;
         }
 
-        float pilusSize = 4.6f;
-
-        // Scale the size down for bacteria
-        if (organelle.ParentMicrobe.Species.IsBacteria)
-        {
-            pilusSize *= 0.5f;
-        }
```
Comment (hhyyrylainen) [inline src/microbe_stage/organelle_components/PilusComponent.cs:42]: I don't fully get why moving this code to a new method that is in CustomAttach works. It should be anyway so that OnPositionChanged **should** only be called when truly needed. Fixing OnPositionChanged being called incorrectly will likely also fix things for the flagella being repositioned all the time.

Comment (CoreyHendrey) [reply src/microbe_stage/organelle_components/PilusComponent.cs:42]: The way I understood the code previously, OnPositionChanged happens every frame the organelle moves. This means every single frame the player moved, DestroyShape() was being called, and a new shape was being created.

This new way, when the organelle is created the CollisonShapes are also created. OnPositionChanged only changes the transform of these shapes now, as you would expect.

Comment (hhyyrylainen) [reply src/microbe_stage/organelle_components/PilusComponent.cs:42]: `OnPositionChanged` **should** only be called when the position within the cell relative coordinates for the thing changes. So basically whenever an organelle is added or removed and the membrane is regenerated, the membrane point the pilus or flagellum wants to attach can change, and **then** OnPositionChanged is called. 
It's a good change to only recreate the shape when needed, but it should also take into account that if the pilus size changes the physics shape needs editing.

Comment (CoreyHendrey) [reply src/microbe_stage/organelle_components/PilusComponent.cs:42]: >It's a good change to only recreate the shape when needed, but it should also take into account that if the pilus size changes the physics shape needs editing.

This can be done here, we just add scaling to the transform. I had it doing that before I took out scaling for the Pilus.

I will check how often OnPositionChanged is called, I was misinterpreting its function.

Comment (CoreyHendrey) [reply src/microbe_stage/organelle_components/PilusComponent.cs:42]: Yeah it's definitely called every single frame. I'll take a look...

**Comment by CoreyHendrey** [comment]
Ok - OnPositionChanged no longer gets called every frame. Hopefully this helps the flagella as well.
