### PR TITLE
Cytoplasm nucleus bug

### LINKED ISSUE #1961: Unplacing and replacing nucleus crashes the game.
Steps to reproduce:
1. Place the nucleus over the original cytoplasm
2. Undo the placement
3. Place it in the same place again
```
E 0:00:24.462   IntPtr Godot.Object.GetPtr(Godot.Object ): System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'NucleusMesh'.
  <C++ Error>   Unhandled exception
  <C++ Source>  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Object.base.cs:37 @ IntPtr Godot.Object.GetPtr(Godot.Object )()
  <Stack Trace> Object.base.cs:37 @ IntPtr Godot.Object.GetPtr(Godot.Object )()
                Node.cs:537 @ void Godot.Node.RemoveChild(Godot.Node )()
                SceneDisplayer.cs:28 @ void SceneDisplayer.LoadNewScene()()
                SceneDisplayer.cs:20 @ void SceneDisplayer.set_Scene(System.String )()
                MicrobeEditor.cs:1788 @ void MicrobeEditor.UpdateOrganellePlaceHolderScene(SceneDisplayer , System.String )()
                MicrobeEditor.cs:1764 @ void MicrobeEditor.UpdateAlreadyPlacedVisuals()()
                MicrobeEditor.cs:1679 @ void MicrobeEditor.OnOrganellesChanged()()
                MicrobeEditor.cs:1199 @ void MicrobeEditor.UpdateEditor(Single )()
                MicrobeEditor.cs:530 @ void MicrobeEditor._Process(Single )()
```

https://user-images.githubusercontent.com/59157446/102834405-c7c3d980-43a8-11eb-9180-f77811ea5454.mp4

### LINKED ISSUE #2340: Crash when deleting other organelles and then moving the nucleus
I seem to sometimes be able to get a crash when trying to move the nucleus after deleting (and moving) other organelles to be left with less than 5 MP. Callstack seems to be the same as: https://github.com/Revolutionary-Games/Thrive/issues/1961
so fixing that might also fix this

### PR DESCRIPTION
**Pull request by Kemikal1**
**Brief Description of What This PR Does**

Fixes #2340  and Fixes #1961

**Related Issues**

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
You'll probably want to override your local master branch from the main repo and rebase these changes on that, and finally force push to clear this out.

Btw would this also fix: https://github.com/Revolutionary-Games/Thrive/issues/1961 ?

**Comment by Kemikal1** [comment]
It fixes everyhting related to nucleus crash for me.
"You'll probably want to override your local master branch from the main repo and rebase these changes on that, and finally force push to clear this out."
IS this a must?Ill pull origin to my main and delete this fork if it gets accepted.

**Comment by hhyyrylainen** [comment]
I guess as there aren't conflicts that is not necessary as this will be squashed to a single commit anyway so it doesn't matter that there's a bunch of useless commits in this PR.

File: src/general/SceneDisplayer.cs [hunk 1]
```diff
@@ -23,7 +23,7 @@ public string Scene
 
     private void LoadNewScene()
     {
-        if (currentlyShown != null)
+        if (currentlyShown != null && IsInstanceValid(currentlyShown))
```
Comment (hhyyrylainen) [inline src/general/SceneDisplayer.cs:26]: I'll just make an observation regarding this as I don't have time to investigate now: so this now asks Godot "hey have we accidentally deleted this currentlyShown scene"? I think a better approach would be investigating where currentlyShown is is freed but not set to null. 

Would adding a line after 29 like `currentlyShown = nul;l`, fix this?

Comment (Kemikal1) [reply src/general/SceneDisplayer.cs:26]: Yes and Yes.

Comment (Kemikal1) [reply src/general/SceneDisplayer.cs:26]: Is cytoplasm.tscn supposed to be loaded in organel.Definition.Display Scene??Cause its not.

Comment (hhyyrylainen) [reply src/general/SceneDisplayer.cs:26]: It's not because the DisplayScene is what's shown in the microbe for that organelle. Cytoplasm only has a scene for when it is used as a corpse chunk.

Comment (Kemikal1) [reply src/general/SceneDisplayer.cs:26]: Im saying because that also seems to fix the problem.

Comment (hhyyrylainen) [reply src/general/SceneDisplayer.cs:26]: I suppose that also *masks* the problem. I want to fix the actual problem which is that `currentlyShown` is sometimes freed without setting it to null. That's the change that actually addresses the underlying problem, and one I want added to the codebase.

Comment (Kemikal1) [reply src/general/SceneDisplayer.cs:26]: Godot doesnt set it to null.it marks it as unused.Doesnt remove all references to the removed object.thats why the null check doesnt work.

Comment (hhyyrylainen) [reply src/general/SceneDisplayer.cs:26]: That's why the correct thing is in our code to set the variable to null after deleting that. That solves all the problems and is valid usage. It's completely nonsensical to me to not do things properly here and instead rely on asking the engine if we did something stupid with an object. I have experience in C++ and to me this seems as silly as deleting a pointer in C++ without setting it to null, the difference being there that you can't ask the runtime "did I delete this already?", instead you need to handle it yourself.

Comment (Kemikal1) [reply src/general/SceneDisplayer.cs:26]: "I have experience in C++ and to me this seems as silly as deleting a pointer in C++ without setting it to null"
Godot has its own type of null.And that is "unused."And aparently null here means uninstantaiated and "unused" is the actuall "null".And thats the check.I dont think were doing any kind of stupid things??
So?How do you wnat it boss?Set to null?

Comment (hhyyrylainen) [reply src/general/SceneDisplayer.cs]: Set the C# variable to null. There's a null check on this *exact* line which will prevent the problem of freeing a Godot object multiple times.

**Review by hhyyrylainen — APPROVED** [review]
Works perfectly for the nucleus redo bug.

**Comment by hhyyrylainen** [comment]
Does this still fix #2340 ?

**Comment by Kemikal1** [comment]
Yes

**Comment by hhyyrylainen** [comment]
Excellent
