### PR TITLE
Save load signal can trigger while loading a save leading to a crash

### LINKED ISSUE #3981: Save load signal can trigger while loading a save leading to a crash
Got a report that the game can crash with the following:
```
ERROR: ------------ Begin of Unhandled Exception Log ------------
ERROR: The following exception prevented the game from running:
ERROR: 
ERROR: System.ObjectDisposedException: Cannot access a disposed object.
ERROR: 
ERROR: Object name: 'SaveListItem'.
ERROR: 
ERROR:   at Godot.Object.GetPtr (Godot.Object instance) [0x0001c] in <19daba5d5ae94c7483bcc78b7907d0ef>:0 
ERROR: 
ERROR:   at Godot.Object.EmitSignal (System.String signal, System.Object[] args) [0x00000] in <19daba5d5ae94c7483bcc78b7907d0ef>:0 
ERROR: 
ERROR:   at SaveListItem.LoadSave () [0x0000b] in <2710f54513ec40ebbebf69e787e6748f>:0 
ERROR: 
ERROR:   at TransitionManager+Sequence.StartNext () [0x00094] in <2710f54513ec40ebbebf69e787e6748f>:0 
ERROR: 
ERROR:   at TransitionManager+Sequence.Process () [0x00087] in <2710f54513ec40ebbebf69e787e6748f>:0 
ERROR: 
ERROR:   at TransitionManager._Process (System.Single delta) [0x00019] in <2710f54513ec40ebbebf69e787e6748f>:0 
ERROR: 
ERROR: Please provide us with this log, thank you.
ERROR: ------------  End of Unhandled Exception Log  ------------
```

Logs leading up to that problem:
```
Jukebox now playing from: MicrobeStage
Creating a save with name: auto_save_5.thrivesave
save finished, success: True message: Saving succeeded elapsed: 00:00:02.4876610
Jukebox: starting track: res://assets/sounds/microbe-theme-4.ogg position: 73.61306
Jukebox: starting track: res://assets/sounds/soundeffects/microbe-ambience-3.ogg position: 120.4477
The player has died
Applying immediate population effect to Primum thrivium (1), constant: -20, coefficient: 0.6666667, reason: player died
Starting load of save: auto_save_4.thrivesave
Note: error lines may not match up when they happened in relation to normal output due to buffering.
Error lines are any lines received from the game's stderr output stream.
ERROR: Index p_shape_index = 14 is out of bounds (total_subshapes = 10).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Index p_shape_index = 14 is out of bounds (total_subshapes = 10).
ERROR:    at: shape_find_owner (scene/3d/collision_object.cpp:529)
ERROR: Can't load a save while a load or save is in progress
```

So it kind of seems like the save load is started but then a second load signal is triggered. This can *probably* be fixed by preventing all further save list item / save manager interaction once a load has started.

### PR DESCRIPTION
**Pull request by Kashnox**
**Brief Description of What This PR Does**

This PR makes SaveListItem use the same load method used by SaveList because SaveList already had plenty of guards against loading, saving, or deleting multiple times at once. It also stops SaveList from queuing multiple load transitions at once.

The multiple transition queuing was the real cause of the crash. SaveListItem would queue two transitions that loaded a save when they were finished. When the first load finished, it disposed of the scene the transitions were triggered from. Then, when the second load started, it tried to emit a signal from the disposed scene, which caused the exception found in the issue.

**Related Issues**

closes #3981 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by buckly90** [comment]
Seems to eliminate the crash without error, and older saves load just fine.

Great job!

File: src/saving/SaveList.cs [hunk 1]
```diff
@@ -410,12 +430,9 @@ private void LoadSave()
...
         SaveHelper.LoadSave(saveToBeLoaded);
+
         EmitSignal(nameof(OnSaveLoaded), saveToBeLoaded);
         saveToBeLoaded = null;
-    }
-
-    private void OnSaveLoadedWithoutProblems(string saveName)
-    {
-        EmitSignal(nameof(OnSaveLoaded), saveName);
+        isLoadingSave = false;
```
Comment (hhyyrylainen) [inline src/saving/SaveList.cs:436]: I was worried that this gets unset for one frame when the loading process hasn't taken hold yet, but maybe that doesn't happen as long as the performed invoke runs on the same frame as this input then the loading screen will get displayed immediately over this save list.

**Review by hhyyrylainen — APPROVED** [review]
I had some "hold on" thoughts while reading the code here, but I suppose this is in fact correct and doesn't have any problematic edge cases.
