### PR TITLE
Fixed equality comparisons for process speed data when processes change

### LINKED ISSUE #3898: Process panel stops updating properly with specific changes to the player
in the day/night cycle PR it was there's some issue regarding the process panel stopping updating, and it was checked to also happen in the master branch (before that PR was merged).

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**

this should fix the process panel stopping updating

**Related Issues**

fixes #3898
closes #3955

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/gui_common/ChemicalEquation.cs [hunk 1]
```diff
@@ -52,7 +52,7 @@ public class ChemicalEquation : VBoxContainer
             if (equationFromProcess == null && value == null)
                 return;
 
-            if (equationFromProcess?.Equals(value) == true)
+            if (value != null && equationFromProcess?.Equals(value) == true)
```
Comment (84634E1A607A) [inline src/gui_common/ChemicalEquation.cs:55]: Why null check here?

Comment (hhyyrylainen) [reply src/gui_common/ChemicalEquation.cs:55]: The Equals method here takes in a non-nullable parameter so it causes a warning because `value` is nullable here. I think this is semantically the right way to express what the old code wanted to do.

File: src/microbe_stage/ProcessStatistics.cs [hunk 2]
```diff
@@ -26,15 +36,15 @@ public void RemoveUnused()
...
+    public SingleProcessStatistics GetAndMarkUsed(BioProcess forProcess)
     {
         if (Processes.TryGetValue(forProcess, out var entry))
         {
             entry.Used = true;
             return entry;
         }
 
-        entry = new SingleProcessStatistics(forProcess.Process);
+        entry = new SingleProcessStatistics(forProcess);
```
Comment (Oliveriver) [inline src/microbe_stage/ProcessStatistics.cs:47]: Ah, good spot simplifying this.

**Review by Oliveriver — APPROVED** [review]
Sensible fix. I'll go ahead and close my PR for this.

File: src/microbe_stage/ProcessStatistics.cs (hunk 2 above)
Comment (hhyyrylainen) [reply src/microbe_stage/ProcessStatistics.cs:47]: Well this was not really about simplifying. I initially designed this to take in a TweakedProcess in case there was a situation where multiple TweakedProcesses might exist for the same base process and their statistics should be able to exist separately. I've now decided that that is a very confusing and bad thing to allow, so I adjusted the object used as key to store the speed information.
