### PR TITLE
Fix weird colony links

### LINKED ISSUE #6733: Fully spawned in multicellular colonies have non-consistent intercellular matrix
When the player grows the intercellular matrix gets done in a very sensible way:

Image

But when a colony spawns in fully grown it gets weird long links.

Top left is an AI colony (and a second one which makes it a bit hard to see) in which the front cell has a really long link to the behind right whereas in the player the front cell has a nice short link to the cell immediately next to it.

I'm not sure in exactly which part the problem is: either the visuals creation or even the attach to cell tree structure being wrong (which would be a more serious bug).

### PR DESCRIPTION
**Pull request by dligr**
**Brief Description of What This PR Does**

It seems like this bug was caused by outer cells being spawned first (with their order being the reverse of that of `GrowColonyMembers`'s) and having very limited options of what cell to attach to (that being the leader cell very often).

This PR reverses this order (as well as switching the script to use a `for` loop), making inner cells spawn first.

**Related Issues**

Fixes #6733

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by IdfbAn** [comment]
I only did some very quick testing, but it does seem to work properly and the links are sane.

File: src/multicellular_stage/systems/DelayedColonyOperationSystem.cs
Comment (hhyyrylainen) [inline src/multicellular_stage/systems/DelayedColonyOperationSystem.cs:203]: As the loop is now reversed, shouldn't this be `bodyPlanIndex = -colony.ColonyMembers.Length;` (so negative?)

File: src/multicellular_stage/systems/DelayedColonyOperationSystem.cs [hunk 1]
```diff
@@ -183,14 +182,14 @@ private void GrowColonyMembers(in Entity entity, CommandBuffer recorder, int mem
         ref var species = ref entity.Get<MulticellularSpeciesMember>();
 
         bool added = false;
-        var cellsToGrow = species.Species.ModifiableGameplayCells.Skip(bodyPlanIndex).Take(members);
 
         ref var parentPosition = ref entity.Get<WorldPosition>();
 
-        foreach (var cellTemplate in cellsToGrow)
+        for (int i = Math.Min(bodyPlanIndex + members, species.Species.ModifiableGameplayCells.Count - 1); i > 0; --i)
```
Comment (hhyyrylainen) [inline src/multicellular_stage/systems/DelayedColonyOperationSystem.cs]: That would then mean that using a clamp here might be required?

File: src/multicellular_stage/systems/DelayedColonyOperationSystem.cs [hunk 2]
```diff
@@ -183,14 +182,14 @@ private void GrowColonyMembers(in Entity entity, CommandBuffer recorder, int mem
         ref var species = ref entity.Get<MulticellularSpeciesMember>();
 
         bool added = false;
-        var cellsToGrow = species.Species.ModifiableGameplayCells.Skip(bodyPlanIndex).Take(members);
 
         ref var parentPosition = ref entity.Get<WorldPosition>();
 
-        foreach (var cellTemplate in cellsToGrow)
```
Comment (hhyyrylainen) [inline src/multicellular_stage/systems/DelayedColonyOperationSystem.cs:190]: Also it would be really nice to write a comment on this line why this loop is now in reverse order.

Actually I'm unsure why the delay attached microbes being created in *reverse order* fixes things. I feel like relying on an internal implementation detail of the ECS system is a bit fragile...

It would be a more bulletproof approach to store an index in the delay attached component and then make the delay attach system buffer all items and sort them based on the index before it applies any of the data. That should make us safe from ECS processing order changes.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
I find it a bit strange how this works given the ECS looping order doesn't seem to have a natural reason to run in reverse order. So while this seems to work based on testing feedback from other people, I think this needs some stricter validations that this will keep working in the future.

File: src/multicellular_stage/systems/DelayedColonyOperationSystem.cs [hunk 3]
```diff
@@ -26,6 +26,10 @@
 [RuntimeCost(0.25f)]
 public partial class DelayedColonyOperationSystem : BaseSystem<World, float>
 {
+    public static readonly object AttachLock = new();
```
Comment (hhyyrylainen) [inline src/multicellular_stage/systems/DelayedColonyOperationSystem.cs]: Static variables in systems should be avoided.

File: src/multicellular_stage/systems/DelayedColonyOperationSystem.cs [hunk 4]
```diff
@@ -112,8 +118,20 @@ private void Update(ref DelayedMicrobeColony delayed, in Entity entity)
 
                     lock (AttachedToEntityHelpers.EntityAttachRelationshipModifyLock)
                     {
-                        CompleteDelayedColonyAttach(ref colony, delayed.FinishAttachingToColony, entity,
-                            recorder, delayed.AttachIndex);
+                        lock (AttachLock)
```
Comment (hhyyrylainen) [inline src/multicellular_stage/systems/DelayedColonyOperationSystem.cs]: I don't think this is the optimal solution. I think that rather than doing this, it would be better to have a `List<(Entity Entity, DelayedMicrobeColony DelayedOperation, int Index)>` that is filled here, and then in after update method, the list would be sorted and processed in body plan index order.

File: src/multicellular_stage/systems/DelayedColonyOperationSystem.cs
Comment (dligr) [reply src/multicellular_stage/systems/DelayedColonyOperationSystem.cs:203]: Now that I've made this method use a non-reversed order, this is probably unnecessary anymore

File: src/multicellular_stage/systems/DelayedColonyOperationSystem.cs (hunk 4 above)
Comment (dligr) [reply src/multicellular_stage/systems/DelayedColonyOperationSystem.cs]: I went with a similar solution, except that `Index` is just `DelayedMicrobeColony`'s attach index

File: src/multicellular_stage/systems/DelayedColonyOperationSystem.cs [hunk 5]
```diff
@@ -92,6 +96,36 @@ public static void CreateDelayAttachedMicrobe(ref WorldPosition colonyPosition,
...
+    public override void AfterUpdate(in float t)
+    {
+        if (attachmentOrder.Count == 0)
+            return;
+
+        var recorder = worldSimulation.StartRecordingEntityCommands();
+
+        lock (attachLock)
+        {
+            foreach (var pair in attachmentOrder.OrderBy(a => a.Delayed.AttachIndex))
```
Comment (hhyyrylainen) [inline src/multicellular_stage/systems/DelayedColonyOperationSystem.cs]: This is pretty good now, but I think this uses LINQ in a way that allocates memory.

I believe that it should be possible to use `List.Sort` (it modifies in-place) with a custom comparer to avoid this memory allocation.

File: src/multicellular_stage/systems/DelayedColonyOperationSystem.cs [hunk 6]
```diff
@@ -183,14 +200,15 @@ private void GrowColonyMembers(in Entity entity, CommandBuffer recorder, int mem
         ref var species = ref entity.Get<MulticellularSpeciesMember>();
 
         bool added = false;
-        var cellsToGrow = species.Species.ModifiableGameplayCells.Skip(bodyPlanIndex).Take(members);
```
Comment (hhyyrylainen) [inline src/multicellular_stage/systems/DelayedColonyOperationSystem.cs:186]: Good removal of LINQ usage here, though!

File: src/multicellular_stage/systems/DelayedColonyOperationSystem.cs
Comment (hhyyrylainen) [inline src/multicellular_stage/systems/DelayedColonyOperationSystem.cs:160]: I just have a thought that what if it was possible for the component to be removed and then a save happens and that would then leave a microbe unattached. However I then checked and as this is always processed in the `AfterUpdate` method that should not be a possible situation so yeah my conclusion is that it is safe to keep things like this.
