### PR TITLE
Fix context-specific tracks playing multiple times in a row by remembering `LastPlayedTrack` instead of index

### LINKED ISSUE #5615: Make context-specific selected music respect option to not play the same track twice in a row
as with the initial implementation there is a chance to play a context specific music track in a row again and again. It should be fixed so that if a context specific music was just played then when the track list is random or sequential mode that same track couldn't be selected at once.

### PR DESCRIPTION
**Pull request by ChevyLevi**
**Brief Description of What This PR Does**

This PR mainly fixes a bug that may cause the same track play twice in a row. It also fixed some code style and memery allocation issues.
The origin logic uses the index of the current available context tracklist to select distinct track. However, the available context may change, and the same index might point to a different track after the change.
This PR uses a `Track` type variable to store the last played track ,therefore to make sure the context change won't have a effect on the playing order.
Please note that after merging this PR, if the available context only contains 1 track, that track will still loop.

**Related Issues**

Fixes #5615

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
One note with the active data in the Jukebox, my dream is that someday saving the Jukebox state will be implemented (https://github.com/Revolutionary-Games/Thrive/issues/1346). Meaning that all data must be easily serializable and loadable, which means that it might not be possible to directly keep a reference to the track object. So it might need an alternative like remembering the string path of the last played track for detecting duplicates. Though it is possible for `IRegistryType` inheriting classes to be saved and loaded, that will still cause some trickyness around the saving / loading.

**Comment by ChevyLevi** [comment]
changed from using referance to `ResourcePath`. Still, I plan to open another PR to implement some custom commands like play next tracks first, then fully test and try to merge this one.

File: src/general/Jukebox.cs [hunk 1]
```diff
@@ -625,31 +667,24 @@ private void OnCategoryEnded()
 
         // We don't have to do anything for the Reset return type here
 
+        if (category?.Return != MusicCategory.ReturnType.Continue)
```
Comment (hhyyrylainen) [inline src/general/Jukebox.cs]: I think the code change mostly makes sense, but I don't think this should be changed...

Because this is meant to be structured to handle all different cases. If your tools want to make this change, I think instead it would make more sense to refactor this into a switch as this is meant to be able to have handling for any return type.

Comment (ChevyLevi) [reply src/general/Jukebox.cs]: the marked change is reverted.

**Comment by hhyyrylainen** [comment]
The saving update for the Jukebox is now merged to master, so this might also need new changes.

**Comment by hhyyrylainen** [comment]
Is this ready for review again? It's not immediately clear what the status on this is.

**Comment by ChevyLevi** [comment]
> Is this ready for review again? It's not immediately clear what the status on this is.

Sorry I forgot to update status about that.
I'm opening a new PR to support the debug command we discussed before, after that I'll use those commands to test this PR. If the test passed, I'll let you know that it's ready.

**Comment by ChevyLevi** [comment]
After fixing a missing place, now gameplay test shows that the bug is fixed now.

File: src/general/Jukebox.cs [hunk 2]
```diff
@@ -779,15 +779,13 @@ private void PlayNextTrackFromList(TrackList list, Func<int, AudioPlayer> getPla
 
         if (random.NextFloat() <= Constants.CONTEXTUAL_ONLY_MUSIC_CHANCE)
         {
-            var contextMusicOnly = list.GetTracksForContexts(activeContexts).Where(c => c.ExclusiveToContexts != null)
+            var contextMusicOnly = list.GetTracksForContexts(activeContexts)
+                .Where(c => c.ExclusiveToContexts != null && c.ResourcePath != list.LastPlayedTrackPath)
```
Comment (hhyyrylainen) [inline src/general/Jukebox.cs:784]: This is slightly bad style as due to the `list` variable usage, this needs to allocate a lambda each time. However I'll allow this as we call ToArray anyway here and thus allocate a bunch of memory already.

File: src/general/MusicCategory.cs [hunk 3]
```diff
@@ -117,8 +117,11 @@ public enum Order
     /// </summary>
     public bool Repeat { get; set; } = true;
 
+    /// <summary>
+    ///   Runtime-only path of the last track played from this list.
+    /// </summary>
     [JsonIgnore]
-    public int LastPlayedIndex { get; set; } = -1;
+    public string? LastPlayedTrackPath { get; set; }
```
Comment (hhyyrylainen) [inline src/general/MusicCategory.cs:124]: Should this be saved to ensure consistency in audio playing after loading a save? I can see both points: the player might have made the save yesterday and continued now in which case playing the last track again doesn't actually matter. Then again making a save and imemdiately reloading and then hearing the same track twice would be kind of non-optimal.

File: src/general/Jukebox.cs (hunk 2 above)
Comment (ChevyLevi) [reply src/general/Jukebox.cs:784]: Yeah I was thinking about that before... It's absolutely better to eliminate those memory alloc here, but broader changes are needed -- for example, the `GetTracksForContexts()` function actually uses LINQ inside and returns an IEnumerable here, so that might need to be changed to.
So if you also think it's better to fix those problems, I'm happy to do that.

Comment (hhyyrylainen) [reply src/general/Jukebox.cs:784]: Seeing as there's already a ToArray call here, it's probably better to just leave it for now. I'll just add a TODO comment on this.

**Review by hhyyrylainen — APPROVED** [review]
I tested this and it seems to correctly skip playing the same track again in a context.

For now, I won't ask extending the saved information in the Jukebox to include the last played track path as I'm not fully sure that is the better option.

File: src/general/MusicCategory.cs (hunk 3 above)
Comment (ChevyLevi) [reply src/general/MusicCategory.cs:124]: I think to avoid the latter case, maybe it's better to record that in the save - anyway record won't harm in the former case.
