### PR TITLE
Fixed some texts not updating on language change v1

### LINKED ISSUE #1815: Make editor organelle and ATP bar tooltips react to language change
If the language is changed while in the editor, the tooltips for organelles are not rebuilt.
To fix this the editor probably needs to register a listener (and also unregister on tree exit) for the language Setting to change, when that happens it needs to rebuild the tooltips that need it.

### LINKED ISSUE #1883: Make patch names react to language change
Right now they are baked in the objects themselves, so even if you save and load the names won't be translated back.

For example:

### LINKED ISSUE #1884: Add callbacks for all dynamically generated text to refresh on language change
At least the editor tooltips need this for the process list.

not absolutely necessary but would be nice to have the auto-evo and external effects also be able to change language.

### PR DESCRIPTION
**Pull request by Kasterisk**
Adresses #1884 but doesn't fully close it because this doesn't fix the auto-evo summary not updating on language change. Might want to rename the issue after this PR is merged.

Also moved MainMenu files to `src/general`.

Closes #1883 and closes #1815

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Does this actually change the translations or is this just updating the translations files?
A new language has been added, and there are quite a few pending changes: https://github.com/Revolutionary-Games/Thrive/pull/2141 so it would be easier to manage if this didn't have any translation file changes to not cause conflicts I need to manually fix. A separate PR can be made for hooking up the new nl translation in the game and then update the localization files after merging the pending translations.

**Comment by Kasterisk** [comment]
This just updates the translation files, which the formatting checks want for some reason (it outputted some build errors last time I ran it).

**Comment by hhyyrylainen** [comment]
Oh yeah, of course. As you moved files around the order in which the translateable strings are detected has changed.
Once this is close to ready for merge, I'll merge that weblate PR, then you can pull, override your local translation changes. And re-run the script. Those steps will require the minimum amount of manual merging.

File: simulation_parameters/SimulationParameters.cs [hunk 1]
```diff
@@ -85,6 +85,14 @@ private SimulationParameters()
 
     public NameGenerator NameGenerator { get; }
 
+    public override void _Notification(int what)
+    {
+        if (what == NotificationTranslationChanged)
+        {
+            ApplyTranslations();
```
Comment (hhyyrylainen) [inline simulation_parameters/SimulationParameters.cs:92]: Doesn't options menu already directly call this when changing the translations?
I think one of these 2 approaches should be removed.

File: src/microbe_stage/MicrobeStage.cs [hunk 2]
```diff
@@ -190,6 +190,19 @@ public override void _Ready()
         SetupStage();
     }
 
+    public override void _Notification(int what)
+    {
+        if (what == NotificationTranslationChanged)
+        {
+            foreach (var patch in CurrentGame.GameWorld.Map.Patches)
```
Comment (hhyyrylainen) [inline src/microbe_stage/MicrobeStage.cs:197]: I think it would make sense to add a method in GameWorld called ApplyTranslations that would apply patch name translations, and also it could in the future apply all other translation changes that are needed.

File: src/microbe_stage/Patch.cs [hunk 3]
```diff
@@ -32,15 +32,28 @@ public class Patch
     [JsonProperty]
     private Deque<PatchSnapshot> history = new Deque<PatchSnapshot>();
 
+#pragma warning disable 169 // Used through reflection
+    [JsonProperty]
+    private string untranslatedName;
+#pragma warning restore 169
+
+    public Patch()
```
Comment (hhyyrylainen) [inline src/microbe_stage/Patch.cs:40]: Is this needed? Would the implicitly defined constructor work, or does that not work?

File: src/microbe_stage/Patch.cs [hunk 4]
```diff
@@ -32,15 +32,28 @@ public class Patch
...
         BiomeTemplate = biomeTemplate;
         currentSnapshot.Biome = (BiomeConditions)biomeTemplate.Conditions.Clone();
+
+        TranslationHelper.CopyTranslateTemplatesToTranslateSource(this);
+        TranslationHelper.ApplyTranslations(this);
     }
 
-    [JsonProperty]
+    [JsonIgnore]
+    [TranslateFrom("untranslatedName")]
```
Comment (hhyyrylainen) [inline src/microbe_stage/Patch.cs:56]: Already mentioned, but if there isn't an easy way to fix the saves, you need to add a save breakage point for 0.5.3.2 in the `KnownSaveIncompatibilityPoints` list.

Comment (hhyyrylainen) [reply src/microbe_stage/Patch.cs:56]: I didn't find an issue about that, so I opened a new one: https://github.com/Revolutionary-Games/Thrive/issues/2152

File: src/microbe_stage/editor/MicrobeEditor.cs [hunk 5]
```diff
@@ -530,6 +530,26 @@ public override void _Process(float delta)
...
+        // Rebuilds and recalculates all value dependent UI elements on language change
+        if (what == NotificationTranslationChanged)
+        {
+            CalculateOrganelleEffectivenessInPatch(CurrentPatch);
+            UpdatePatchDependentBalanceData();
+            gui.UpdateTimeIndicator(CurrentGame.GameWorld.TotalPassedTime);
+            gui.UpdateGlucoseReduction(Constants.GLUCOSE_REDUCTION_RATE);
+
+            // If ReturnToStage is null (starting directly from the MicrobeEditor scene), the patch
+            // names won't be updated on language change
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditor.cs:544]: This comment looks wrong to me...

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

File: simulation_parameters/SimulationParameters.cs (hunk 1 above)
Comment (Kasterisk) [reply simulation_parameters/SimulationParameters.cs:92]: I tried with using only the call in Settings.cs and the it seems the compounds and processes names (specifically on the charts and organelle tooltips) doesn't properly change like it stuck one language behind, maybe godot notifications are executed earlier than script functions? Either way, I guess I'll keep the notifications approach.

File: src/microbe_stage/Patch.cs (hunk 3 above)
Comment (Kasterisk) [reply src/microbe_stage/Patch.cs:40]: It doesn't work with the implicit constructor and throws an exception when trying to load a save: `Newtonsoft.Json.JsonException: no suitable constructor found for current type: Patch`

File: simulation_parameters/SimulationParameters.cs (hunk 1 above)
Comment (hhyyrylainen) [reply simulation_parameters/SimulationParameters.cs:92]: But if just this notifications doesn't work, then shouldn't notifications be removed from SImulationParameters, as it is already specifically handled by the game options to notify the parameters?

File: src/microbe_stage/Patch.cs (hunk 3 above)
Comment (hhyyrylainen) [reply src/microbe_stage/Patch.cs:40]: Okay. I think I remember experiencing the same thing. Btw I wrote that constructor finding code, so it might be possible to special case it for calling the implicit constructor.

**Comment by hhyyrylainen** [comment]
Btw now that I've thought about this a bit more I have some further conclusions about the patch names.
I don't think we should change how the patch name is stored. This will make old saves work, so we aren't breaking people's saves each point release. Instead I think for now we should do the following:
- Pass in the untranslated name to the Patch constructor from the patch name generation
- The 2 places (I think there's only like two: patch map display in the editor and the patch name in the microbe stage), should then use TranslationServer.Translate(Patch.Name). This will correctly map the untranslated strings to translations *and* pass already translated strings as-is, because they won't match anything

I suggest this because in the future when we have a dynamic patch map generator and also a place name generator, it would be extremely difficult to apply translations (as you would need to maintain a mapping between each type of name and the principal name components of each name for each language) . Instead the name generator needs to be rewritten for each language separately, and then the localized names will eventually be stored in the Patch name, at this point the translation server calls to localize, the patch names can be removed.

File: simulation_parameters/SimulationParameters.cs (hunk 1 above)
Comment (Kasterisk) [reply simulation_parameters/SimulationParameters.cs:92]: I mean to say the notification in SimulationParameters works by itself and the apply translations call in the settings doesn't work properly on its own.

Comment (hhyyrylainen) [reply simulation_parameters/SimulationParameters.cs:92]: Ah okay, so you meant to remove the call from options to SimulationParameters? That's fine as well.

Comment (Kasterisk) [reply simulation_parameters/SimulationParameters.cs:92]: Yeah, that's what I meant.

**Comment by Kasterisk** [comment]
> The 2 places (I think there's only like two: patch map display in the editor and the patch name in the microbe stage), should then use TranslationServer.Translate(Patch.Name). This will correctly map the untranslated strings to translations and pass already translated strings as-is, because they won't match anything

Wouldn't that make the localizatin update script (at least to my understanding) couldn't extract the name stored in the patches  since it's only set at runtime? Also there might be a bit more than two places that need patch names I think.

**Comment by hhyyrylainen** [comment]
> Wouldn't that make the localizatin update script (at least to my understanding) couldn't extract the name stored in the patches since it's only set at runtime? Also there might be a bit more than two places that need patch names I think.

I assumed you would keep the specific TranslationServer calls you put in the patch generator.

I think it's better anyway this way, because I think the places that need the name in localized way won't run each frame, so it isn't that bad that whenever the text is prepared for display to the user it can be passed through the translation server.

**Comment by hhyyrylainen** [comment]
Is this now ready for me to take another look?

**Comment by Kasterisk** [comment]
Yes, I feel this is now more or less in a good state, should be ready for another review.

**Comment by hhyyrylainen** [comment]
Probably around here where the values go along untranslated: https://github.com/Revolutionary-Games/Thrive/pull/2151/files#diff-4a8c8959a9293f5a6c52a15a32782ef19914673e0e9390430be2ee4260e31413R279
I think the whole create report summary method should be carefully (re-)inspected to determine what variables may contain the patch names in them.

**Comment by Kasterisk** [comment]
Okay that's fixed, I'm pretty sure those are the last strings with untranslated patch names in them.

**Review by hhyyrylainen — APPROVED** [review]
