### PR TITLE
Fix compound currents switching and ugly edges

### LINKED ISSUE #1924: Weird region lines in compound cloud absorption
Here's a video showing what's wrong: https://mega.nz/file/9BQSlLgK#gM5e3I3g31r7Izsw3LFPSAuCaimqngeQZUEDuTJCAlc

Basically it looks like there is some kind of invisible line blocking cells absorbing compounds from the other side.

### LINKED ISSUE #6670: Current effects on compound clouds needs to be scaled back (or a really old bug fixed)
The new much stronger currents in some patches cause way more straight edges to appear in the clouds. So we have two choices:
- Scale those back down
- Or finally fix this really old issue: https://github.com/Revolutionary-Games/Thrive/issues/1924

I'm marking this as easy as the easy solution is just to scale down the current effects on the clouds back to the previous levels

### PR DESCRIPTION
**Pull request by Patryk26g**
Previosly coordinates of the cloud plane were wrongly cast to the world coordinates which resulted in ugly edges created at the plane's edges and made it so that the currents switched abruptly when player crossed the boundaries

Fixes #6670 and fixes #1924  

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/microbe_stage/CompoundCloudPlane.cs [hunk 1]
```diff
@@ -999,128 +889,88 @@ private Vector4 CalculateCloudToAdd(Compound compound, float density)
...
+                        Density[(x + 1) % PlaneSize, y]) * (a * 0.25f);
             }
         }
     }
 
-    private void PartialDiffuseEdges(int x0, int y0, int width, int height, float delta)
+    private Vector3 GetWorldPositionForAdvection(int x0, int y0)
     {
-        float a = delta * Constants.CLOUD_DIFFUSION_RATE;
+        int worldShift = 200;
```
Comment (hhyyrylainen) [inline src/microbe_stage/CompoundCloudPlane.cs]: Where does this magic value come from? Could you add a comment describing here *why* this needs to be 200? This also seems to not change so maybe this should be defined as a `const` at the top of the file?

File: src/microbe_stage/CompoundCloudPlane.cs [hunk 2]
```diff
@@ -45,16 +45,17 @@ public partial class CompoundCloudPlane : MeshInstance3D, ISaveLoadedTracked, IA
 
     private Vector4 decayRates;
 
-    private Vector2I position = new(0, 0);
+    // Which square plane player is in
```
Comment (hhyyrylainen) [inline src/microbe_stage/CompoundCloudPlane.cs]: This should be an XML comment as it is commenting a single variable.

File: src/microbe_stage/CompoundCloudPlane.cs (hunk 1 above)
Comment (Patryk26g) [reply src/microbe_stage/CompoundCloudPlane.cs]: Sorry, forgot I hardcoded it, it's fixed now
