### PR TITLE
Fix physics debug draw disappearing in large saves

### LINKED ISSUE #6874: Physics debug draw doesn't work in some saves with a lot of stuff in them
Looks like while physics debug draw now works on all platforms, saves with a lot of stuff in them can just have the drawing disappear. And confusingly loading another save that worked before will make the drawing work immediately, and going back to the bad save consistently each time stops the drawing from working.

So there is some weird things going on.

A few screenshots.

Loading bad save:
Image

Loading good save:
Image

And loading the bad save immediately afterwards again just removes the debug draw that was working.

The bug could be related to the debug draw limit system culling the wrong vertices leading nothing visible in the camera when there are a lot of objects. Or at least that's my first guess where the bug might be.

### PR DESCRIPTION
**Pull request by RyuDanuer**
**Brief Description of What This PR Does**

This PR fixes physics debug draw disappearing when saves contain a lot of physics debug geometry.

The debug camera location is now refreshed from the active viewport camera immediately before physics debug drawing can happen. That keeps the native Jolt LOD / distance culling from using a stale camera location after loading a different save.

The native debug draw forwarder now also drops direct debug lines and triangles whose points are all outside the existing debug draw distance. This reduces the amount of geometry sent to Godot before the immediate mesh memory guard is reached, and applies the same distance rule to both lines and triangles instead of sorting them in separate buffers.

**Related Issues**

Closes #6874

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

**Testing**

- `dotnet build Thrive.csproj --no-restore`
- `dotnet run --project Scripts -- check files --include src/engine/DebugDrawer.cs src/engine/physics/PhysicalWorld.cs src/extension/nodes/DebugDrawer.cpp src/extension/nodes/DebugDrawer.hpp src/native/physics/DebugDrawForwarder.cpp src/native/physics/DebugDrawForwarder.hpp`

Not run locally: native C++ build and in-game verification with the affected save. This Windows machine doesn't currently have the native C++ build tools (`cmake`, `clang-format`, or a compiler) available in PATH.

### CODE REVIEW

File: src/extension/nodes/DebugDrawer.cpp [hunk 1]
```diff
@@ -30,13 +34,45 @@ constexpr long SingleLineDrawMemoryUse = MemoryUseOfIntermediateVertex * 2 + siz
 /// 3 vertices
 constexpr long SingleTriangleDrawMemoryUse = MemoryUseOfIntermediateVertex * 3 + sizeof(uint32_t);
 
+using LineDrawEntry = std::tuple<JPH::RVec3Arg, JPH::RVec3Arg, JPH::Float4>;
```
Comment (hhyyrylainen) [inline src/extension/nodes/DebugDrawer.cpp]: Looking at the distance calculation method, I think it would be more efficient to first convert to the JVec3 etc. types rather than constantly reconverting when trying to calculate the distance.

File: src/extension/nodes/DebugDrawer.cpp [hunk 2]
```diff
@@ -30,13 +34,45 @@ constexpr long SingleLineDrawMemoryUse = MemoryUseOfIntermediateVertex * 2 + siz
...
+using TriangleDrawEntry = std::tuple<JPH::RVec3Arg, JPH::RVec3Arg, JPH::RVec3Arg, JPH::Float4>;
+
 const godot::Vector3 DebugDrawer::pointOffsetLeft = {-PointLineWidth, 0, 0};
 const godot::Vector3 DebugDrawer::pointOffsetUp = {0, PointLineWidth, 0};
 const godot::Vector3 DebugDrawer::pointOffsetRight = {PointLineWidth, 0, 0};
 const godot::Vector3 DebugDrawer::pointOffsetDown = {0, -PointLineWidth, 0};
 const godot::Vector3 DebugDrawer::pointOffsetForward = {0, 0, -PointLineWidth};
 const godot::Vector3 DebugDrawer::pointOffsetBack = {0, 0, PointLineWidth};
 
+namespace
```
Comment (hhyyrylainen) [inline src/extension/nodes/DebugDrawer.cpp]: Why is this not in the game's namespace?

File: src/extension/nodes/DebugDrawer.cpp [hunk 3]
```diff
@@ -260,21 +293,70 @@ void DebugDrawer::DisablePhysicsDebug() noexcept
...
+    for (const auto& entry : lineDrawOrder)
     {
-        DrawLine(JoltToGodot(std::get<0>(entry)), JoltToGodot(std::get<1>(entry)), JoltToGodot(std::get<2>(entry)));
+        const auto& line = lineBuffer[entry.second];
+
+        DrawLine(JoltToGodot(std::get<0>(line)), JoltToGodot(std::get<1>(line)), JoltToGodot(std::get<2>(line)));
     }
 }
 
 void DebugDrawer::OnReceiveTriangles(
```
Comment (hhyyrylainen) [inline src/extension/nodes/DebugDrawer.cpp:269]: This still has a problem where the lines and triangles don't take each other into account. So if the line buffer takes up all rendering memory, then no triangles even if they are really close to the camera would render.

I think that perhaps rather than having a hardcoded memory limit, we could instead just have a max distance from the camera to display debug info and then cull any triangles or lines that don't have a close enough point. I imagine this would be faster than double buffering all lines and triangles and needing to sort them globally based on distance.

File: src/extension/nodes/DebugDrawer.cpp [hunk 4]
```diff
@@ -384,6 +466,17 @@ void DebugDrawer::StartDrawingIfNotYetThisFrame()
     drawnThisFrame = true;
 }
 
+void DebugDrawer::UpdateDebugCameraLocation()
+{
+    // The physics debug culling depends on this position even before a successful draw happens.
```
Comment (hhyyrylainen) [inline src/extension/nodes/DebugDrawer.cpp:391]: This is an interesting comment and if accurate, it could mean that maybe the problem in the first place was the camera location not being updated early enough, which prevented the rendering?

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Besides the few minor code comments, I tested this in the game and this does not seem to work. Did you test this, what were your findings? I can provide you with the save that shows the bug if you need that for testing.

**Comment by RyuDanuer** [comment]
thanks for testing it... i reworked it based on your comments.
the new revision removes the separate line/triangle sorting buffers, refreshes the debug camera location right before physics debug drawing can happen, and culls direct debug lines/triangles in the native forwarder before they are sent to Godot.

could you share the bad save so i can test it better?

File: src/extension/nodes/DebugDrawer.cpp (hunk 4 above)
Comment (RyuDanuer) [reply src/extension/nodes/DebugDrawer.cpp:391]: yes I think that’s probably the right read tbh. I checked the flow locally and Jolt gets the debug camera in `PhysicalWorld::DrawPhysics()` before drawing, but the old path only refreshed that position from the Godot camera after a successful debug draw frame. so if the stale camera made Jolt cull everything, it could get stuck in a loop: no visible draw -> camera position doesn’t refresh -> culling keeps using the old position.

so I moved the refresh to right before the physics draw/wait calls, aka before native debug draw can use the camera position.

**Comment by hhyyrylainen** [comment]
Sure, here is one save that consistently shows me the problem:

[auto_save_2.zip](https://github.com/user-attachments/files/26815392/auto_save_2.zip)


Just start up the game, enable debug draw, and then load the save and see how no debug draw occurs.

(I needed to put it into an extra zip layer to upload to Github)

**Comment by xfractalino** [comment]
This fork may not be up-to-date with the main one, as I tried to test it on my machine and still get the crash related to the previous issue:

`00 (Inline Function) --------`--------     libthrive_extension_without_avx!JPH::DVec3::GetX [/thrive/third_party/JoltPhysics/Build/../Jolt/Math/DVec3.h @ 142] `

So you might need to update this branch with the master from RevolutionaryGames first, and then I'll be happy to test it with a save where I had the current issue.

File: src/extension/nodes/DebugDrawer.cpp (hunk 4 above)
Comment (hhyyrylainen) [reply src/extension/nodes/DebugDrawer.cpp:391]: That seems like a good change, then.

**Comment by hhyyrylainen** [comment]
Yeah, this is not updated related to master so doesn't have that fix and there's a merge conflict even on DebugDrawer.cpp.

**Comment by RyuDanuer** [comment]
I tested this with the `auto_save_2.thrivesave` save on my pc.

I did find one extra edge case while doing that: during shutdown/headless cleanup, the physics debug camera update could run after the viewport was gone and throw a nullref. Pushed `cd7e25fd5` to guard that.

File: src/extension/nodes/DebugDrawer.cpp (hunk 3 above)
Comment (RyuDanuer) [reply src/extension/nodes/DebugDrawer.cpp:269]: Yeah I checked these again. The namespace + conversion comments were already from an older diff, but the line/triangle starvation point was still worth improving tbh.

I pushed another commit that keeps separate final mesh budgets for lines and triangles, so even if lines are super spammy they can’t use the whole debug draw budget and make all nearby triangles disappear. Also noticed the triangle overflow accounting was using the line memory cost, so I fixed that too.

Built it on my pc with .NET 10 and ran the targeted format check as well.

**Comment by xfractalino** [comment]
Unfortunately it still doesn't work for me. Debug drawing doesn't work on some saves with a lot of objects.

File: src/native/physics/DebugDrawForwarder.cpp [hunk 5]
```diff
@@ -315,6 +369,12 @@ JPH::DebugRenderer::Batch DebugDrawForwarder::CreateTriangleBatch(
 void DebugDrawForwarder::DrawTriangleInternal(
     const DVertex& vertex1, const DVertex& vertex2, const DVertex& vertex3, JColour colourTint, bool wireFrame)
 {
+    if (!IsPointWithinDrawDistance(vertex1.mPosition) && !IsPointWithinDrawDistance(vertex2.mPosition) &&
```
Comment (hhyyrylainen) [inline src/native/physics/DebugDrawForwarder.cpp]: For me the latest version doesn't seem to compile? So I couldn't test if this now works.

```
/home/hhyyrylainen/Projects/Thrive/src/native/physics/DebugDrawForwarder.cpp:372:36: error: no viable conversion from 'const JVec3' to 'DVec3'
  372 |     if (!IsPointWithinDrawDistance(vertex1.mPosition) && !IsPointWithinDrawDistance(vertex2.mPosition) &&
      |                                    ^~~~~~~~~~~~~~~~~
/home/hhyyrylainen/Projects/Thrive/third_party/JoltPhysics/Build/../Jolt/Math/DVec3.h:38:9: note: candidate constructor not viable: no known conversion from 'const JVec3' to 'const DVec3 &' for 1st argument                                                                                                        
   38 |                                                                 DVec3(const DVec3 &inRHS) = default;
      |                                                                 ^     ~~~~~~~~~~~~~~~~~~
/home/hhyyrylainen/Projects/Thrive/third_party/JoltPhysics/Build/../Jolt/Math/DVec3.h:42:17: note: candidate constructor not viable: no known conversion from 'const JVec3' to 'TypeArg' (aka '__m256d') for 1st argument                                                                                             
   42 |         JPH_INLINE                                      DVec3(TypeArg inRHS) : mValue(inRHS)                    { CheckW(); }
      |                                                         ^     ~~~~~~~~~~~~~
```

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

File: src/native/physics/DebugDrawForwarder.cpp (hunk 5 above)
Comment (RyuDanuer) [reply src/native/physics/DebugDrawForwarder.cpp]: Fixed the compile issue in a978b3f by changing the internal triangle culling path to use the existing `JVec3` distance helper instead of passing stored forwarded vertices into the `RVec3Arg` helper. I also added the Boost no-exceptions shim to this older branch so the local MSVC `thrive_native` target links. The MSVC native build and scoped `files rewrite` check passed.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
This compiles for me again, but I see no impact in the game the two saves I had that show the broken state are still broken. Can you share your testing results? Maybe show a screenshot of the changes working, because otherwise I will just close this.

**Comment by RyuDanuer** [comment]
Pushed 96fbf5046. The missing piece was Godot culling the debug-draw mesh itself: the custom AABB was anchored near world origin, so in this save/camera position the whole mesh could still be outside the render bounds. It now follows the active camera.

Tested on my pc with the provided `auto_save_2.thrivesave`, btw. I rebuilt the native debug libs locally, loaded the save, enabled physics debug draw, and got this in-game screenshot:

physics debug draw working

Also ran `dotnet build Thrive.sln`, `dotnet run --project Scripts -- check files`, and `cmake --build build-debug --config Debug --target install -- /m:6`.

**Comment by hhyyrylainen** [comment]
Thank you for testing in the game. I can also confirm that this now also works for me!

I wanted to investigate this and I think the core issue was the bounding box, right? So I did some tweaking and removed the culling (but I did keep the sorting so that closest lines to the camera are kept when there are a lot of them).

If everything is fine with my changes to this branch, I'll merge this and then make the bumped native libs version so that everyone starts using these then.

**Review by hhyyrylainen — APPROVED** [review]
I did quite thorough testing and I think this now works. I removed the priority-based culling as it didn't even trigger in the bugged save and it was I think a bit unnecessary (though it would be easy to add back if wanted), I still kept the sorting though so that when there's a lot of debug drawing (even more than the problematic save) then the lines are sorted by closeness so that drawing will still happen for the most important lines. I removed the C# side camera updates as the C++ side seems fully capable of that.

It seems the core bug was that the "quiteBigAABB" was not big enough and thus moving it along the camera position was what fixed the problem. I only tested on Linux as I don't expect these changes to be able to break this for other platforms.

**Comment by hhyyrylainen** [comment]
Looks like the checks are again finding new random stuff, I'll just merge this and put the fix onto master.

**Comment by xfractalino** [comment]
Unfortunately, I just tested this branch right now but the physics debug draw still doesn't work for me in large saves. I want to specify I run the game with AVX disabled, so it might have something to do with that.

**Comment by hhyyrylainen** [comment]
Did you make sure you used a new version? This PR *does not* bump the native libs version so the game will happily load an older version for you. I plan to do that separate PR updating the native lib version in an hour or two. Which will ensure everyone will then be forced to use the new version (which is not currently yet the case).

**Comment by xfractalino** [comment]
Okay, maybe that's the issue since I don't compile the libs myself. I'll wait and update you in a few hours.

**Comment by RyuDanuer** [comment]
﻿Yeah, that matches my testing too. The core issue was the debug mesh bounds/AABB not covering the camera-relative debug draw, so Godot could cull the whole thing even though the lines existed. Keeping the bounds centered around the active camera is the important fix; the sorting is fine to keep.
