### PR TITLE
Options menu can open in different modes

### LINKED ISSUE #1217: Make during gameplay options control tutorial status
Maybe also warn the player if they change some option that can't be applied without restarting. Right now only one is probably the cloud resolution but that is broken anyway, but code should be implemented to allow a popup to say to the player that you changed an option that can't be applied instantly.

Once https://github.com/Revolutionary-Games/Thrive/issues/1502 is done this needs to act so that the tutorials option applies to the current game instead of globally.

- [x] implemented
- [ ] handles disabling / enabling tutorial in the current game correctly
- [ ] re-disable the tutorial if freebuild is on (if trying to re-enable in options menu)

### PR DESCRIPTION
**Pull request by Satharis**
Changed options so it can be opened with different methods in game vs on the main menu. Currently only displays a setting for tutorials being enabled or disabled in the current game.

As a note: While it technically enables and disables the tutorial correctly, the tutorial code doesn't quite handle the state switching that elegantly. Enabling the tutorials for the first time won't display the initial opening tutorial, and toggling the enabled state off and on seems to make it skip whatever the previous objective was.

Closes #1217

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
I didn't envision that enabling the tutorial would replay all of the tutorials that were skipped, properly. I think mainly it should work for future tutorials. And the more important way the option is to be used, is to disable the tutorials as there's no way to do that after the initial popup.

File: src/general/OptionsMenu.cs [hunk 1]
```diff
@@ -202,6 +216,12 @@ public class OptionsMenu : Control
     [Signal]
     public delegate void OnOptionsClosed();
 
+    public enum OptionsMode
+    {
+        MainMenu,
+        MicrobeStage,
```
Comment (hhyyrylainen) [inline src/general/OptionsMenu.cs:222]: I think this should be named "InGame"

File: src/general/OptionsMenu.cs [hunk 2]
```diff
@@ -258,32 +273,87 @@ public override void _Ready()
...
+        tutorialsEnabled = GetNode<CheckBox>(TutorialsEnabledPath);
 
         backConfirmationBox = GetNode<WindowDialog>(BackConfirmationBoxPath);
         defaultsConfirmationBox = GetNode<ConfirmationDialog>(DefaultsConfirmationBoxPath);
         errorAcceptBox = GetNode<AcceptDialog>(ErrorAcceptBoxPath);
 
         selectedOptionsTab = SelectedOptionsTab.Graphics;
+    }
+
+    public override void _Process(float delta)
```
Comment (hhyyrylainen) [inline src/general/OptionsMenu.cs:291]: Empty method

File: src/general/OptionsMenu.cs [hunk 3]
```diff
@@ -314,24 +384,41 @@ public void ApplySettingsToControls(Settings settings)
...
         autosave.Pressed = settings.AutoSaveEnabled;
         maxAutosaves.Value = settings.MaxAutoSaves;
         maxAutosaves.Editable = settings.AutoSaveEnabled;
         maxQuicksaves.Value = settings.MaxQuickSaves;
     }
 
-    private void SetSettingsTab(string tab)
+    private void SwitchMode(OptionsMode mode)
+    {
+        if (mode == OptionsMode.MainMenu)
```
Comment (hhyyrylainen) [inline src/general/OptionsMenu.cs:397]: Switch statement should be preferred when checking enum values

File: src/general/OptionsMenu.cs [hunk 4]
```diff
@@ -314,24 +384,41 @@ public void ApplySettingsToControls(Settings settings)
...
+            // Hide the local game settings if opened from the main menu.
+            localSettingsVBox.Hide();
+            optionsMode = OptionsMode.MainMenu;
+        }
+        else if (mode == OptionsMode.MicrobeStage)
+        {
+            // Show the local game settings if opened from the microbe stage or editor.
+            localSettingsVBox.Show();
+            optionsMode = OptionsMode.MicrobeStage;
+        }
```
Comment (hhyyrylainen) [inline src/general/OptionsMenu.cs:408]: Add an error throw if mode is unknown

File: src/general/OptionsMenu.cs [hunk 5]
```diff
@@ -370,12 +457,12 @@ private void SetSettingsTab(string tab)
     /// </summary>
     private float ConvertSoundBarToDb(float value)
     {
-        return (value - 100) / AUDIO_BAR_SCALE;
+        return GD.Linear2Db(value / 100.0f);
```
Comment (hhyyrylainen) [inline src/general/OptionsMenu.cs:460]: Why was this change done? What does this do?

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
I think you accidentally moved one of the separators:


this is after:


Also I think that the same checkbox that is used for new tutorial state, should be used for also the in-game tutorial state. I don't particularly like the new section for settings specific to current game, as I can't imagine more settings being put there, definitely no world generation tweaks and such will be put there. Maybe a future difficulty option could be put there. I guess I'll see if GUI people agree with me.

Here's a screenshot of it:

**Comment by Satharis** [comment]
I didn't accidentally move it, I moved it so it was split into global and current game settings.

I split the tutorials enabled thing into a separate panel because I thought having them be the same button would be incredibly cryptic. You could look at options on the main menu, see it enabled, load a save, open the menu and now it's unchecked. Now you go out to the main menu and it's checked again. I'm not sure what you would write on that button that would easily convey to the user that when on the main menu it is global and applied to all new games, and when in game it only toggles it on that game, and gets saved/loaded with your save.

**Comment by hhyyrylainen** [comment]
That's why I had in parenthesis written for (new games), I imagined that it would change to `(for current save / game)` when the options is opened from in-game.

File: src/general/OptionsMenu.cs (hunk 5 above)
Comment (Satharis) [reply src/general/OptionsMenu.cs:460]: It uses a more proper logarithm conversion to decibels, it also handles silencing the audio if it gets down to 0, vs it being at a really low volume like it was before. The mute checkbox still works on top of that. Unless I misunderstood something, that division by 6.0f ends up with notable amounts of error, like 10% volume should be -20 db but it's -15 with that.

**Comment by Satharis** [comment]
I mean I could change it to that but I also thought it was nice that you had the option to enable/disable the global setting from in game as well, with them being distinct options.

File: src/general/OptionsMenu.cs (hunk 1 above)
Comment (Satharis) [reply src/general/OptionsMenu.cs:222]: I had it like that because I wasn't sure if the options would need to change when opened from another stage at some point.

File: src/general/OptionsMenu.cs (hunk 2 above)
Comment (Satharis) [reply src/general/OptionsMenu.cs:291]: It's like that in master, am I supposed to remove it? I think it's only showing as a diff because it got moved.

File: src/general/OptionsMenu.cs (hunk 5 above)
Comment (hhyyrylainen) [reply src/general/OptionsMenu.cs:460]: I suppose that's fine, then.

File: src/general/OptionsMenu.cs (hunk 2 above)
Comment (hhyyrylainen) [reply src/general/OptionsMenu.cs:291]: Please remove it, it unnecessarily runs each frame.

File: src/general/OptionsMenu.cs (hunk 1 above)
Comment (hhyyrylainen) [reply src/general/OptionsMenu.cs:222]: I don't foresee there being a need for stage specific options. It will be later confusing when each stage needs to say to the options "yeah, I'm the microbe stage (when I'm really the space stage)"
Even if there are stage specific options, they should all be always visible.

**Comment by hhyyrylainen** [comment]
I can see both sides, but for logical consistency I'd like to have a separator also before the cheats option.
I'm hoping more people will pitch in on the #gui channel.

**Review by hhyyrylainen — APPROVED** [review]
I think there's nothing left to fix in this one
