### PR TITLE
Fix processes' toggle buttons not matching their actual state

### LINKED ISSUE #5420: Process toggle buttons sometimes don't match process state
I was able to find two cases when this happens:
1. When exiting editor with a new organelle, the process speed of which is immediately zero (because of having no needed compound or something like that). For example, placing rusticyanin while having no iron or thylakoids in a patch with no light. The process is shown as turned off. After gathering needed resources, however, the process starts to run (the button still shows it as turned off).
2. If a process was manually turned off, it starts to run again after an editor session. However, it is still shown as turned off.

Picture after exiting editor and getting resources required for processes to run:
image
Some processes run, even though they are turned off.

### PR DESCRIPTION
**Pull request by dligr**
**Brief Description of What This PR Does**

Fixes process toggle buttons being de-synced from their processes' actual state.

Does so by making process displays get the toggle state directly from the process, instead of using a local variable. This also allows those states to be saved.

Also, makes TweakedProcesses' speed multipliers save when they are updated (e.g. when an organelle duplicates).

**Related Issues**

Fixes #5420

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by dligr** [comment]
I have noticed while testing that process toggles don't work on cell colonies (at least, on other members of those colonies). I hope that it's fine if I fixed it too with this PR.

**Comment by hhyyrylainen** [comment]
It's most likely fine, but I have slight concern if that has understandability problems because https://github.com/Revolutionary-Games/Thrive/issues/3207 is not done. But I guess in most situations where like for efficiency reasons players want to toggle processes it's fine as the colony compound distribution will make sure that other colony members can basically do the same processes as the lead cell.

File: src/gui_common/ChemicalEquation.cs [hunk 1]
```diff
@@ -102,14 +100,19 @@ public bool ShowToggle
...
+            if (EquationFromProcess == null)
+                return true;
+
+            return EquationFromProcess.Enabled;
+        }
         set
         {
-            if (value == lastToggle)
+            if (EquationFromProcess == null)
                 return;
```
Comment (hhyyrylainen) [inline src/gui_common/ChemicalEquation.cs:113]: I think this should print an error message in case there's a programmer error in the future (so that it'll be quicker to diagnose).

File: src/microbe_stage/TweakedProcess.cs [hunk 2]
```diff
@@ -4,13 +4,7 @@
...
 ///   A concrete process that organelle does. Applies a modifier to the process
 /// </summary>
-/// <remarks>
-///   <para>
-///     This is a struct as this just packs a few floats and a single object reference in here. This allows much tighter
-///     data packing when this is used in lists.
-///   </para>
-/// </remarks>
-public struct TweakedProcess : IEquatable<TweakedProcess>
+public class TweakedProcess : IEquatable<TweakedProcess>
```
Comment (hhyyrylainen) [inline src/microbe_stage/TweakedProcess.cs:7]: This is a pretty major change to no longer have this as a struct, and will now have temporary memory allocation consequences.

File: src/microbe_stage/StrictProcessDisplayInfoEquality.cs [hunk 3]
```diff
@@ -33,6 +33,9 @@ public bool Equals(StrictProcessDisplayInfoEquality? other)
         var our = DisplayInfo;
         var theirs = other.DisplayInfo;
 
+        if (our.Enabled != theirs.Enabled)
```
Comment (hhyyrylainen) [inline src/microbe_stage/StrictProcessDisplayInfoEquality.cs:36]: The whole process equality comparisons is a bit of a mess and changing any of the code here can cause bugs in a bunch of places. I think the enabled state probably should not be compared here as having a process speed display show the same item twice but another is disabled while the other is enabled doesn't seem like a good idea to me.

File: src/microbe_stage/systems/ProcessSystem.cs [hunk 4]
```diff
@@ -61,6 +61,13 @@ public static void ComputeActiveProcessList(IReadOnlyList<IPositionedOrganelle>
     {
         result ??= new List<TweakedProcess>();
 
+        var speedMultipliers = new Dictionary<BioProcess, float>();
```
Comment (hhyyrylainen) [inline src/microbe_stage/systems/ProcessSystem.cs:64]: This code should be rewritten to not use this extra temporary memory.

File: src/microbe_stage/ProcessStatistics.cs [hunk 5]
```diff
@@ -412,6 +418,10 @@ public override bool Equals(object? obj)
         // This also checks for obj being null
         if (obj is AverageProcessStatistics statistics)
         {
+            GD.Print(owner.Equals(statistics.owner));
```
Comment (hhyyrylainen) [inline src/microbe_stage/ProcessStatistics.cs:421]: This looks like a debug print.

File: src/microbe_stage/ProcessStatistics.cs [hunk 6]
```diff
@@ -412,6 +418,10 @@ public override bool Equals(object? obj)
...
+            if (owner.Process.SpeedMultiplier != statistics.owner.Process.SpeedMultiplier)
+                GD.Print("Speed multiplier mismatch!");
```
Comment (hhyyrylainen) [inline src/microbe_stage/ProcessStatistics.cs:423]: Is this an error condition? (also the message should be a bit more specific because if we get logs with this message in them, that will really confuse whoever is trying to determine the problem).

File: src/microbe_stage/ProcessStatistics.cs [hunk 7]
```diff
@@ -312,6 +309,7 @@ public override bool Equals(object? obj)
         // This also checks for obj being null
         if (obj is SingleProcessStatistics statistics)
         {
+            GD.Print(Process.Equals(statistics.Process));
```
Comment (hhyyrylainen) [inline src/microbe_stage/ProcessStatistics.cs:312]: Another debug print.

File: src/microbe_stage/ProcessStatistics.cs [hunk 8]
```diff
@@ -322,6 +320,10 @@ public bool Equals(SingleProcessStatistics? other)
     {
         if (ReferenceEquals(null, other))
             return false;
+
+        if (Process.SpeedMultiplier != other.Process.SpeedMultiplier)
+            GD.Print("Speed multiplier mismatch!");
```
Comment (hhyyrylainen) [inline src/microbe_stage/ProcessStatistics.cs:325]: This seems like a debug print?

File: src/microbe_stage/ProcessStatistics.cs [hunk 9]
```diff
@@ -15,24 +15,19 @@ public class ProcessStatistics
...
     /// </summary>
-    private List<BioProcess>? temporaryRemovedItems;
+    private List<TweakedProcess>? temporaryRemovedItems;
 
     /// <summary>
     ///   The processes and their associated speed statistics
     /// </summary>
     /// <remarks>
     ///   <para>
-    ///     This uses <see cref="BioProcess"/> rather than <see cref="TweakedProcess"/> as the key so that equality
```
Comment (hhyyrylainen) [inline src/microbe_stage/ProcessStatistics.cs:25]: This is another point that I think is causing some pretty major architectural problems here. I didn't yet check every single place, that these changes impact, but my impression is that all of the code depending on the assumptions about the code that has been changed in this PR have not been updated yet.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
I think this is a pretty good design for this problem and one that can fix the toggle states getting out of sync. What I have significant concerns about is the change of that one struct to a class which majorly changes all memory usage and allocations related to it, which is something I've relied on greatly in the process system for maximum efficiency. I think as a result the changes here need to be considered more.

File: src/microbe_stage/TweakedProcess.cs (hunk 2 above)
Comment (dligr) [reply src/microbe_stage/TweakedProcess.cs]: Apparently, because of how process updating works, this change was unnecessary

Comment (hhyyrylainen) [reply src/microbe_stage/TweakedProcess.cs]: That's actually very good to hear, so this PR might be able to be polished up easily, then.

File: src/microbe_stage/ProcessStatistics.cs [hunk 10]
```diff
@@ -71,13 +66,8 @@ public void RemoveUnused()
         }
     }
 
-    public SingleProcessStatistics GetAndMarkUsed(BioProcess forProcess)
+    public SingleProcessStatistics GetAndMarkUsed(TweakedProcess forProcess)
     {
-#if DEBUG
```
Comment (hhyyrylainen) [inline src/microbe_stage/ProcessStatistics.cs:76]: I think this debug code could be updated to check if the process inside the tweaked process is valid. That would keep this safety check (that only is in debug mode, so active for only programmers) in-place.

File: src/microbe_stage/TweakedProcess.cs [hunk 11]
```diff
@@ -50,7 +50,8 @@ public bool Equals(TweakedProcess other)
             return false;
 
         // ReSharper disable once CompareOfFloatsByEqualityOperator
-        return Rate == other.Rate && ReferenceEquals(Process, other.Process);
+        return Rate == other.Rate && SpeedMultiplier == other.SpeedMultiplier
```
Comment (hhyyrylainen) [inline src/microbe_stage/TweakedProcess.cs:53]: Adding comparing the speed multiplier here, I think might break some grouping of process displays...

So I would remove this change.

Comment (dligr) [reply src/microbe_stage/TweakedProcess.cs:53]: I don't think it's right, because if processes with different states are considered equal, then they aren't correctly updated on GUI, unless I'm missing something.

Comment (hhyyrylainen) [reply src/microbe_stage/TweakedProcess.cs:53]: Have you playtested and confirmed that is a bug? Kind of unhelpfully the process list detection uses equality to combine items, so too strict checking can result in a situation where duplicates get created into the process list.

Comment (hhyyrylainen) [reply src/microbe_stage/TweakedProcess.cs:53]: It's true that if this isn't the type of equality used in the GUI combining (and that doesn't call this equality in turn), this should be fine. Though, the last time I tried to improve the process equality checks to be more accurate, I totally messed up the process speed panel to show each instance of a process separately (instead of keeping the functionality where all organelles are summed into one process of each type). I'll need to check this carefully when doing the next review (after the extra temporary memory use is solved).

File: src/microbe_stage/systems/ProcessSystem.cs (hunk 4 above)
Comment (dligr) [reply src/microbe_stage/systems/ProcessSystem.cs:64]: Should the Dictionary be stored outside of the method's domain?

Comment (hhyyrylainen) [reply src/microbe_stage/systems/ProcessSystem.cs:64]: Yes, if there's truly no way to write the logic in a way that doesn't require this store first and then apply approach.

File: src/microbe_stage/systems/ProcessSystem.cs [hunk 12]
```diff
@@ -32,6 +32,8 @@ namespace Systems;
 [RuntimeCost(55)]
 public sealed class ProcessSystem : AEntitySetSystem<float>
 {
+    private static readonly Dictionary<BioProcess, float> TempSpeedMultipliers = new();
```
Comment (hhyyrylainen) [inline src/microbe_stage/systems/ProcessSystem.cs:35]: I'm pretty sure this is a massive problem as ComputeActiveProcessList has to be thread safe.

Comment (dligr) [reply src/microbe_stage/systems/ProcessSystem.cs:35]: Would it be right to put all of `ComputeActiveProcessList`'s code in a `lock` statement? Only a single thread would then be able to access the dictionary at a time, though that would worsen performance

Comment (hhyyrylainen) [reply src/microbe_stage/systems/ProcessSystem.cs:35]: I wouldn't because this then becomes a bottleneck. If there truly is no way to avoid the temp memory, then the approach where the method caller must provide the working memory should be used (look at for example how the hex adding methods in the hex layout class require multiple working memory parameters to work).

Comment (dligr) [reply src/microbe_stage/systems/ProcessSystem.cs]: This is done now. Each microbe spawn now requires an extra memory allocation, though.

File: src/microbe_stage/systems/EndosymbiontOrganelleSystem.cs [hunk 13]
```diff
@@ -74,7 +75,7 @@ protected override void Update(float state, in Entity entity)
                     // times and when not empty mostly just once
                     organelleContainer.OnOrganellesChanged(ref entity.Get<CompoundStorage>(),
                         ref entity.Get<BioProcesses>(), ref entity.Get<Engulfer>(), ref entity.Get<Engulfable>(),
-                        ref entity.Get<CellProperties>());
+                        ref entity.Get<CellProperties>(), tempProcessListMemory);
```
Comment (hhyyrylainen) [inline src/microbe_stage/systems/EndosymbiontOrganelleSystem.cs:78]: The list must be locked as this can run multithreaded. See for example line 100 how the hexWorkData has to be locked.

File: src/microbe_stage/systems/MicrobeReproductionSystem.cs [hunk 14]
```diff
@@ -623,7 +624,7 @@ private void ReadyToReproduce(in Entity entity, ref OrganelleContainer organelle
                     // Return the first cell to its normal, non duplicated cell arrangement and spawn a daughter cell
                     organelles.ResetOrganelleLayout(ref entity.Get<CompoundStorage>(),
                         ref entity.Get<BioProcesses>(),
-                        entity, species, species, worldSimulation, workData1, workData2);
+                        entity, species, species, worldSimulation, workData1, workData2, tempProcessListMemory);
```
Comment (hhyyrylainen) [inline src/microbe_stage/systems/MicrobeReproductionSystem.cs:627]: This also has to lock the data.

File: src/microbe_stage/systems/ProcessSystem.cs [hunk 15]
```diff
@@ -57,10 +57,15 @@ public ProcessSystem(World world, IParallelRunner runner) : base(world, runner,
...
     /// </remarks>
     public static void ComputeActiveProcessList(IReadOnlyList<IPositionedOrganelle> organelles,
-        [NotNull] ref List<TweakedProcess>? result)
+        [NotNull] ref List<TweakedProcess>? result, Dictionary<BioProcess, float> tempStorage)
     {
         result ??= new List<TweakedProcess>();
 
+        foreach (var process in result)
+        {
+            tempStorage.TryAdd(process.Process, process.SpeedMultiplier);
```
Comment (hhyyrylainen) [inline src/microbe_stage/systems/ProcessSystem.cs:66]: For the hex work data the pattern I usually use is that the data is cleared just before use, this way if an exception breaks the game and skips the data clear, that won't cause compounding errors after that.

File: src/general/world_effects/PhotosynthesisProductionEffect.cs [hunk 16]
```diff
@@ -50,6 +50,8 @@ private void ApplyCompoundsAddition()
             float oxygenBalance = 0;
             float co2Balance = 0;
 
+            Dictionary<BioProcess, float> tempStorage = new();
```
Comment (hhyyrylainen) [inline src/general/world_effects/PhotosynthesisProductionEffect.cs:53]: This should be allocated outside the loop.

File: src/microbe_stage/ProcessStatistics.cs [hunk 17]
```diff
@@ -71,13 +66,12 @@ public void RemoveUnused()
...
 
-    public SingleProcessStatistics GetAndMarkUsed(BioProcess forProcess)
+    public SingleProcessStatistics GetAndMarkUsed(TweakedProcess forProcess)
     {
 #if DEBUG
-        if (forProcess == null!)
+        if (forProcess.Process == null!)
             throw new ArgumentException("Invalid process marked used");
 #endif
-
```
Comment (hhyyrylainen) [inline src/microbe_stage/ProcessStatistics.cs:80]: I think the blank line after a pragma looks much better than code being all bunched up.

File: src/microbe_stage/ProcessStatistics.cs [hunk 18]
```diff
@@ -154,6 +148,8 @@ public float CurrentSpeed
         }
     }
 
+    public bool Enabled => Process.SpeedMultiplier > 0.5f;
```
Comment (hhyyrylainen) [inline src/microbe_stage/ProcessStatistics.cs:151]: Wouldn't it be better to show it enabled if the value is above 0? I think somewhere else there's also a similar threshold so unless they both use zero, I'd put the magic value in Constants to make sure a consistent value is used.

File: src/microbe_stage/systems/ProcessSystem.cs [hunk 19]
```diff
@@ -57,10 +57,15 @@ public ProcessSystem(World world, IParallelRunner runner) : base(world, runner,
     ///   </para>
     /// </remarks>
     public static void ComputeActiveProcessList(IReadOnlyList<IPositionedOrganelle> organelles,
-        [NotNull] ref List<TweakedProcess>? result)
+        [NotNull] ref List<TweakedProcess>? result, Dictionary<BioProcess, float> tempStorage)
     {
         result ??= new List<TweakedProcess>();
 
+        foreach (var process in result)
```
Comment (hhyyrylainen) [inline src/microbe_stage/systems/ProcessSystem.cs:64]: Could you add a comment here that this block of code is for remembering the existing speed multiplier states?

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
At least the couple data locks have to be added I commented on at a minimum.

I still have this vague idea in my head that it would be better to do this without the temp memory.

Here's an idea I just had: what if TweakedProcess gets added an `internal bool Marked` field and then the ComputeActiveProcessList method uses that to detect what is a new entry and what is an old one? That way the process speeds can be copied from an existing process entry to a newly created one inside the loop. And then instead of calling `result.Clear` the clearing could be done by removing the entries that didn't have the marked field set. Does that sound doable?

File: src/microbe_stage/systems/ProcessSystem.cs [hunk 20]
```diff
@@ -106,9 +117,25 @@ public static void ComputeActiveProcessList(IReadOnlyList<IPositionedOrganelle>
...
 
                 // If not found, then create a new result
-                result.Add(new TweakedProcess(process.Process, process.Rate));
+                var newProcess = new TweakedProcess(processKey, process.Rate);
+                newProcess.Marked = true;
+                result.Add(newProcess);
             }
         }
+
+        int writeIndex = 0;
```
Comment (hhyyrylainen) [inline src/microbe_stage/systems/ProcessSystem.cs:126]: My last comment. This block of code could do with a comment saying this removes the unmarked processes to not keep processes around that don't exist anymore, and also for efficiency this handles unmarking processes that are kept.

**Review by hhyyrylainen — APPROVED** [review]
I think the code is perfect now. I'll do some final testing tomorrow, unless someone else gets to it first, before merging this.

**Comment by dligr** [comment]
Apparently, the process button used the `toggled()` signal (Godot-side), which is called when button's state is changed, even if it's changed from code. Which led to the unexpected behavior of the button toggling itself.

File: src/microbe_stage/TweakedProcess.cs [hunk 21]
```diff
@@ -50,7 +60,8 @@ public bool Equals(TweakedProcess other)
...
+            && ReferenceEquals(Process, other.Process);
```
Comment (hhyyrylainen) [inline src/microbe_stage/TweakedProcess.cs:64]: I think I was able to confirm that this change breaks the ProcessStatistics.GetAndMarkUsed so I will revert this change. (this now causes process panel process order to change when turning processes off and on)

**Review by hhyyrylainen — APPROVED** [review]
I did a fix for the process equality bug I found (it caused items in the process panel to jump around as I pressed the toggle buttons). Now everything should be working fine, though I'd greatly appreciate if you could double check my changes. I'm unsure if the logic for ordering the items back into the order they should be by moving the marked items to the start of the process data list is fully working, so especially double checking this bit of code would be good for avoiding bugs:
```c#
for (int l = 0; l < k; ++l)
{
    if (!result[l].Marked)
    {
        // Swap positions of the data, as we will write to the k index (that is updated)
        // we need to only write the moving away data to perform the swap
        result[k] = result[l];
        k = l;
        break;
    }
}
```

**Comment by dligr** [comment]
After some testing, I can confirm that the new changes work. Processes are now kept in a consistent order, and their toggling now changes their speed gradually. The changes to the ProcessSystem's process updating make sense to me too.
