### PR TITLE
Fix patch extinction animation not showing

### LINKED ISSUE #3543: Patch map in patch extinction screen doesn't animate correctly
Making this issue to make sure this isn't forgotten.

The patch map in the patch extinction box doesn't call _Process on the patch map nodes, for reasons I couldn't fathom after a while spent trying to fix it. This means the current patch border doesn't blink and hovered patch borders don't show.

### PR DESCRIPTION
**Pull request by 84634E1A607A**
Fixes #3543 

Turns out map is rebuilt every time so there isn't a chance for them to animate.

Personally I dislike the approach to attempt to update map every frame, but adding early return causes a crash. If you think this approach is acceptable, go on and merge this.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: src/microbe_stage/editor/PatchMapDrawer.cs [hunk 1]
```diff
@@ -49,7 +49,13 @@ public class PatchMapDrawer : Control
         get => map;
         set
         {
-            map = value ?? throw new ArgumentNullException(nameof(value), "setting to null not allowed");
+            if (value == null)
+                throw new ArgumentNullException(nameof(value), "setting to null not allowed");
+
+            if (map == value)
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/PatchMapDrawer.cs:55]: This seems like good idea, though, would you or someone else be able to check why the patch extinction drawer repeatedly sets the map property? That would be a good place to also fix.

Comment (84634E1A607A) [reply src/microbe_stage/editor/PatchMapDrawer.cs:55]:
```
PatchMapDrawer.set_Map() at D:\source\repos\Thrive\src\microbe_stage\editor\PatchMapDrawer.cs:line 53
PatchExtinctionBox.set_Map() at D:\source\repos\Thrive\src\microbe_stage\gui\PatchExtinctionBox.cs:line 27
StageHUDBase<MicrobeStage>.ShowPatchExtinctionBox()
StageBase<Microbe>.PlayerExtinctInPatch()
MicrobeStage.PlayerExtinctInPatch()
StageBase<Microbe>.HandlePlayerRespawn()
StageBase<Microbe>._Process()
MicrobeStage._Process()
```

Comment (hhyyrylainen) [reply src/microbe_stage/editor/PatchMapDrawer.cs:55]: So the ShowPatchExtinctionBox should be modified to be called just once only if the extinction screen is not open?

Comment (84634E1A607A) [reply src/microbe_stage/editor/PatchMapDrawer.cs:55]: I think so, but as I stated, it causes a crash.

Comment (hhyyrylainen) [reply src/microbe_stage/editor/PatchMapDrawer.cs:55]: Could someone help out here? If it takes more than a few days, I can take a look at this problem next week.

Comment (84634E1A607A) [reply src/microbe_stage/editor/PatchMapDrawer.cs:55]: I got it working.

Comment (hhyyrylainen) [reply src/microbe_stage/editor/PatchMapDrawer.cs:55]: Seems like a good approach. I'll try to ask for testing on this, especially if multiple patch extinctions happen in a row to make sure there's no bugs.

**Comment by Oliveriver** [comment]
Nicely done! I can confirm this works.

**Review by RacerBG — APPROVED** [review]
Indeed, it now blinks just like in the normal patch map.

**Comment by hhyyrylainen** [comment]
I'll assume people tested the multiple patch extinctions in a row case.

**Review by hhyyrylainen — APPROVED** [review]
Code changes look fine.
