### PR TITLE
Fix binding agent being able to placed without a nucleus

### LINKED ISSUE #2574: Binding agent can be placed without the nucleus
**To Reproduce**
1. Place a nucleus
2. Select Binding Agent
3. Undo placing the nucleus
4. Place the Binding Agent

**Screenshots**
image
image

Edit: Can't reproduce with other organelles.

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

The old eligible to place check in `AddOrganelle` for organelles that requires nucleus is a bit unreliable as it depends on a couple of variables one of which doesn't necessarily state whether an organelle is prokaryote-only.

**Related Issues**

Fixes #2574 

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

File: src/microbe_stage/editor/MicrobeEditor.cs [hunk 1]
```diff
@@ -1887,8 +1887,7 @@ private bool AddOrganelle(OrganelleTemplate organelle)
         // 1 - you put nucleus but you already have it
         // 2 - you put organelle that need nucleus and you don't have it
```
Comment (Maxonovien) [inline src/microbe_stage/editor/MicrobeEditor.cs:1888]:
```suggestion
        // 2 - you put organelle that requires nucleus but you don't have one
```

**Review by Maxonovien — APPROVED** [review]
Simple yet effective code rework, perhaps it might be an occasion to fix a small typo in a comment -- and perhaps rephrase it alongside? Just a suggestion, I'm fine as is (as long as it is ok with testers).

File: src/microbe_stage/editor/MicrobeEditor.cs (hunk 1 above)
Comment (FuJa0815) [reply src/microbe_stage/editor/MicrobeEditor.cs:1888]: actually, this comment is a bit more outdated.
This code does not only check the uniqueness of the nucleus, it also checks the uniqueness of other organelles (currently only BA and Nucleus)

Comment (Kasterisk) [reply src/microbe_stage/editor/MicrobeEditor.cs]: Reworded the comment into:
```
// 1 - you put a unique organelle (means only one instance allowed) but you already have it
// 2 - you put organelle that requires nucleus but you don't have one
```

File: src/microbe_stage/editor/MicrobeEditor.cs [hunk 2]
```diff
@@ -1884,11 +1884,10 @@ private void UndoOrganellePlaceAction(MicrobeEditorAction action)
 
     private bool AddOrganelle(OrganelleTemplate organelle)
     {
-        // 1 - you put nucleus but you already have it
-        // 2 - you put organelle that need nucleus and you don't have it
+        // 1 - you put a unique organelle (means only one instance allowed) but you already have it
+        // 2 - you put organelle that requires nucleus but you don't have one
```
Comment (Maxonovien) [inline src/microbe_stage/editor/MicrobeEditor.cs:1888]:
```suggestion
        // 2 - you put an organelle that requires nucleus but you don't have one
```
Just determiner consistency, but the comment change is nice already

**Review by hhyyrylainen — APPROVED** [review]
Functionality seems fine. I agree with the suggested wording change that the comment could be improved.
