### PR TITLE
Make changing the membrane in the editor work

### LINKED ISSUE #1141: Fix changing the membrane in the editor
Unless I'm completely blind changing the membrane in the editor doesn't work.

Some things that need to be fixed for this:
- [ ] membrane is applied on player when exiting
- [ ] the membrane change costs MP and can be undone / redone
- [ ] the membrane change recalculates atp balance

### PR DESCRIPTION
**Pull request by GatoCreador887**
Close #1141.

### CODE REVIEW

File: src/microbe_stage/Membrane.cs [hunk 1]
```diff
@@ -364,8 +364,10 @@ private void ApplyTint()
 
     private void ApplyTextures()
     {
-        if (normalTexture != null)
-            return;
+        // We must update the texture on already-existing membranes,
+        // due to the membrane texture changing for the player microbe.
+        // if (normalTexture != null)
+        //     return;
```
Comment (hhyyrylainen) [inline src/microbe_stage/Membrane.cs:370]: I think that instead of removing this check instead what could be done is adding a new string field called `currentlyLoadedNormalTexture` which would have the texture path.
And then this check could be `if(normalTexture != null && currentlyLoadedNormalTexture == Type.NormalTexture)`

File: src/microbe_stage/editor/MicrobeEditorGUI.cs [hunk 2]
```diff
@@ -651,11 +651,33 @@ internal void ResetSymmetryButton()
 
     internal void OnMembraneSelected(string membrane)
     {
-        // todo: Send selected membrane to the editor script
+        editor.SetMembrane(membrane);
+    }
 
+    internal void SetSpeciesInfo(string name, MembraneType membrane, Color colour,
```
Comment (hhyyrylainen) [inline src/microbe_stage/editor/MicrobeEditorGUI.cs:657]: Should this already call UpdateMembraneButtons as this is given the membrane as a parameter?
